// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: ActiveModelConfig_t (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_ACTIVEMODELCONFIG_T_HPP
#define ISDK_ACTIVEMODELCONFIG_T_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct ActiveModelConfig_t {
    SCHEMA_CLASS("client.dll", "ActiveModelConfig_t");


    // --- Virtual functions (vtable RVA: 0x19C0D18, 9 total) ---
};

} // namespace sdk

#endif // ISDK_ACTIVEMODELCONFIG_T_HPP

