// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: AI_DefaultNPC_DebugSnapshotData_t (runtime-resolved offsets)
// Module: client.dll
// Parent: DebugSnapshotBaseStructuredData_t
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_AI_DEFAULTNPC_DEBUGSNAPSHOTDATA_T_HPP
#define ISDK_AI_DEFAULTNPC_DEBUGSNAPSHOTDATA_T_HPP

#include "../schema_runtime.hpp"
#include "DebugSnapshotBaseStructuredData_t.hpp"

namespace sdk {

struct AI_DefaultNPC_DebugSnapshotData_t : DebugSnapshotBaseStructuredData_t {
    SCHEMA_CLASS("client.dll", "AI_DefaultNPC_DebugSnapshotData_t");


    // --- Virtual functions (vtable RVA: 0x19CED80, 5 total) ---
};

} // namespace sdk

#endif // ISDK_AI_DEFAULTNPC_DEBUGSNAPSHOTDATA_T_HPP

