// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: AmmoTypeInfo_t (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_AMMOTYPEINFO_T_HPP
#define ISDK_AMMOTYPEINFO_T_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct AmmoTypeInfo_t {
    SCHEMA_CLASS("client.dll", "AmmoTypeInfo_t");


    // --- Virtual functions (vtable RVA: 0x19C29C8, 4 total) ---
    VFUNC_RAW(0);                                           // sig: 40 53 48 83 EC 20 48 8B DA 48 8D 15 ? ? ...
    VFUNC_RAW(1);                                           // sig: E9 ? ? ? ? CC CC CC CC CC CC CC CC CC CC...
    VFUNC_RAW(2);                                           // sig: 4C 8D 05 ? ? ? ? E9 ? ? ? ? CC CC CC CC ...
};

} // namespace sdk

#endif // ISDK_AMMOTYPEINFO_T_HPP

