// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: C_BaseButton (runtime-resolved offsets)
// Module: client.dll
// Parent: C_BaseToggle
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_C_BASEBUTTON_HPP
#define ISDK_C_BASEBUTTON_HPP

#include "../schema_runtime.hpp"
#include "C_BaseToggle.hpp"

namespace sdk {

struct C_BaseButton : C_BaseToggle {
    SCHEMA_CLASS("client.dll", "C_BaseButton");


    // --- Virtual functions (vtable RVA: 0x19C3390, 245 total) ---
};

} // namespace sdk

#endif // ISDK_C_BASEBUTTON_HPP

