// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: C_Chicken (runtime-resolved offsets)
// Module: client.dll
// Parent: C_DynamicProp
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_C_CHICKEN_HPP
#define ISDK_C_CHICKEN_HPP

#include "../schema_runtime.hpp"
#include "C_DynamicProp.hpp"

namespace sdk {

struct C_Chicken : C_DynamicProp {
    SCHEMA_CLASS("client.dll", "C_Chicken");


    // --- Virtual functions (vtable RVA: 0x1B44AF8, 283 total) ---
};

} // namespace sdk

#endif // ISDK_C_CHICKEN_HPP

