// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: C_CSGameRules (runtime-resolved offsets)
// Module: client.dll
// Parent: C_TeamplayRules
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_C_CSGAMERULES_HPP
#define ISDK_C_CSGAMERULES_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct C_CSGameRules {
    SCHEMA_CLASS("client.dll", "C_CSGameRules");


    // --- Virtual functions (vtable RVA: 0x1A515A8, 76 total) ---
};

} // namespace sdk

#endif // ISDK_C_CSGAMERULES_HPP

