// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: C_CSMinimapBoundary (runtime-resolved offsets)
// Module: client.dll
// Parent: C_BaseEntity
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_C_CSMINIMAPBOUNDARY_HPP
#define ISDK_C_CSMINIMAPBOUNDARY_HPP

#include "../schema_runtime.hpp"
#include "C_BaseEntity.hpp"

namespace sdk {

struct C_CSMinimapBoundary : C_BaseEntity {
    SCHEMA_CLASS("client.dll", "C_CSMinimapBoundary");


    // --- Virtual functions (vtable RVA: 0x1A5E068, 215 total) ---
};

} // namespace sdk

#endif // ISDK_C_CSMINIMAPBOUNDARY_HPP

