// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: C_DEagle (runtime-resolved offsets)
// Module: client.dll
// Parent: C_CSWeaponBaseGun
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_C_DEAGLE_HPP
#define ISDK_C_DEAGLE_HPP

#include "../schema_runtime.hpp"
#include "C_CSWeaponBaseGun.hpp"

namespace sdk {

struct C_DEagle : C_CSWeaponBaseGun {
    SCHEMA_CLASS("client.dll", "C_DEagle");


    // --- Virtual functions (vtable RVA: 0x1A9C410, 421 total) ---
};

} // namespace sdk

#endif // ISDK_C_DEAGLE_HPP

