// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: C_EnvCombinedLightProbeVolumeAlias_func_combined_light_probe_volume (runtime-resolved offsets)
// Module: client.dll
// Parent: C_EnvCombinedLightProbeVolume
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_C_ENVCOMBINEDLIGHTPROBEVOLUMEALIAS_FUNC_COMBINED_LIGHT_PROBE_VOLUME_HPP
#define ISDK_C_ENVCOMBINEDLIGHTPROBEVOLUMEALIAS_FUNC_COMBINED_LIGHT_PROBE_VOLUME_HPP

#include "../schema_runtime.hpp"
#include "C_EnvCombinedLightProbeVolume.hpp"

namespace sdk {

struct C_EnvCombinedLightProbeVolumeAlias_func_combined_light_probe_volume : C_EnvCombinedLightProbeVolume {
    SCHEMA_CLASS("client.dll", "C_EnvCombinedLightProbeVolumeAlias_func_combined_light_probe_volume");


    // --- Virtual functions (vtable RVA: 0x1981850, 215 total) ---
};

} // namespace sdk

#endif // ISDK_C_ENVCOMBINEDLIGHTPROBEVOLUMEALIAS_FUNC_COMBINED_LIGHT_PROBE_VOLUME_HPP

