// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: C_EnvCubemapFog (runtime-resolved offsets)
// Module: client.dll
// Parent: C_BaseEntity
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_C_ENVCUBEMAPFOG_HPP
#define ISDK_C_ENVCUBEMAPFOG_HPP

#include "../schema_runtime.hpp"
#include "C_BaseEntity.hpp"

namespace sdk {

struct C_EnvCubemapFog : C_BaseEntity {
    SCHEMA_CLASS("client.dll", "C_EnvCubemapFog");


    // --- Virtual functions (vtable RVA: 0x19821D0, 215 total) ---
};

} // namespace sdk

#endif // ISDK_C_ENVCUBEMAPFOG_HPP

