// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: C_Fish (runtime-resolved offsets)
// Module: client.dll
// Parent: CBaseAnimGraph
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_C_FISH_HPP
#define ISDK_C_FISH_HPP

#include "../schema_runtime.hpp"
#include "CBaseAnimGraph.hpp"

namespace sdk {

struct C_Fish : CBaseAnimGraph {
    SCHEMA_CLASS("client.dll", "C_Fish");


    // --- Virtual functions (vtable RVA: 0x1AEFCD0, 276 total) ---
};

} // namespace sdk

#endif // ISDK_C_FISH_HPP

