// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: C_fogplayerparams_t (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_C_FOGPLAYERPARAMS_T_HPP
#define ISDK_C_FOGPLAYERPARAMS_T_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct C_fogplayerparams_t {
    SCHEMA_CLASS("client.dll", "C_fogplayerparams_t");


    // --- Virtual functions (vtable RVA: 0x199EAF8, 8 total) ---
    VFUNC_RAW(0);                                           // sig: 40 53 48 83 EC 20 48 8B DA 48 8D 15 ? ? ...
    VFUNC_RAW(1);                                           // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(2);                                           // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(3);                                           // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(4);                                           // sig: E9 ? ? ? ? CC CC CC CC CC CC CC CC CC CC...
    VFUNC_RAW(5);                                           // sig: 4C 8D 05 ? ? ? ? E9 ? ? ? ? CC CC CC CC ...
    VFUNC_RAW(7);                                           // sig: 48 8B 05 ? ? ? ? C3 CC CC CC CC CC CC CC...
};

} // namespace sdk

#endif // ISDK_C_FOGPLAYERPARAMS_T_HPP

