// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: C_INIT_CreateParticleImpulse (runtime-resolved offsets)
// Module: client.dll
// Parent: CParticleFunctionInitializer
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_C_INIT_CREATEPARTICLEIMPULSE_HPP
#define ISDK_C_INIT_CREATEPARTICLEIMPULSE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct C_INIT_CreateParticleImpulse {
    SCHEMA_CLASS("client.dll", "C_INIT_CreateParticleImpulse");

};

} // namespace sdk

#endif // ISDK_C_INIT_CREATEPARTICLEIMPULSE_HPP

