// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: C_INIT_RemapNamedModelMeshGroupToScalar (runtime-resolved offsets)
// Module: client.dll
// Parent: C_INIT_RemapNamedModelElementToScalar
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_C_INIT_REMAPNAMEDMODELMESHGROUPTOSCALAR_HPP
#define ISDK_C_INIT_REMAPNAMEDMODELMESHGROUPTOSCALAR_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct C_INIT_RemapNamedModelMeshGroupToScalar {
    SCHEMA_CLASS("client.dll", "C_INIT_RemapNamedModelMeshGroupToScalar");

};

} // namespace sdk

#endif // ISDK_C_INIT_REMAPNAMEDMODELMESHGROUPTOSCALAR_HPP

