// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: C_INIT_RandomYaw (runtime-resolved offsets)
// Module: client.dll
// Parent: CGeneralRandomRotation
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_C_INIT_RANDOMYAW_HPP
#define ISDK_C_INIT_RANDOMYAW_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct C_INIT_RandomYaw {
    SCHEMA_CLASS("client.dll", "C_INIT_RandomYaw");

};

} // namespace sdk

#endif // ISDK_C_INIT_RANDOMYAW_HPP

