// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: C_INIT_RemapParticleCountToNamedModelMeshGroupScalar (runtime-resolved offsets)
// Module: client.dll
// Parent: C_INIT_RemapParticleCountToNamedModelElementScalar
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_C_INIT_REMAPPARTICLECOUNTTONAMEDMODELMESHGROUPSCALAR_HPP
#define ISDK_C_INIT_REMAPPARTICLECOUNTTONAMEDMODELMESHGROUPSCALAR_HPP

#include "../schema_runtime.hpp"
#include "C_INIT_RemapParticleCountToNamedModelElementScalar.hpp"

namespace sdk {

struct C_INIT_RemapParticleCountToNamedModelMeshGroupScalar : C_INIT_RemapParticleCountToNamedModelElementScalar {
    SCHEMA_CLASS("client.dll", "C_INIT_RemapParticleCountToNamedModelMeshGroupScalar");

};

} // namespace sdk

#endif // ISDK_C_INIT_REMAPPARTICLECOUNTTONAMEDMODELMESHGROUPSCALAR_HPP

