// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: C_INIT_RandomNamedModelBodyPart (runtime-resolved offsets)
// Module: client.dll
// Parent: C_INIT_RandomNamedModelElement
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_C_INIT_RANDOMNAMEDMODELBODYPART_HPP
#define ISDK_C_INIT_RANDOMNAMEDMODELBODYPART_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct C_INIT_RandomNamedModelBodyPart {
    SCHEMA_CLASS("client.dll", "C_INIT_RandomNamedModelBodyPart");

};

} // namespace sdk

#endif // ISDK_C_INIT_RANDOMNAMEDMODELBODYPART_HPP

