// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: C_Multimeter (runtime-resolved offsets)
// Module: client.dll
// Parent: CBaseAnimGraph
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_C_MULTIMETER_HPP
#define ISDK_C_MULTIMETER_HPP

#include "../schema_runtime.hpp"
#include "CBaseAnimGraph.hpp"

namespace sdk {

struct C_Multimeter : CBaseAnimGraph {
    SCHEMA_CLASS("client.dll", "C_Multimeter");


    // --- Virtual functions (vtable RVA: 0x1B36FC8, 276 total) ---
};

} // namespace sdk

#endif // ISDK_C_MULTIMETER_HPP

