// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: C_OP_RenderSprites (runtime-resolved offsets)
// Module: client.dll
// Parent: CBaseRendererSource2
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_C_OP_RENDERSPRITES_HPP
#define ISDK_C_OP_RENDERSPRITES_HPP

#include "../schema_runtime.hpp"
#include "CBaseRendererSource2.hpp"

namespace sdk {

struct C_OP_RenderSprites : CBaseRendererSource2 {
    SCHEMA_CLASS("client.dll", "C_OP_RenderSprites");

};

} // namespace sdk

#endif // ISDK_C_OP_RENDERSPRITES_HPP

