// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: C_OP_PlayEndCapWhenFinished (runtime-resolved offsets)
// Module: client.dll
// Parent: CParticleFunctionPreEmission
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_C_OP_PLAYENDCAPWHENFINISHED_HPP
#define ISDK_C_OP_PLAYENDCAPWHENFINISHED_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct C_OP_PlayEndCapWhenFinished {
    SCHEMA_CLASS("client.dll", "C_OP_PlayEndCapWhenFinished");

};

} // namespace sdk

#endif // ISDK_C_OP_PLAYENDCAPWHENFINISHED_HPP

