// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: C_OP_RadiusDecay (runtime-resolved offsets)
// Module: client.dll
// Parent: CParticleFunctionOperator
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_C_OP_RADIUSDECAY_HPP
#define ISDK_C_OP_RADIUSDECAY_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct C_OP_RadiusDecay {
    SCHEMA_CLASS("client.dll", "C_OP_RadiusDecay");

};

} // namespace sdk

#endif // ISDK_C_OP_RADIUSDECAY_HPP

