// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: C_OP_RemapNamedModelSequenceEndCap (runtime-resolved offsets)
// Module: client.dll
// Parent: C_OP_RemapNamedModelElementEndCap
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_C_OP_REMAPNAMEDMODELSEQUENCEENDCAP_HPP
#define ISDK_C_OP_REMAPNAMEDMODELSEQUENCEENDCAP_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct C_OP_RemapNamedModelSequenceEndCap {
    SCHEMA_CLASS("client.dll", "C_OP_RemapNamedModelSequenceEndCap");

};

} // namespace sdk

#endif // ISDK_C_OP_REMAPNAMEDMODELSEQUENCEENDCAP_HPP

