// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: C_OP_RenderSimpleModelCollection (runtime-resolved offsets)
// Module: client.dll
// Parent: CParticleFunctionRenderer
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_C_OP_RENDERSIMPLEMODELCOLLECTION_HPP
#define ISDK_C_OP_RENDERSIMPLEMODELCOLLECTION_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct C_OP_RenderSimpleModelCollection {
    SCHEMA_CLASS("client.dll", "C_OP_RenderSimpleModelCollection");

};

} // namespace sdk

#endif // ISDK_C_OP_RENDERSIMPLEMODELCOLLECTION_HPP

