// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: C_OP_RenderTrails (runtime-resolved offsets)
// Module: client.dll
// Parent: CBaseTrailRenderer
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_C_OP_RENDERTRAILS_HPP
#define ISDK_C_OP_RENDERTRAILS_HPP

#include "../schema_runtime.hpp"
#include "CBaseTrailRenderer.hpp"

namespace sdk {

struct C_OP_RenderTrails : CBaseTrailRenderer {
    SCHEMA_CLASS("client.dll", "C_OP_RenderTrails");

};

} // namespace sdk

#endif // ISDK_C_OP_RENDERTRAILS_HPP

