// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: C_OP_RenderLights (runtime-resolved offsets)
// Module: client.dll
// Parent: C_OP_RenderPoints
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_C_OP_RENDERLIGHTS_HPP
#define ISDK_C_OP_RENDERLIGHTS_HPP

#include "../schema_runtime.hpp"
#include "C_OP_RenderPoints.hpp"

namespace sdk {

struct C_OP_RenderLights : C_OP_RenderPoints {
    SCHEMA_CLASS("client.dll", "C_OP_RenderLights");

};

} // namespace sdk

#endif // ISDK_C_OP_RENDERLIGHTS_HPP

