// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: C_OP_ChooseRandomChildrenInGroup (runtime-resolved offsets)
// Module: client.dll
// Parent: CParticleFunctionPreEmission
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_C_OP_CHOOSERANDOMCHILDRENINGROUP_HPP
#define ISDK_C_OP_CHOOSERANDOMCHILDRENINGROUP_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct C_OP_ChooseRandomChildrenInGroup {
    SCHEMA_CLASS("client.dll", "C_OP_ChooseRandomChildrenInGroup");

};

} // namespace sdk

#endif // ISDK_C_OP_CHOOSERANDOMCHILDRENINGROUP_HPP

