// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: C_OP_RemapDistanceToLineSegmentToVector (runtime-resolved offsets)
// Module: client.dll
// Parent: C_OP_RemapDistanceToLineSegmentBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_C_OP_REMAPDISTANCETOLINESEGMENTTOVECTOR_HPP
#define ISDK_C_OP_REMAPDISTANCETOLINESEGMENTTOVECTOR_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct C_OP_RemapDistanceToLineSegmentToVector {
    SCHEMA_CLASS("client.dll", "C_OP_RemapDistanceToLineSegmentToVector");

};

} // namespace sdk

#endif // ISDK_C_OP_REMAPDISTANCETOLINESEGMENTTOVECTOR_HPP

