// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: C_OP_TimeVaryingForce (runtime-resolved offsets)
// Module: client.dll
// Parent: CParticleFunctionForce
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_C_OP_TIMEVARYINGFORCE_HPP
#define ISDK_C_OP_TIMEVARYINGFORCE_HPP

#include "../schema_runtime.hpp"
#include "CParticleFunctionForce.hpp"

namespace sdk {

struct C_OP_TimeVaryingForce : CParticleFunctionForce {
    SCHEMA_CLASS("client.dll", "C_OP_TimeVaryingForce");

};

} // namespace sdk

#endif // ISDK_C_OP_TIMEVARYINGFORCE_HPP

