// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: C_OP_MovementMoveAlongSkinnedCPSnapshot (runtime-resolved offsets)
// Module: client.dll
// Parent: CParticleFunctionOperator
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_C_OP_MOVEMENTMOVEALONGSKINNEDCPSNAPSHOT_HPP
#define ISDK_C_OP_MOVEMENTMOVEALONGSKINNEDCPSNAPSHOT_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct C_OP_MovementMoveAlongSkinnedCPSnapshot {
    SCHEMA_CLASS("client.dll", "C_OP_MovementMoveAlongSkinnedCPSnapshot");

};

} // namespace sdk

#endif // ISDK_C_OP_MOVEMENTMOVEALONGSKINNEDCPSNAPSHOT_HPP

