// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: C_OP_ConstrainLineLength (runtime-resolved offsets)
// Module: client.dll
// Parent: CParticleFunctionConstraint
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_C_OP_CONSTRAINLINELENGTH_HPP
#define ISDK_C_OP_CONSTRAINLINELENGTH_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct C_OP_ConstrainLineLength {
    SCHEMA_CLASS("client.dll", "C_OP_ConstrainLineLength");

};

} // namespace sdk

#endif // ISDK_C_OP_CONSTRAINLINELENGTH_HPP

