// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: C_OP_ContinuousEmitter (runtime-resolved offsets)
// Module: client.dll
// Parent: CParticleFunctionEmitter
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_C_OP_CONTINUOUSEMITTER_HPP
#define ISDK_C_OP_CONTINUOUSEMITTER_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct C_OP_ContinuousEmitter {
    SCHEMA_CLASS("client.dll", "C_OP_ContinuousEmitter");

};

} // namespace sdk

#endif // ISDK_C_OP_CONTINUOUSEMITTER_HPP

