// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: C_PlayerSprayDecal (runtime-resolved offsets)
// Module: client.dll
// Parent: C_ModelPointEntity
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_C_PLAYERSPRAYDECAL_HPP
#define ISDK_C_PLAYERSPRAYDECAL_HPP

#include "../schema_runtime.hpp"
#include "C_ModelPointEntity.hpp"

namespace sdk {

struct C_PlayerSprayDecal : C_ModelPointEntity {
    SCHEMA_CLASS("client.dll", "C_PlayerSprayDecal");


    // --- Virtual functions (vtable RVA: 0x1B37B60, 245 total) ---
};

} // namespace sdk

#endif // ISDK_C_PLAYERSPRAYDECAL_HPP

