// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: C_PointWorldText (runtime-resolved offsets)
// Module: client.dll
// Parent: C_ModelPointEntity
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_C_POINTWORLDTEXT_HPP
#define ISDK_C_POINTWORLDTEXT_HPP

#include "../schema_runtime.hpp"
#include "C_ModelPointEntity.hpp"

namespace sdk {

struct C_PointWorldText : C_ModelPointEntity {
    SCHEMA_CLASS("client.dll", "C_PointWorldText");


    // --- Virtual functions (vtable RVA: 0x1B0EB20, 245 total) ---
};

} // namespace sdk

#endif // ISDK_C_POINTWORLDTEXT_HPP

