// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: C_PropDoorRotating (runtime-resolved offsets)
// Module: client.dll
// Parent: C_BasePropDoor
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_C_PROPDOORROTATING_HPP
#define ISDK_C_PROPDOORROTATING_HPP

#include "../schema_runtime.hpp"
#include "C_BasePropDoor.hpp"

namespace sdk {

struct C_PropDoorRotating : C_BasePropDoor {
    SCHEMA_CLASS("client.dll", "C_PropDoorRotating");


    // --- Virtual functions (vtable RVA: 0x19CC078, 283 total) ---
    VFUNC_RAW(247);                                         // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(250);                                         // sig: 48 89 5C 24 08 48 89 74 24 10 57 48 83 E... reads: 0x330
    VFUNC_RAW(251);                                         // sig: 48 83 EC 28 E8 ? ? ? ? 33 C9 84 C0 0F 95...
    VFUNC_RAW(252);                                         // sig: 40 53 48 83 EC 60 0F 29 7C 24 40 48 8B D...
    VFUNC_RAW(253);                                         // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(254);                                         // sig: 48 89 5C 24 08 48 89 74 24 18 48 89 7C 2...
    VFUNC_RAW(255);                                         // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(257);                                         // sig: 80 B9 F1 12 00 00 00 0F 95 C0 FE C0 C3 C... reads: 0x12F1
    VFUNC_RAW(259);                                         // sig: 40 53 48 83 EC 30 0F 29 74 24 20 48 8B D... reads: 0x330
    VFUNC_RAW(261);                                         // sig: 48 89 5C 24 10 48 89 6C 24 18 48 89 74 2... reads: 0x330
    VFUNC_RAW(262);                                         // sig: 48 83 EC 28 8B 0D ? ? ? ? 65 48 8B 04 25...
    VFUNC_RAW(264);                                         // sig: 40 55 56 57 48 8D AC 24 80 D9 FF FF B8 8...
    VFUNC_RAW(265);                                         // sig: 48 89 5C 24 20 56 57 41 57 48 83 EC 20 4... reads: 0x330
    VFUNC_RAW(267);                                         // sig: 0F 10 81 40 0D 00 00 48 8B C2 0F 10 89 5... reads: 0xD40, 0xD50, 0xD60
    VFUNC_RAW(268);                                         // sig: 40 53 48 83 EC 20 41 0F B6 00 48 8B D9 3... reads: 0x10C0, 0x1118, 0x1119
    VFUNC_RAW(269);                                         // sig: 48 83 EC 28 48 8B 89 30 03 00 00 48 8B 0... reads: 0x330
    VFUNC_RAW(270);                                         // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(271);                                         // sig: 40 53 48 83 EC 20 48 8B 89 30 03 00 00 4... reads: 0x330
    VFUNC_RAW(272);                                         // sig: C6 05 F0 F6 A8 01 01 C3 CC CC CC CC CC C...
    VFUNC_RAW(273);                                         // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(275);                                         // sig: 48 89 5C 24 10 48 89 6C 24 18 56 57 41 5... reads: 0x1168
    VFUNC_RAW(276);                                         // sig: 0F B6 81 82 13 00 00 C3 CC CC CC CC CC C... reads: 0x1382
    VFUNC_RAW(278);                                         // sig: 33 D2 E9 ? ? ? ? CC CC CC CC CC CC CC CC...
    VFUNC_RAW(279);                                         // sig: 8B 81 5C 12 00 00 C3 CC CC CC CC CC CC C... reads: 0x125C
    VFUNC_RAW(280);                                         // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(281);                                         // sig: 48 89 5C 24 08 57 48 83 EC 30 49 8B D9 4...
    VFUNC_RAW(282);                                         // sig: 40 53 48 83 EC 30 48 8B 51 10 48 8B D9 0... reads: 0x10, 0x12D8, 0x12DC
};

} // namespace sdk

#endif // ISDK_C_PROPDOORROTATING_HPP

