// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: C_RetakeGameRules (runtime-resolved offsets)
// Module: client.dll
// Parent: CGameEventListener
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_C_RETAKEGAMERULES_HPP
#define ISDK_C_RETAKEGAMERULES_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct C_RetakeGameRules {
    SCHEMA_CLASS("client.dll", "C_RetakeGameRules");


    // --- Virtual functions (vtable RVA: 0x1A5D008, 7 total) ---
};

} // namespace sdk

#endif // ISDK_C_RETAKEGAMERULES_HPP

