// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: C_SoundAreaEntitySphere (runtime-resolved offsets)
// Module: client.dll
// Parent: C_SoundAreaEntityBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_C_SOUNDAREAENTITYSPHERE_HPP
#define ISDK_C_SOUNDAREAENTITYSPHERE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct C_SoundAreaEntitySphere {
    SCHEMA_CLASS("client.dll", "C_SoundAreaEntitySphere");


    // --- Virtual functions (vtable RVA: 0x1997310, 217 total) ---
    VFUNC_RAW(215);                                         // sig: 40 53 48 83 EC 40 48 83 3D BA 73 DD 01 0... reads: 0x604, 0x610, 0x628
    VFUNC_RAW(216);                                         // sig: 48 8B D1 48 8B 0D ? ? ? ? 48 85 C9 74 0B... reads: 0x604
};

} // namespace sdk

#endif // ISDK_C_SOUNDAREAENTITYSPHERE_HPP

