// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: C_Team (runtime-resolved offsets)
// Module: client.dll
// Parent: C_BaseEntity
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_C_TEAM_HPP
#define ISDK_C_TEAM_HPP

#include "../schema_runtime.hpp"
#include "C_BaseEntity.hpp"

namespace sdk {

struct C_Team : C_BaseEntity {
    SCHEMA_CLASS("client.dll", "C_Team");


    // --- Virtual functions (vtable RVA: 0x199B548, 215 total) ---
};

} // namespace sdk

#endif // ISDK_C_TEAM_HPP

