// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: C_TriggerLerpObject (runtime-resolved offsets)
// Module: client.dll
// Parent: C_BaseTrigger
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_C_TRIGGERLERPOBJECT_HPP
#define ISDK_C_TRIGGERLERPOBJECT_HPP

#include "../schema_runtime.hpp"
#include "C_BaseTrigger.hpp"

namespace sdk {

struct C_TriggerLerpObject : C_BaseTrigger {
    SCHEMA_CLASS("client.dll", "C_TriggerLerpObject");


    // --- Virtual functions (vtable RVA: 0x19CDBE0, 253 total) ---
    VFUNC_RAW(245);                                         // sig: 48 89 5C 24 10 56 48 83 EC 20 48 8B DA 4... reads: 0x3E8
    VFUNC_RAW(246);                                         // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(247);                                         // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(248);                                         // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(249);                                         // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(250);                                         // sig: 48 89 5C 24 08 57 48 83 EC 20 0F B6 FA 4... reads: 0xD28
    VFUNC_RAW(251);                                         // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
};

} // namespace sdk

#endif // ISDK_C_TRIGGERLERPOBJECT_HPP

