// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: C_WeaponP90 (runtime-resolved offsets)
// Module: client.dll
// Parent: C_CSWeaponBaseGun
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_C_WEAPONP90_HPP
#define ISDK_C_WEAPONP90_HPP

#include "../schema_runtime.hpp"
#include "C_CSWeaponBaseGun.hpp"

namespace sdk {

struct C_WeaponP90 : C_CSWeaponBaseGun {
    SCHEMA_CLASS("client.dll", "C_WeaponP90");


    // --- Virtual functions (vtable RVA: 0x1A90628, 421 total) ---
};

} // namespace sdk

#endif // ISDK_C_WEAPONP90_HPP

