// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CAddUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CBinaryUpdateNode
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CADDUPDATENODE_HPP
#define ISDK_CADDUPDATENODE_HPP

#include "../schema_runtime.hpp"
#include "CBinaryUpdateNode.hpp"

namespace sdk {

struct CAddUpdateNode : CBinaryUpdateNode {
    SCHEMA_CLASS("client.dll", "CAddUpdateNode");

};

} // namespace sdk

#endif // ISDK_CADDUPDATENODE_HPP

