// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CAI_ExpresserWithFollowup (runtime-resolved offsets)
// Module: client.dll
// Parent: CAI_Expresser
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CAI_EXPRESSERWITHFOLLOWUP_HPP
#define ISDK_CAI_EXPRESSERWITHFOLLOWUP_HPP

#include "../schema_runtime.hpp"
#include "CAI_Expresser.hpp"

namespace sdk {

struct CAI_ExpresserWithFollowup : CAI_Expresser {
    SCHEMA_CLASS("client.dll", "CAI_ExpresserWithFollowup");

};

} // namespace sdk

#endif // ISDK_CAI_EXPRESSERWITHFOLLOWUP_HPP

