// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CAI_Expresser (runtime-resolved offsets)
// Module: client.dll
// Parent: IResponseFilter
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CAI_EXPRESSER_HPP
#define ISDK_CAI_EXPRESSER_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CAI_Expresser {
    SCHEMA_CLASS("client.dll", "CAI_Expresser");

};

} // namespace sdk

#endif // ISDK_CAI_EXPRESSER_HPP

