// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CAimMatrixUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CUnaryUpdateNode
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CAIMMATRIXUPDATENODE_HPP
#define ISDK_CAIMMATRIXUPDATENODE_HPP

#include "../schema_runtime.hpp"
#include "CUnaryUpdateNode.hpp"

namespace sdk {

struct CAimMatrixUpdateNode : CUnaryUpdateNode {
    SCHEMA_CLASS("client.dll", "CAimMatrixUpdateNode");

};

} // namespace sdk

#endif // ISDK_CAIMMATRIXUPDATENODE_HPP

