// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CAimConstraint (runtime-resolved offsets)
// Module: client.dll
// Parent: CBaseConstraint
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CAIMCONSTRAINT_HPP
#define ISDK_CAIMCONSTRAINT_HPP

#include "../schema_runtime.hpp"
#include "CBaseConstraint.hpp"

namespace sdk {

struct CAimConstraint : CBaseConstraint {
    SCHEMA_CLASS("client.dll", "CAimConstraint");

};

} // namespace sdk

#endif // ISDK_CAIMCONSTRAINT_HPP

