// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CAimCameraUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CUnaryUpdateNode
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CAIMCAMERAUPDATENODE_HPP
#define ISDK_CAIMCAMERAUPDATENODE_HPP

#include "../schema_runtime.hpp"
#include "CUnaryUpdateNode.hpp"

namespace sdk {

struct CAimCameraUpdateNode : CUnaryUpdateNode {
    SCHEMA_CLASS("client.dll", "CAimCameraUpdateNode");

};

} // namespace sdk

#endif // ISDK_CAIMCAMERAUPDATENODE_HPP

