// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CAnimActionUpdater (runtime-resolved offsets)
// Module: client.dll
// Parent: ?$CMutableRefCounted@V?$CMutableRefCountBase@VCRefMT
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CANIMACTIONUPDATER_HPP
#define ISDK_CANIMACTIONUPDATER_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CAnimActionUpdater {
    SCHEMA_CLASS("client.dll", "CAnimActionUpdater");

};

} // namespace sdk

#endif // ISDK_CANIMACTIONUPDATER_HPP

