// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CAnimTagBase (runtime-resolved offsets)
// Module: client.dll
// Parent: IAnimTag
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CANIMTAGBASE_HPP
#define ISDK_CANIMTAGBASE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CAnimTagBase {
    SCHEMA_CLASS("client.dll", "CAnimTagBase");

};

} // namespace sdk

#endif // ISDK_CANIMTAGBASE_HPP

