// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CAnimationGraphVisualizerSphere (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimationGraphVisualizerPrimitiveBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CANIMATIONGRAPHVISUALIZERSPHERE_HPP
#define ISDK_CANIMATIONGRAPHVISUALIZERSPHERE_HPP

#include "../schema_runtime.hpp"
#include "CAnimationGraphVisualizerPrimitiveBase.hpp"

namespace sdk {

struct CAnimationGraphVisualizerSphere : CAnimationGraphVisualizerPrimitiveBase {
    SCHEMA_CLASS("client.dll", "CAnimationGraphVisualizerSphere");

};

} // namespace sdk

#endif // ISDK_CANIMATIONGRAPHVISUALIZERSPHERE_HPP

