// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CAnimStateMachineUpdater (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CANIMSTATEMACHINEUPDATER_HPP
#define ISDK_CANIMSTATEMACHINEUPDATER_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CAnimStateMachineUpdater {
    SCHEMA_CLASS("client.dll", "CAnimStateMachineUpdater");

};

} // namespace sdk

#endif // ISDK_CANIMSTATEMACHINEUPDATER_HPP

