// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CAnimReplayFrame (runtime-resolved offsets)
// Module: client.dll
// Parent: ?$CMutableRefCounted@V?$CMutableRefCountBase@VCRefMT
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CANIMREPLAYFRAME_HPP
#define ISDK_CANIMREPLAYFRAME_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CAnimReplayFrame {
    SCHEMA_CLASS("client.dll", "CAnimReplayFrame");

};

} // namespace sdk

#endif // ISDK_CANIMREPLAYFRAME_HPP

