// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CAnimGraphModelBinding (runtime-resolved offsets)
// Module: client.dll
// Parent: IAnimGraphModelBinding
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CANIMGRAPHMODELBINDING_HPP
#define ISDK_CANIMGRAPHMODELBINDING_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CAnimGraphModelBinding {
    SCHEMA_CLASS("client.dll", "CAnimGraphModelBinding");

};

} // namespace sdk

#endif // ISDK_CANIMGRAPHMODELBINDING_HPP

