// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CAnimComponentUpdater (runtime-resolved offsets)
// Module: client.dll
// Parent: ?$CMutableRefCounted@V?$CMutableRefCountBase@VCRefMT
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CANIMCOMPONENTUPDATER_HPP
#define ISDK_CANIMCOMPONENTUPDATER_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CAnimComponentUpdater {
    SCHEMA_CLASS("client.dll", "CAnimComponentUpdater");

};

} // namespace sdk

#endif // ISDK_CANIMCOMPONENTUPDATER_HPP

