// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CAnimTagManagerUpdater (runtime-resolved offsets)
// Module: client.dll
// Parent: ?$CMutableRefCounted@V?$CMutableRefCountBase@VCRefMT
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CANIMTAGMANAGERUPDATER_HPP
#define ISDK_CANIMTAGMANAGERUPDATER_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CAnimTagManagerUpdater {
    SCHEMA_CLASS("client.dll", "CAnimTagManagerUpdater");

};

} // namespace sdk

#endif // ISDK_CANIMTAGMANAGERUPDATER_HPP

