// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CAnimationGraphVisualizerAxis (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimationGraphVisualizerPrimitiveBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CANIMATIONGRAPHVISUALIZERAXIS_HPP
#define ISDK_CANIMATIONGRAPHVISUALIZERAXIS_HPP

#include "../schema_runtime.hpp"
#include "CAnimationGraphVisualizerPrimitiveBase.hpp"

namespace sdk {

struct CAnimationGraphVisualizerAxis : CAnimationGraphVisualizerPrimitiveBase {
    SCHEMA_CLASS("client.dll", "CAnimationGraphVisualizerAxis");

};

} // namespace sdk

#endif // ISDK_CANIMATIONGRAPHVISUALIZERAXIS_HPP

