// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CAnimGraphDebugReplay (runtime-resolved offsets)
// Module: client.dll
// Parent: IAnimGraphDebugReplay
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CANIMGRAPHDEBUGREPLAY_HPP
#define ISDK_CANIMGRAPHDEBUGREPLAY_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CAnimGraphDebugReplay {
    SCHEMA_CLASS("client.dll", "CAnimGraphDebugReplay");

};

} // namespace sdk

#endif // ISDK_CANIMGRAPHDEBUGREPLAY_HPP

