// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CAnimGraphNetworkSettings (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimGraphSettingsGroup
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CANIMGRAPHNETWORKSETTINGS_HPP
#define ISDK_CANIMGRAPHNETWORKSETTINGS_HPP

#include "../schema_runtime.hpp"
#include "CAnimGraphSettingsGroup.hpp"

namespace sdk {

struct CAnimGraphNetworkSettings : CAnimGraphSettingsGroup {
    SCHEMA_CLASS("client.dll", "CAnimGraphNetworkSettings");

};

} // namespace sdk

#endif // ISDK_CANIMGRAPHNETWORKSETTINGS_HPP

