// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CAnimGraphSettingsGroup (runtime-resolved offsets)
// Module: client.dll
// Parent: IAnimGraphSettingsGroup
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CANIMGRAPHSETTINGSGROUP_HPP
#define ISDK_CANIMGRAPHSETTINGSGROUP_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CAnimGraphSettingsGroup {
    SCHEMA_CLASS("client.dll", "CAnimGraphSettingsGroup");

};

} // namespace sdk

#endif // ISDK_CANIMGRAPHSETTINGSGROUP_HPP

