// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CAnimGraphSettingsManager (runtime-resolved offsets)
// Module: client.dll
// Parent: ?$CMutableRefCounted@V?$CMutableRefCountBase@VCRefMT
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CANIMGRAPHSETTINGSMANAGER_HPP
#define ISDK_CANIMGRAPHSETTINGSMANAGER_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CAnimGraphSettingsManager {
    SCHEMA_CLASS("client.dll", "CAnimGraphSettingsManager");

};

} // namespace sdk

#endif // ISDK_CANIMGRAPHSETTINGSMANAGER_HPP

