// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CAnimGraphControllerBase (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CANIMGRAPHCONTROLLERBASE_HPP
#define ISDK_CANIMGRAPHCONTROLLERBASE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CAnimGraphControllerBase {
    SCHEMA_CLASS("client.dll", "CAnimGraphControllerBase");


    // --- Virtual functions (vtable RVA: 0x1977FF8, 20 total) ---
    VFUNC_RAW(11);                                          // sig: 48 89 5C 24 08 57 48 83 EC 20 48 8B 01 4... reads: 0x18
    VFUNC_RAW(12);                                          // sig: 48 8B 01 48 FF 60 70 CC CC CC CC CC CC C...
    VFUNC_RAW(13);                                          // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(14);                                          // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(15);                                          // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(16);                                          // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(17);                                          // sig: 48 83 EC 28 E8 ? ? ? ? 48 85 C0 74 06 FF...
    VFUNC_RAW(18);                                          // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(19);                                          // sig: 48 89 5C 24 08 48 89 74 24 10 57 48 83 E... reads: 0x30, 0x38
};

} // namespace sdk

#endif // ISDK_CANIMGRAPHCONTROLLERBASE_HPP

