// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CAnimationGraphVisualizerPie (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimationGraphVisualizerPrimitiveBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CANIMATIONGRAPHVISUALIZERPIE_HPP
#define ISDK_CANIMATIONGRAPHVISUALIZERPIE_HPP

#include "../schema_runtime.hpp"
#include "CAnimationGraphVisualizerPrimitiveBase.hpp"

namespace sdk {

struct CAnimationGraphVisualizerPie : CAnimationGraphVisualizerPrimitiveBase {
    SCHEMA_CLASS("client.dll", "CAnimationGraphVisualizerPie");

};

} // namespace sdk

#endif // ISDK_CANIMATIONGRAPHVISUALIZERPIE_HPP

