// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CAnimScriptBase (runtime-resolved offsets)
// Module: client.dll
// Parent: IAnimCPPScript
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CANIMSCRIPTBASE_HPP
#define ISDK_CANIMSCRIPTBASE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CAnimScriptBase {
    SCHEMA_CLASS("client.dll", "CAnimScriptBase");

};

} // namespace sdk

#endif // ISDK_CANIMSCRIPTBASE_HPP

