// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CAnimScriptManager (runtime-resolved offsets)
// Module: client.dll
// Parent: ?$CMutableRefCounted@V?$CMutableRefCountBase@VCRefMT
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CANIMSCRIPTMANAGER_HPP
#define ISDK_CANIMSCRIPTMANAGER_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CAnimScriptManager {
    SCHEMA_CLASS("client.dll", "CAnimScriptManager");

};

} // namespace sdk

#endif // ISDK_CANIMSCRIPTMANAGER_HPP

