// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CAnimationGroup (runtime-resolved offsets)
// Module: client.dll
// Parent: ?$CRefCounted@V?$CRefCountServiceBase@VCRefMT
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CANIMATIONGROUP_HPP
#define ISDK_CANIMATIONGROUP_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CAnimationGroup {
    SCHEMA_CLASS("client.dll", "CAnimationGroup");

};

} // namespace sdk

#endif // ISDK_CANIMATIONGROUP_HPP

