// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CAnimationGraphInstance (runtime-resolved offsets)
// Module: client.dll
// Parent: IAnimationGraphInstance
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CANIMATIONGRAPHINSTANCE_HPP
#define ISDK_CANIMATIONGRAPHINSTANCE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CAnimationGraphInstance {
    SCHEMA_CLASS("client.dll", "CAnimationGraphInstance");

};

} // namespace sdk

#endif // ISDK_CANIMATIONGRAPHINSTANCE_HPP

