// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CAnimationGraphVisualizerLine (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimationGraphVisualizerPrimitiveBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CANIMATIONGRAPHVISUALIZERLINE_HPP
#define ISDK_CANIMATIONGRAPHVISUALIZERLINE_HPP

#include "../schema_runtime.hpp"
#include "CAnimationGraphVisualizerPrimitiveBase.hpp"

namespace sdk {

struct CAnimationGraphVisualizerLine : CAnimationGraphVisualizerPrimitiveBase {
    SCHEMA_CLASS("client.dll", "CAnimationGraphVisualizerLine");

};

} // namespace sdk

#endif // ISDK_CANIMATIONGRAPHVISUALIZERLINE_HPP

