// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CAnimationGraphVisualizerText (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimationGraphVisualizerPrimitiveBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CANIMATIONGRAPHVISUALIZERTEXT_HPP
#define ISDK_CANIMATIONGRAPHVISUALIZERTEXT_HPP

#include "../schema_runtime.hpp"
#include "CAnimationGraphVisualizerPrimitiveBase.hpp"

namespace sdk {

struct CAnimationGraphVisualizerText : CAnimationGraphVisualizerPrimitiveBase {
    SCHEMA_CLASS("client.dll", "CAnimationGraphVisualizerText");

};

} // namespace sdk

#endif // ISDK_CANIMATIONGRAPHVISUALIZERTEXT_HPP

