// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CAnimUpdateNodeBase (runtime-resolved offsets)
// Module: client.dll
// Parent: Object@Reflection
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CANIMUPDATENODEBASE_HPP
#define ISDK_CANIMUPDATENODEBASE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CAnimUpdateNodeBase {
    SCHEMA_CLASS("client.dll", "CAnimUpdateNodeBase");

};

} // namespace sdk

#endif // ISDK_CANIMUPDATENODEBASE_HPP

