// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CAnimSkeleton (runtime-resolved offsets)
// Module: client.dll
// Parent: ?$CMutableRefCounted@V?$CMutableRefCountBase@VCRefMT
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CANIMSKELETON_HPP
#define ISDK_CANIMSKELETON_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CAnimSkeleton {
    SCHEMA_CLASS("client.dll", "CAnimSkeleton");

};

} // namespace sdk

#endif // ISDK_CANIMSKELETON_HPP

