// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CAnimParameterBase (runtime-resolved offsets)
// Module: client.dll
// Parent: IAnimParameter
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CANIMPARAMETERBASE_HPP
#define ISDK_CANIMPARAMETERBASE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CAnimParameterBase {
    SCHEMA_CLASS("client.dll", "CAnimParameterBase");

};

} // namespace sdk

#endif // ISDK_CANIMPARAMETERBASE_HPP

