// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CAnimInputDamping (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CANIMINPUTDAMPING_HPP
#define ISDK_CANIMINPUTDAMPING_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CAnimInputDamping {
    SCHEMA_CLASS("client.dll", "CAnimInputDamping");

};

} // namespace sdk

#endif // ISDK_CANIMINPUTDAMPING_HPP

