// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CAnimationGraphVisualizerPrimitiveBase (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CANIMATIONGRAPHVISUALIZERPRIMITIVEBASE_HPP
#define ISDK_CANIMATIONGRAPHVISUALIZERPRIMITIVEBASE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CAnimationGraphVisualizerPrimitiveBase {
    SCHEMA_CLASS("client.dll", "CAnimationGraphVisualizerPrimitiveBase");

};

} // namespace sdk

#endif // ISDK_CANIMATIONGRAPHVISUALIZERPRIMITIVEBASE_HPP

