// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CAnimUpdateSharedData (runtime-resolved offsets)
// Module: client.dll
// Parent: ?$CMutableRefCounted@V?$CMutableRefCountBase@VCRefMT
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CANIMUPDATESHAREDDATA_HPP
#define ISDK_CANIMUPDATESHAREDDATA_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CAnimUpdateSharedData {
    SCHEMA_CLASS("client.dll", "CAnimUpdateSharedData");

};

} // namespace sdk

#endif // ISDK_CANIMUPDATESHAREDDATA_HPP

