// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CAttributeManager (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CATTRIBUTEMANAGER_HPP
#define ISDK_CATTRIBUTEMANAGER_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CAttributeManager {
    SCHEMA_CLASS("client.dll", "CAttributeManager");


    // --- Virtual functions (vtable RVA: 0x1BA5948, 12 total) ---
};

} // namespace sdk

#endif // ISDK_CATTRIBUTEMANAGER_HPP

