// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CAttributeList (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CATTRIBUTELIST_HPP
#define ISDK_CATTRIBUTELIST_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CAttributeList {
    SCHEMA_CLASS("client.dll", "CAttributeList");


    // --- Virtual functions (vtable RVA: 0x1BB4248, 5 total) ---
    VFUNC_RAW(0);                                           // sig: 40 53 48 83 EC 20 48 8B DA 48 8D 15 ? ? ...
    VFUNC_RAW(1);                                           // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(2);                                           // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(3);                                           // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(4);                                           // sig: 48 8B 05 ? ? ? ? C3 CC CC CC CC CC CC CC...
};

} // namespace sdk

#endif // ISDK_CATTRIBUTELIST_HPP

