// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CAudioAnimTag (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimTagBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CAUDIOANIMTAG_HPP
#define ISDK_CAUDIOANIMTAG_HPP

#include "../schema_runtime.hpp"
#include "CAnimTagBase.hpp"

namespace sdk {

struct CAudioAnimTag : CAnimTagBase {
    SCHEMA_CLASS("client.dll", "CAudioAnimTag");

};

} // namespace sdk

#endif // ISDK_CAUDIOANIMTAG_HPP

