// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CBaseAnimGraphDestructibleParts_GraphController (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimGraphControllerBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CBASEANIMGRAPHDESTRUCTIBLEPARTS_GRAPHCONTROLLER_HPP
#define ISDK_CBASEANIMGRAPHDESTRUCTIBLEPARTS_GRAPHCONTROLLER_HPP

#include "../schema_runtime.hpp"
#include "CAnimGraphControllerBase.hpp"

namespace sdk {

struct CBaseAnimGraphDestructibleParts_GraphController : CAnimGraphControllerBase {
    SCHEMA_CLASS("client.dll", "CBaseAnimGraphDestructibleParts_GraphController");


    // --- Virtual functions (vtable RVA: 0x19CEDE0, 20 total) ---
};

} // namespace sdk

#endif // ISDK_CBASEANIMGRAPHDESTRUCTIBLEPARTS_GRAPHCONTROLLER_HPP

