// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CBaseIssue (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CBASEISSUE_HPP
#define ISDK_CBASEISSUE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CBaseIssue {
    SCHEMA_CLASS("client.dll", "CBaseIssue");

};

} // namespace sdk

#endif // ISDK_CBASEISSUE_HPP

