// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CBaseAnimGraphVariationUserData (runtime-resolved offsets)
// Module: client.dll
// Parent: CNmGraphVariationUserData
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CBASEANIMGRAPHVARIATIONUSERDATA_HPP
#define ISDK_CBASEANIMGRAPHVARIATIONUSERDATA_HPP

#include "../schema_runtime.hpp"
#include "CNmGraphVariationUserData.hpp"

namespace sdk {

struct CBaseAnimGraphVariationUserData : CNmGraphVariationUserData {
    SCHEMA_CLASS("client.dll", "CBaseAnimGraphVariationUserData");


    // --- Virtual functions (vtable RVA: 0x1ABD740, 9 total) ---
};

} // namespace sdk

#endif // ISDK_CBASEANIMGRAPHVARIATIONUSERDATA_HPP

