// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CBasePlayerWeaponVData (runtime-resolved offsets)
// Module: client.dll
// Parent: CEntitySubclassVDataBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CBASEPLAYERWEAPONVDATA_HPP
#define ISDK_CBASEPLAYERWEAPONVDATA_HPP

#include "../schema_runtime.hpp"
#include "CEntitySubclassVDataBase.hpp"

namespace sdk {

struct CBasePlayerWeaponVData : CEntitySubclassVDataBase {
    SCHEMA_CLASS("client.dll", "CBasePlayerWeaponVData");


    // --- Virtual functions (vtable RVA: 0x1A6EFA8, 8 total) ---
};

} // namespace sdk

#endif // ISDK_CBASEPLAYERWEAPONVDATA_HPP

