// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CBaseTrailRenderer (runtime-resolved offsets)
// Module: client.dll
// Parent: CBaseRendererSource2
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CBASETRAILRENDERER_HPP
#define ISDK_CBASETRAILRENDERER_HPP

#include "../schema_runtime.hpp"
#include "CBaseRendererSource2.hpp"

namespace sdk {

struct CBaseTrailRenderer : CBaseRendererSource2 {
    SCHEMA_CLASS("client.dll", "CBaseTrailRenderer");

};

} // namespace sdk

#endif // ISDK_CBASETRAILRENDERER_HPP

