// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CBasePlayerVData (runtime-resolved offsets)
// Module: client.dll
// Parent: CEntitySubclassVDataBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CBASEPLAYERVDATA_HPP
#define ISDK_CBASEPLAYERVDATA_HPP

#include "../schema_runtime.hpp"
#include "CEntitySubclassVDataBase.hpp"

namespace sdk {

struct CBasePlayerVData : CEntitySubclassVDataBase {
    SCHEMA_CLASS("client.dll", "CBasePlayerVData");


    // --- Virtual functions (vtable RVA: 0x1ABABD8, 6 total) ---
};

} // namespace sdk

#endif // ISDK_CBASEPLAYERVDATA_HPP

