// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CBinaryUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimUpdateNodeBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CBINARYUPDATENODE_HPP
#define ISDK_CBINARYUPDATENODE_HPP

#include "../schema_runtime.hpp"
#include "CAnimUpdateNodeBase.hpp"

namespace sdk {

struct CBinaryUpdateNode : CAnimUpdateNodeBase {
    SCHEMA_CLASS("client.dll", "CBinaryUpdateNode");

};

} // namespace sdk

#endif // ISDK_CBINARYUPDATENODE_HPP

