// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CBindPoseUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CLeafUpdateNode
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CBINDPOSEUPDATENODE_HPP
#define ISDK_CBINDPOSEUPDATENODE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CBindPoseUpdateNode {
    SCHEMA_CLASS("client.dll", "CBindPoseUpdateNode");

};

} // namespace sdk

#endif // ISDK_CBINDPOSEUPDATENODE_HPP

