// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CBlendUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimUpdateNodeBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CBLENDUPDATENODE_HPP
#define ISDK_CBLENDUPDATENODE_HPP

#include "../schema_runtime.hpp"
#include "CAnimUpdateNodeBase.hpp"

namespace sdk {

struct CBlendUpdateNode : CAnimUpdateNodeBase {
    SCHEMA_CLASS("client.dll", "CBlendUpdateNode");

};

} // namespace sdk

#endif // ISDK_CBLENDUPDATENODE_HPP

