// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CBlend2DUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimUpdateNodeBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CBLEND2DUPDATENODE_HPP
#define ISDK_CBLEND2DUPDATENODE_HPP

#include "../schema_runtime.hpp"
#include "CAnimUpdateNodeBase.hpp"

namespace sdk {

struct CBlend2DUpdateNode : CAnimUpdateNodeBase {
    SCHEMA_CLASS("client.dll", "CBlend2DUpdateNode");

};

} // namespace sdk

#endif // ISDK_CBLEND2DUPDATENODE_HPP

