// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CBodyComponentSkeletonInstance (runtime-resolved offsets)
// Module: client.dll
// Parent: CBodyComponent
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CBODYCOMPONENTSKELETONINSTANCE_HPP
#define ISDK_CBODYCOMPONENTSKELETONINSTANCE_HPP

#include "../schema_runtime.hpp"
#include "CBodyComponent.hpp"

namespace sdk {

struct CBodyComponentSkeletonInstance : CBodyComponent {
    SCHEMA_CLASS("client.dll", "CBodyComponentSkeletonInstance");


    // --- Virtual functions (vtable RVA: 0x1977C00, 9 total) ---
};

} // namespace sdk

#endif // ISDK_CBODYCOMPONENTSKELETONINSTANCE_HPP

