// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CBodyGroupAnimTag (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimTagBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CBODYGROUPANIMTAG_HPP
#define ISDK_CBODYGROUPANIMTAG_HPP

#include "../schema_runtime.hpp"
#include "CAnimTagBase.hpp"

namespace sdk {

struct CBodyGroupAnimTag : CAnimTagBase {
    SCHEMA_CLASS("client.dll", "CBodyGroupAnimTag");

};

} // namespace sdk

#endif // ISDK_CBODYGROUPANIMTAG_HPP

