// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CBodyComponentPoint (runtime-resolved offsets)
// Module: client.dll
// Parent: CBodyComponent
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CBODYCOMPONENTPOINT_HPP
#define ISDK_CBODYCOMPONENTPOINT_HPP

#include "../schema_runtime.hpp"
#include "CBodyComponent.hpp"

namespace sdk {

struct CBodyComponentPoint : CBodyComponent {
    SCHEMA_CLASS("client.dll", "CBodyComponentPoint");


    // --- Virtual functions (vtable RVA: 0x1977A98, 9 total) ---
};

} // namespace sdk

#endif // ISDK_CBODYCOMPONENTPOINT_HPP

