// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CBodyComponentBaseAnimGraph (runtime-resolved offsets)
// Module: client.dll
// Parent: CBodyComponentSkeletonInstance
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CBODYCOMPONENTBASEANIMGRAPH_HPP
#define ISDK_CBODYCOMPONENTBASEANIMGRAPH_HPP

#include "../schema_runtime.hpp"
#include "CBodyComponentSkeletonInstance.hpp"

namespace sdk {

struct CBodyComponentBaseAnimGraph : CBodyComponentSkeletonInstance {
    SCHEMA_CLASS("client.dll", "CBodyComponentBaseAnimGraph");


    // --- Virtual functions (vtable RVA: 0x19C1FC8, 9 total) ---
};

} // namespace sdk

#endif // ISDK_CBODYCOMPONENTBASEANIMGRAPH_HPP

