// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CBoneConstraintBase (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CBONECONSTRAINTBASE_HPP
#define ISDK_CBONECONSTRAINTBASE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CBoneConstraintBase {
    SCHEMA_CLASS("client.dll", "CBoneConstraintBase");

};

} // namespace sdk

#endif // ISDK_CBONECONSTRAINTBASE_HPP

