// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CBoneConstraintDotToMorph (runtime-resolved offsets)
// Module: client.dll
// Parent: CBoneConstraintBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CBONECONSTRAINTDOTTOMORPH_HPP
#define ISDK_CBONECONSTRAINTDOTTOMORPH_HPP

#include "../schema_runtime.hpp"
#include "CBoneConstraintBase.hpp"

namespace sdk {

struct CBoneConstraintDotToMorph : CBoneConstraintBase {
    SCHEMA_CLASS("client.dll", "CBoneConstraintDotToMorph");

};

} // namespace sdk

#endif // ISDK_CBONECONSTRAINTDOTTOMORPH_HPP

