// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CBonePositionMetricEvaluator (runtime-resolved offsets)
// Module: client.dll
// Parent: CMotionMetricEvaluator
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CBONEPOSITIONMETRICEVALUATOR_HPP
#define ISDK_CBONEPOSITIONMETRICEVALUATOR_HPP

#include "../schema_runtime.hpp"
#include "CMotionMetricEvaluator.hpp"

namespace sdk {

struct CBonePositionMetricEvaluator : CMotionMetricEvaluator {
    SCHEMA_CLASS("client.dll", "CBonePositionMetricEvaluator");

};

} // namespace sdk

#endif // ISDK_CBONEPOSITIONMETRICEVALUATOR_HPP

