// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CBoneConstraintPoseSpaceMorph (runtime-resolved offsets)
// Module: client.dll
// Parent: CBoneConstraintBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CBONECONSTRAINTPOSESPACEMORPH_HPP
#define ISDK_CBONECONSTRAINTPOSESPACEMORPH_HPP

#include "../schema_runtime.hpp"
#include "CBoneConstraintBase.hpp"

namespace sdk {

struct CBoneConstraintPoseSpaceMorph : CBoneConstraintBase {
    SCHEMA_CLASS("client.dll", "CBoneConstraintPoseSpaceMorph");

};

} // namespace sdk

#endif // ISDK_CBONECONSTRAINTPOSESPACEMORPH_HPP

