// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CBoneVelocityMetricEvaluator (runtime-resolved offsets)
// Module: client.dll
// Parent: CMotionMetricEvaluator
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CBONEVELOCITYMETRICEVALUATOR_HPP
#define ISDK_CBONEVELOCITYMETRICEVALUATOR_HPP

#include "../schema_runtime.hpp"
#include "CMotionMetricEvaluator.hpp"

namespace sdk {

struct CBoneVelocityMetricEvaluator : CMotionMetricEvaluator {
    SCHEMA_CLASS("client.dll", "CBoneVelocityMetricEvaluator");

};

} // namespace sdk

#endif // ISDK_CBONEVELOCITYMETRICEVALUATOR_HPP

