// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CBoneConstraintRbf (runtime-resolved offsets)
// Module: client.dll
// Parent: CBoneConstraintBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CBONECONSTRAINTRBF_HPP
#define ISDK_CBONECONSTRAINTRBF_HPP

#include "../schema_runtime.hpp"
#include "CBoneConstraintBase.hpp"

namespace sdk {

struct CBoneConstraintRbf : CBoneConstraintBase {
    SCHEMA_CLASS("client.dll", "CBoneConstraintRbf");

};

} // namespace sdk

#endif // ISDK_CBONECONSTRAINTRBF_HPP

