// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CBoneMaskUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CBinaryUpdateNode
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CBONEMASKUPDATENODE_HPP
#define ISDK_CBONEMASKUPDATENODE_HPP

#include "../schema_runtime.hpp"
#include "CBinaryUpdateNode.hpp"

namespace sdk {

struct CBoneMaskUpdateNode : CBinaryUpdateNode {
    SCHEMA_CLASS("client.dll", "CBoneMaskUpdateNode");

};

} // namespace sdk

#endif // ISDK_CBONEMASKUPDATENODE_HPP

