// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CBoneConstraintPoseSpaceBone (runtime-resolved offsets)
// Module: client.dll
// Parent: CBaseConstraint
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CBONECONSTRAINTPOSESPACEBONE_HPP
#define ISDK_CBONECONSTRAINTPOSESPACEBONE_HPP

#include "../schema_runtime.hpp"
#include "CBaseConstraint.hpp"

namespace sdk {

struct CBoneConstraintPoseSpaceBone : CBaseConstraint {
    SCHEMA_CLASS("client.dll", "CBoneConstraintPoseSpaceBone");

};

} // namespace sdk

#endif // ISDK_CBONECONSTRAINTPOSESPACEBONE_HPP

