// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CBtNode (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CBTNODE_HPP
#define ISDK_CBTNODE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CBtNode {
    SCHEMA_CLASS("client.dll", "CBtNode");

};

} // namespace sdk

#endif // ISDK_CBTNODE_HPP

