// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CBtNodeComposite (runtime-resolved offsets)
// Module: client.dll
// Parent: CBtNode
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CBTNODECOMPOSITE_HPP
#define ISDK_CBTNODECOMPOSITE_HPP

#include "../schema_runtime.hpp"
#include "CBtNode.hpp"

namespace sdk {

struct CBtNodeComposite : CBtNode {
    SCHEMA_CLASS("client.dll", "CBtNodeComposite");

};

} // namespace sdk

#endif // ISDK_CBTNODECOMPOSITE_HPP

