// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CBuoyancyHelper (runtime-resolved offsets)
// Module: client.dll
// Parent: IMotionEvent
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CBUOYANCYHELPER_HPP
#define ISDK_CBUOYANCYHELPER_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CBuoyancyHelper {
    SCHEMA_CLASS("client.dll", "CBuoyancyHelper");


    // --- Virtual functions (vtable RVA: 0x1980F20, 12 total) ---
    VFUNC_RAW(0);                                           // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(1);                                           // sig: 48 89 6C 24 18 56 57 41 56 48 83 EC 40 4... reads: 0x90, 0x110, 0x114
    VFUNC_RAW(2);                                           // sig: 48 8B 01 48 FF 60 08 CC CC CC CC CC CC C...
    VFUNC_RAW(3);                                           // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(5);                                           // sig: 40 53 48 83 EC 20 48 8B DA 48 8D 15 ? ? ...
    VFUNC_RAW(6);                                           // sig: E9 ? ? ? ? CC CC CC CC CC CC CC CC CC CC...
    VFUNC_RAW(7);                                           // sig: 4C 8D 05 ? ? ? ? E9 ? ? ? ? CC CC CC CC ...
    VFUNC_RAW(9);                                           // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(10);                                          // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(11);                                          // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
};

} // namespace sdk

#endif // ISDK_CBUOYANCYHELPER_HPP

