// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CCachedPose (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CCACHEDPOSE_HPP
#define ISDK_CCACHEDPOSE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CCachedPose {
    SCHEMA_CLASS("client.dll", "CCachedPose");

};

} // namespace sdk

#endif // ISDK_CCACHEDPOSE_HPP

