// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CCashStack (runtime-resolved offsets)
// Module: client.dll
// Parent: C_BaseModelEntity
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CCASHSTACK_HPP
#define ISDK_CCASHSTACK_HPP

#include "../schema_runtime.hpp"
#include "C_BaseModelEntity.hpp"

namespace sdk {

struct CCashStack : C_BaseModelEntity {
    SCHEMA_CLASS("client.dll", "CCashStack");


    // --- Virtual functions (vtable RVA: 0x1A52190, 245 total) ---
};

} // namespace sdk

#endif // ISDK_CCASHSTACK_HPP

