// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CChoiceUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimUpdateNodeBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CCHOICEUPDATENODE_HPP
#define ISDK_CCHOICEUPDATENODE_HPP

#include "../schema_runtime.hpp"
#include "CAnimUpdateNodeBase.hpp"

namespace sdk {

struct CChoiceUpdateNode : CAnimUpdateNodeBase {
    SCHEMA_CLASS("client.dll", "CChoiceUpdateNode");

};

} // namespace sdk

#endif // ISDK_CCHOICEUPDATENODE_HPP

