// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CChoreoInfoTarget (runtime-resolved offsets)
// Module: client.dll
// Parent: C_PointEntity
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CCHOREOINFOTARGET_HPP
#define ISDK_CCHOREOINFOTARGET_HPP

#include "../schema_runtime.hpp"
#include "C_PointEntity.hpp"

namespace sdk {

struct CChoreoInfoTarget : C_PointEntity {
    SCHEMA_CLASS("client.dll", "CChoreoInfoTarget");


    // --- Virtual functions (vtable RVA: 0x198DD50, 215 total) ---
};

} // namespace sdk

#endif // ISDK_CCHOREOINFOTARGET_HPP

