// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CChoreoUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CUnaryUpdateNode
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CCHOREOUPDATENODE_HPP
#define ISDK_CCHOREOUPDATENODE_HPP

#include "../schema_runtime.hpp"
#include "CUnaryUpdateNode.hpp"

namespace sdk {

struct CChoreoUpdateNode : CUnaryUpdateNode {
    SCHEMA_CLASS("client.dll", "CChoreoUpdateNode");

};

} // namespace sdk

#endif // ISDK_CCHOREOUPDATENODE_HPP

