// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CChoreoComponent (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CCHOREOCOMPONENT_HPP
#define ISDK_CCHOREOCOMPONENT_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CChoreoComponent {
    SCHEMA_CLASS("client.dll", "CChoreoComponent");


    // --- Virtual functions (vtable RVA: 0x1978118, 31 total) ---
    VFUNC_RAW(10);                                          // sig: 48 8B C4 55 56 57 41 57 48 83 EC 48 45 3...
    VFUNC_RAW(12);                                          // sig: 48 89 5C 24 10 48 89 74 24 18 57 48 83 E... reads: 0x30
    VFUNC_RAW(13);                                          // sig: 40 55 56 41 54 41 55 41 57 48 8D 6C 24 C... reads: 0x30
    VFUNC_RAW(14);                                          // sig: 48 89 5C 24 10 48 89 74 24 18 57 48 83 E... reads: 0x30
    VFUNC_RAW(18);                                          // sig: 48 89 5C 24 08 48 89 6C 24 10 48 89 74 2... reads: 0x30
    VFUNC_RAW(19);                                          // sig: 48 89 5C 24 18 48 89 6C 24 20 57 48 83 E... reads: 0x30
    VFUNC_RAW(20);                                          // sig: 40 53 48 83 EC 20 48 8B DA 48 85 D2 74 3...
    VFUNC_RAW(21);                                          // sig: 48 89 5C 24 08 48 89 74 24 18 57 48 81 E...
    VFUNC_RAW(22);                                          // sig: 48 83 EC 28 48 85 D2 74 1D 4D 85 C0 74 1...
    VFUNC_RAW(24);                                          // sig: 48 83 EC 28 44 8B 42 6C 4C 8B D1 41 83 F...
    VFUNC_RAW(26);                                          // sig: 40 57 41 54 41 55 41 56 48 83 EC 58 44 8... reads: 0x30
    VFUNC_RAW(29);                                          // sig: 40 57 41 56 48 83 EC 38 8B 51 30 45 33 F... reads: 0x30
    VFUNC_RAW(30);                                          // sig: 48 8B 02 48 89 41 38 C3 CC CC CC CC CC C... reads: 0x38
};

} // namespace sdk

#endif // ISDK_CCHOREOCOMPONENT_HPP

