// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CChoreo_GraphController (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimGraphControllerBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CCHOREO_GRAPHCONTROLLER_HPP
#define ISDK_CCHOREO_GRAPHCONTROLLER_HPP

#include "../schema_runtime.hpp"
#include "CAnimGraphControllerBase.hpp"

namespace sdk {

struct CChoreo_GraphController : CAnimGraphControllerBase {
    SCHEMA_CLASS("client.dll", "CChoreo_GraphController");


    // --- Virtual functions (vtable RVA: 0x1978218, 20 total) ---
    VFUNC_RAW(19);                                          // sig: 48 89 5C 24 08 48 89 74 24 10 57 48 83 E... reads: 0x30, 0x38
};

} // namespace sdk

#endif // ISDK_CCHOREO_GRAPHCONTROLLER_HPP

