// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CClientAlphaProperty (runtime-resolved offsets)
// Module: client.dll
// Parent: IClientAlphaProperty
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CCLIENTALPHAPROPERTY_HPP
#define ISDK_CCLIENTALPHAPROPERTY_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CClientAlphaProperty {
    SCHEMA_CLASS("client.dll", "CClientAlphaProperty");


    // --- Virtual functions (vtable RVA: 0x1AFD770, 10 total) ---
    VFUNC_RAW(0);                                           // sig: 40 53 48 83 EC 20 48 8B DA E8 ? ? ? ? 48...
    VFUNC_RAW(1);                                           // sig: E9 ? ? ? ? CC CC CC CC CC CC CC CC CC CC...
    VFUNC_RAW(2);                                           // sig: 4C 8D 05 ? ? ? ? E9 ? ? ? ? CC CC CC CC ...
    VFUNC_RAW(4);                                           // sig: 88 51 17 C3 CC CC CC CC CC CC CC CC CC C... reads: 0x17
    VFUNC_RAW(5);                                           // sig: 40 53 57 48 83 EC 38 F3 0F 10 0D 2D C0 E...
    VFUNC_RAW(6);                                           // sig: 0F 2F D3 0F 28 E3 76 06 0F 28 E2 0F 28 D...
    VFUNC_RAW(7);                                           // sig: 44 0F B7 41 14 66 44 33 C2 BA FF 3F 00 0... reads: 0x14
    VFUNC_RAW(8);                                           // sig: 0F B7 41 14 44 0F B6 C2 BA FF BF 00 00 6... reads: 0x14
    VFUNC_RAW(9);                                           // sig: 0F B7 41 14 44 0F B6 C2 BA FF 7F 00 00 6... reads: 0x14
};

} // namespace sdk

#endif // ISDK_CCLIENTALPHAPROPERTY_HPP

