// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CCollisionProperty (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CCOLLISIONPROPERTY_HPP
#define ISDK_CCOLLISIONPROPERTY_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CCollisionProperty {
    SCHEMA_CLASS("client.dll", "CCollisionProperty");


    // --- Virtual functions (vtable RVA: 0x1B04320, 9 total) ---
    VFUNC_RAW(0);                                           // sig: 40 53 48 83 EC 20 48 8B DA E8 ? ? ? ? 48...
    VFUNC_RAW(2);                                           // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(3);                                           // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(4);                                           // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(5);                                           // sig: 48 8B 05 ? ? ? ? C3 CC CC CC CC CC CC CC...
    VFUNC_RAW(6);                                           // sig: E9 ? ? ? ? CC CC CC CC CC CC CC CC CC CC...
    VFUNC_RAW(7);                                           // sig: 4C 8D 05 ? ? ? ? E9 ? ? ? ? CC CC CC CC ...
};

} // namespace sdk

#endif // ISDK_CCOLLISIONPROPERTY_HPP

