// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CCommentarySystem (runtime-resolved offsets)
// Module: client.dll
// Parent: CAutoGameSystem
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CCOMMENTARYSYSTEM_HPP
#define ISDK_CCOMMENTARYSYSTEM_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CCommentarySystem {
    SCHEMA_CLASS("client.dll", "CCommentarySystem");

};

} // namespace sdk

#endif // ISDK_CCOMMENTARYSYSTEM_HPP

