// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CConstantForceController (runtime-resolved offsets)
// Module: client.dll
// Parent: IMotionEvent
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CCONSTANTFORCECONTROLLER_HPP
#define ISDK_CCONSTANTFORCECONTROLLER_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CConstantForceController {
    SCHEMA_CLASS("client.dll", "CConstantForceController");

};

} // namespace sdk

#endif // ISDK_CCONSTANTFORCECONTROLLER_HPP

