// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CCopyRecipientFilter (runtime-resolved offsets)
// Module: client.dll
// Parent: IRecipientFilter
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CCOPYRECIPIENTFILTER_HPP
#define ISDK_CCOPYRECIPIENTFILTER_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CCopyRecipientFilter {
    SCHEMA_CLASS("client.dll", "CCopyRecipientFilter");


    // --- Virtual functions (vtable RVA: 0x19A68F8, 11 total) ---
};

} // namespace sdk

#endif // ISDK_CCOPYRECIPIENTFILTER_HPP

