// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CCS2UIPawnGraphController (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimGraphControllerBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CCS2UIPAWNGRAPHCONTROLLER_HPP
#define ISDK_CCS2UIPAWNGRAPHCONTROLLER_HPP

#include "../schema_runtime.hpp"
#include "CAnimGraphControllerBase.hpp"

namespace sdk {

struct CCS2UIPawnGraphController : CAnimGraphControllerBase {
    SCHEMA_CLASS("client.dll", "CCS2UIPawnGraphController");


    // --- Virtual functions (vtable RVA: 0x1B2CD88, 20 total) ---
    VFUNC_RAW(8);                                           // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(9);                                           // sig: 40 53 48 83 EC 20 48 8B D9 48 8B 89 90 0... reads: 0x90, 0x98, 0xA8...
    VFUNC_RAW(10);                                          // sig: 48 89 5C 24 08 48 89 74 24 10 57 48 83 E...
    VFUNC_RAW(11);                                          // sig: 48 89 5C 24 18 55 48 8B EC 48 83 EC 40 4... reads: 0x8, 0x98
    VFUNC_RAW(12);                                          // sig: 33 C0 BA FF FF FF FF 48 89 81 90 00 00 0...
    VFUNC_RAW(13);                                          // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(14);                                          // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(15);                                          // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(16);                                          // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(18);                                          // sig: 48 83 EC 28 48 8B 05 ? ? ? ? 4C 8B C9 48... reads: 0x8
    VFUNC_RAW(19);                                          // sig: 40 57 48 83 EC 60 48 8B F9 48 8B 89 C0 0... reads: 0xC0, 0xC8
};

} // namespace sdk

#endif // ISDK_CCS2UIPAWNGRAPHCONTROLLER_HPP

