// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CCS2PawnGraphController (runtime-resolved offsets)
// Module: client.dll
// Parent: CCS2WeaponGraphController
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CCS2PAWNGRAPHCONTROLLER_HPP
#define ISDK_CCS2PAWNGRAPHCONTROLLER_HPP

#include "../schema_runtime.hpp"
#include "CCS2WeaponGraphController.hpp"

namespace sdk {

struct CCS2PawnGraphController : CCS2WeaponGraphController {
    SCHEMA_CLASS("client.dll", "CCS2PawnGraphController");


    // --- Virtual functions (vtable RVA: 0x1AB1040, 21 total) ---
};

} // namespace sdk

#endif // ISDK_CCS2PAWNGRAPHCONTROLLER_HPP

