// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CCS2WeaponGraphController (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimGraphControllerBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CCS2WEAPONGRAPHCONTROLLER_HPP
#define ISDK_CCS2WEAPONGRAPHCONTROLLER_HPP

#include "../schema_runtime.hpp"
#include "CAnimGraphControllerBase.hpp"

namespace sdk {

struct CCS2WeaponGraphController : CAnimGraphControllerBase {
    SCHEMA_CLASS("client.dll", "CCS2WeaponGraphController");


    // --- Virtual functions (vtable RVA: 0x1AB4600, 21 total) ---
};

} // namespace sdk

#endif // ISDK_CCS2WEAPONGRAPHCONTROLLER_HPP

