// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CCS_PortraitWorldCallbackHandler (runtime-resolved offsets)
// Module: client.dll
// Parent: C_BaseEntity
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CCS_PORTRAITWORLDCALLBACKHANDLER_HPP
#define ISDK_CCS_PORTRAITWORLDCALLBACKHANDLER_HPP

#include "../schema_runtime.hpp"
#include "C_BaseEntity.hpp"

namespace sdk {

struct CCS_PortraitWorldCallbackHandler : C_BaseEntity {
    SCHEMA_CLASS("client.dll", "CCS_PortraitWorldCallbackHandler");


    // --- Virtual functions (vtable RVA: 0x1B649E0, 215 total) ---
};

} // namespace sdk

#endif // ISDK_CCS_PORTRAITWORLDCALLBACKHANDLER_HPP

