// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CCSGameModeRules (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CCSGAMEMODERULES_HPP
#define ISDK_CCSGAMEMODERULES_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CCSGameModeRules {
    SCHEMA_CLASS("client.dll", "CCSGameModeRules");


    // --- Virtual functions (vtable RVA: 0x1A53168, 3 total) ---
};

} // namespace sdk

#endif // ISDK_CCSGAMEMODERULES_HPP

