// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CCSGO_EndOfMatchLineupEnd (runtime-resolved offsets)
// Module: client.dll
// Parent: C_CSGO_EndOfMatchLineupEndpoint
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CCSGO_ENDOFMATCHLINEUPEND_HPP
#define ISDK_CCSGO_ENDOFMATCHLINEUPEND_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CCSGO_EndOfMatchLineupEnd {
    SCHEMA_CLASS("client.dll", "CCSGO_EndOfMatchLineupEnd");


    // --- Virtual functions (vtable RVA: 0x1A67848, 215 total) ---
};

} // namespace sdk

#endif // ISDK_CCSGO_ENDOFMATCHLINEUPEND_HPP

