// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CCSGameModeRules_Noop (runtime-resolved offsets)
// Module: client.dll
// Parent: CCSGameModeRules
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CCSGAMEMODERULES_NOOP_HPP
#define ISDK_CCSGAMEMODERULES_NOOP_HPP

#include "../schema_runtime.hpp"
#include "CCSGameModeRules.hpp"

namespace sdk {

struct CCSGameModeRules_Noop : CCSGameModeRules {
    SCHEMA_CLASS("client.dll", "CCSGameModeRules_Noop");


    // --- Virtual functions (vtable RVA: 0x1A53188, 3 total) ---
};

} // namespace sdk

#endif // ISDK_CCSGAMEMODERULES_NOOP_HPP

