// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CCSObserver_UseServices (runtime-resolved offsets)
// Module: client.dll
// Parent: CPlayer_UseServices
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CCSOBSERVER_USESERVICES_HPP
#define ISDK_CCSOBSERVER_USESERVICES_HPP

#include "../schema_runtime.hpp"
#include "CPlayer_UseServices.hpp"

namespace sdk {

struct CCSObserver_UseServices : CPlayer_UseServices {
    SCHEMA_CLASS("client.dll", "CCSObserver_UseServices");


    // --- Virtual functions (vtable RVA: 0x1AA9B40, 32 total) ---
};

} // namespace sdk

#endif // ISDK_CCSOBSERVER_USESERVICES_HPP

