// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CCSObserver_CameraServices (runtime-resolved offsets)
// Module: client.dll
// Parent: CCSPlayerBase_CameraServices
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CCSOBSERVER_CAMERASERVICES_HPP
#define ISDK_CCSOBSERVER_CAMERASERVICES_HPP

#include "../schema_runtime.hpp"
#include "CCSPlayerBase_CameraServices.hpp"

namespace sdk {

struct CCSObserver_CameraServices : CCSPlayerBase_CameraServices {
    SCHEMA_CLASS("client.dll", "CCSObserver_CameraServices");


    // --- Virtual functions (vtable RVA: 0x1AA9388, 48 total) ---
};

} // namespace sdk

#endif // ISDK_CCSOBSERVER_CAMERASERVICES_HPP

