// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CCSPlayerAnimationState (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CCSPLAYERANIMATIONSTATE_HPP
#define ISDK_CCSPLAYERANIMATIONSTATE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CCSPlayerAnimationState {
    SCHEMA_CLASS("client.dll", "CCSPlayerAnimationState");


    // --- Virtual functions (vtable RVA: 0x1AB0DE8, 2 total) ---
};

} // namespace sdk

#endif // ISDK_CCSPLAYERANIMATIONSTATE_HPP

