// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CCSPlayerModernJump (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CCSPLAYERMODERNJUMP_HPP
#define ISDK_CCSPLAYERMODERNJUMP_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CCSPlayerModernJump {
    SCHEMA_CLASS("client.dll", "CCSPlayerModernJump");


    // --- Virtual functions (vtable RVA: 0x1AB0DC0, 4 total) ---
    VFUNC_RAW(0);                                           // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(1);                                           // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(2);                                           // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
};

} // namespace sdk

#endif // ISDK_CCSPLAYERMODERNJUMP_HPP

