// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CCSPlayerController_ActionTrackingServices (runtime-resolved offsets)
// Module: client.dll
// Parent: CPlayerControllerComponent
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CCSPLAYERCONTROLLER_ACTIONTRACKINGSERVICES_HPP
#define ISDK_CCSPLAYERCONTROLLER_ACTIONTRACKINGSERVICES_HPP

#include "../schema_runtime.hpp"
#include "CPlayerControllerComponent.hpp"

namespace sdk {

struct CCSPlayerController_ActionTrackingServices : CPlayerControllerComponent {
    SCHEMA_CLASS("client.dll", "CCSPlayerController_ActionTrackingServices");


    // --- Virtual functions (vtable RVA: 0x1AB5010, 15 total) ---
};

} // namespace sdk

#endif // ISDK_CCSPLAYERCONTROLLER_ACTIONTRACKINGSERVICES_HPP

