// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CCSPlayer_UseServices (runtime-resolved offsets)
// Module: client.dll
// Parent: CPlayer_UseServices
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CCSPLAYER_USESERVICES_HPP
#define ISDK_CCSPLAYER_USESERVICES_HPP

#include "../schema_runtime.hpp"
#include "CPlayer_UseServices.hpp"

namespace sdk {

struct CCSPlayer_UseServices : CPlayer_UseServices {
    SCHEMA_CLASS("client.dll", "CCSPlayer_UseServices");


    // --- Virtual functions (vtable RVA: 0x1AB1D70, 32 total) ---
};

} // namespace sdk

#endif // ISDK_CCSPLAYER_USESERVICES_HPP

