// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CCSPlayer_BulletServices (runtime-resolved offsets)
// Module: client.dll
// Parent: CPlayerPawnComponent
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CCSPLAYER_BULLETSERVICES_HPP
#define ISDK_CCSPLAYER_BULLETSERVICES_HPP

#include "../schema_runtime.hpp"
#include "CPlayerPawnComponent.hpp"

namespace sdk {

struct CCSPlayer_BulletServices : CPlayerPawnComponent {
    SCHEMA_CLASS("client.dll", "CCSPlayer_BulletServices");


    // --- Virtual functions (vtable RVA: 0x1AACD00, 30 total) ---
};

} // namespace sdk

#endif // ISDK_CCSPLAYER_BULLETSERVICES_HPP

