// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CCSPlayer_PingServices (runtime-resolved offsets)
// Module: client.dll
// Parent: CPlayerPawnComponent
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CCSPLAYER_PINGSERVICES_HPP
#define ISDK_CCSPLAYER_PINGSERVICES_HPP

#include "../schema_runtime.hpp"
#include "CPlayerPawnComponent.hpp"

namespace sdk {

struct CCSPlayer_PingServices : CPlayerPawnComponent {
    SCHEMA_CLASS("client.dll", "CCSPlayer_PingServices");


    // --- Virtual functions (vtable RVA: 0x1AB2AA8, 30 total) ---
    VFUNC_RAW(20);                                          // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(21);                                          // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(22);                                          // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(23);                                          // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(24);                                          // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(25);                                          // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(26);                                          // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(27);                                          // sig: 48 89 5C 24 08 48 89 74 24 10 57 48 83 E... reads: 0x30
    VFUNC_RAW(29);                                          // sig: 48 83 EC 28 48 8D 54 24 38 E8 ? ? ? ? 48...
};

} // namespace sdk

#endif // ISDK_CCSPLAYER_PINGSERVICES_HPP

