// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CCSPlayerLegacyJump (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CCSPLAYERLEGACYJUMP_HPP
#define ISDK_CCSPLAYERLEGACYJUMP_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CCSPlayerLegacyJump {
    SCHEMA_CLASS("client.dll", "CCSPlayerLegacyJump");


    // --- Virtual functions (vtable RVA: 0x1AB0D98, 4 total) ---
};

} // namespace sdk

#endif // ISDK_CCSPLAYERLEGACYJUMP_HPP

