// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CCSPlayerController_InGameMoneyServices (runtime-resolved offsets)
// Module: client.dll
// Parent: CPlayerControllerComponent
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CCSPLAYERCONTROLLER_INGAMEMONEYSERVICES_HPP
#define ISDK_CCSPLAYERCONTROLLER_INGAMEMONEYSERVICES_HPP

#include "../schema_runtime.hpp"
#include "CPlayerControllerComponent.hpp"

namespace sdk {

struct CCSPlayerController_InGameMoneyServices : CPlayerControllerComponent {
    SCHEMA_CLASS("client.dll", "CCSPlayerController_InGameMoneyServices");


    // --- Virtual functions (vtable RVA: 0x1AB51E8, 15 total) ---
};

} // namespace sdk

#endif // ISDK_CCSPLAYERCONTROLLER_INGAMEMONEYSERVICES_HPP

