// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CCSPlayerController_InventoryServices (runtime-resolved offsets)
// Module: client.dll
// Parent: CPlayerControllerComponent
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CCSPLAYERCONTROLLER_INVENTORYSERVICES_HPP
#define ISDK_CCSPLAYERCONTROLLER_INVENTORYSERVICES_HPP

#include "../schema_runtime.hpp"
#include "CPlayerControllerComponent.hpp"

namespace sdk {

struct CCSPlayerController_InventoryServices : CPlayerControllerComponent {
    SCHEMA_CLASS("client.dll", "CCSPlayerController_InventoryServices");


    // --- Virtual functions (vtable RVA: 0x1AB52A0, 15 total) ---
};

} // namespace sdk

#endif // ISDK_CCSPLAYERCONTROLLER_INVENTORYSERVICES_HPP

