// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CCSWeaponBaseVData (runtime-resolved offsets)
// Module: client.dll
// Parent: CBasePlayerWeaponVData
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CCSWEAPONBASEVDATA_HPP
#define ISDK_CCSWEAPONBASEVDATA_HPP

#include "../schema_runtime.hpp"
#include "CBasePlayerWeaponVData.hpp"

namespace sdk {

struct CCSWeaponBaseVData : CBasePlayerWeaponVData {
    SCHEMA_CLASS("client.dll", "CCSWeaponBaseVData");


    // --- Virtual functions (vtable RVA: 0x1A79FA0, 8 total) ---
    VFUNC_RAW(0);                                           // sig: 48 89 5C 24 08 57 48 83 EC 20 48 8B D9 8... reads: 0x620, 0x7F0, 0x880
    VFUNC_RAW(1);                                           // sig: 40 53 48 83 EC 20 48 8B DA 48 8D 15 ? ? ...
    VFUNC_RAW(2);                                           // sig: E9 ? ? ? ? CC CC CC CC CC CC CC CC CC CC...
    VFUNC_RAW(3);                                           // sig: 4C 8D 05 ? ? ? ? E9 ? ? ? ? CC CC CC CC ...
    VFUNC_RAW(5);                                           // sig: 48 89 5C 24 08 48 89 74 24 10 57 48 83 E... reads: 0x52C
    VFUNC_RAW(6);                                           // sig: 8B 81 00 07 00 00 C3 CC CC CC CC CC CC C... reads: 0x700
    VFUNC_RAW(7);                                           // sig: 8B 81 04 07 00 00 C3 CC CC CC CC CC CC C... reads: 0x704
};

} // namespace sdk

#endif // ISDK_CCSWEAPONBASEVDATA_HPP

