// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CCurrentRotationVelocityMetricEvaluator (runtime-resolved offsets)
// Module: client.dll
// Parent: CMotionMetricEvaluator
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CCURRENTROTATIONVELOCITYMETRICEVALUATOR_HPP
#define ISDK_CCURRENTROTATIONVELOCITYMETRICEVALUATOR_HPP

#include "../schema_runtime.hpp"
#include "CMotionMetricEvaluator.hpp"

namespace sdk {

struct CCurrentRotationVelocityMetricEvaluator : CMotionMetricEvaluator {
    SCHEMA_CLASS("client.dll", "CCurrentRotationVelocityMetricEvaluator");

};

} // namespace sdk

#endif // ISDK_CCURRENTROTATIONVELOCITYMETRICEVALUATOR_HPP

