// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CCurrentVelocityMetricEvaluator (runtime-resolved offsets)
// Module: client.dll
// Parent: CMotionMetricEvaluator
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CCURRENTVELOCITYMETRICEVALUATOR_HPP
#define ISDK_CCURRENTVELOCITYMETRICEVALUATOR_HPP

#include "../schema_runtime.hpp"
#include "CMotionMetricEvaluator.hpp"

namespace sdk {

struct CCurrentVelocityMetricEvaluator : CMotionMetricEvaluator {
    SCHEMA_CLASS("client.dll", "CCurrentVelocityMetricEvaluator");

};

} // namespace sdk

#endif // ISDK_CCURRENTVELOCITYMETRICEVALUATOR_HPP

