// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CCycleControlUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CUnaryUpdateNode
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CCYCLECONTROLUPDATENODE_HPP
#define ISDK_CCYCLECONTROLUPDATENODE_HPP

#include "../schema_runtime.hpp"
#include "CUnaryUpdateNode.hpp"

namespace sdk {

struct CCycleControlUpdateNode : CUnaryUpdateNode {
    SCHEMA_CLASS("client.dll", "CCycleControlUpdateNode");

};

} // namespace sdk

#endif // ISDK_CCYCLECONTROLUPDATENODE_HPP

