// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CDamageRecord (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CDAMAGERECORD_HPP
#define ISDK_CDAMAGERECORD_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CDamageRecord {
    SCHEMA_CLASS("client.dll", "CDamageRecord");


    // --- Virtual functions (vtable RVA: 0x1AAD4E0, 6 total) ---
};

} // namespace sdk

#endif // ISDK_CDAMAGERECORD_HPP

