// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CDampedPathAnimMotorUpdater (runtime-resolved offsets)
// Module: client.dll
// Parent: CPathAnimMotorUpdaterBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CDAMPEDPATHANIMMOTORUPDATER_HPP
#define ISDK_CDAMPEDPATHANIMMOTORUPDATER_HPP

#include "../schema_runtime.hpp"
#include "CPathAnimMotorUpdaterBase.hpp"

namespace sdk {

struct CDampedPathAnimMotorUpdater : CPathAnimMotorUpdaterBase {
    SCHEMA_CLASS("client.dll", "CDampedPathAnimMotorUpdater");

};

} // namespace sdk

#endif // ISDK_CDAMPEDPATHANIMMOTORUPDATER_HPP

