// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CDemoSettingsComponentUpdater (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimComponentUpdater
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CDEMOSETTINGSCOMPONENTUPDATER_HPP
#define ISDK_CDEMOSETTINGSCOMPONENTUPDATER_HPP

#include "../schema_runtime.hpp"
#include "CAnimComponentUpdater.hpp"

namespace sdk {

struct CDemoSettingsComponentUpdater : CAnimComponentUpdater {
    SCHEMA_CLASS("client.dll", "CDemoSettingsComponentUpdater");

};

} // namespace sdk

#endif // ISDK_CDEMOSETTINGSCOMPONENTUPDATER_HPP

