// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CDirectionalBlendUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CLeafUpdateNode
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CDIRECTIONALBLENDUPDATENODE_HPP
#define ISDK_CDIRECTIONALBLENDUPDATENODE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CDirectionalBlendUpdateNode {
    SCHEMA_CLASS("client.dll", "CDirectionalBlendUpdateNode");

};

} // namespace sdk

#endif // ISDK_CDIRECTIONALBLENDUPDATENODE_HPP

