// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CDirectPlaybackUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CUnaryUpdateNode
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CDIRECTPLAYBACKUPDATENODE_HPP
#define ISDK_CDIRECTPLAYBACKUPDATENODE_HPP

#include "../schema_runtime.hpp"
#include "CUnaryUpdateNode.hpp"

namespace sdk {

struct CDirectPlaybackUpdateNode : CUnaryUpdateNode {
    SCHEMA_CLASS("client.dll", "CDirectPlaybackUpdateNode");

};

} // namespace sdk

#endif // ISDK_CDIRECTPLAYBACKUPDATENODE_HPP

