// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CDistanceRemainingMetricEvaluator (runtime-resolved offsets)
// Module: client.dll
// Parent: CMotionMetricEvaluator
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CDISTANCEREMAININGMETRICEVALUATOR_HPP
#define ISDK_CDISTANCEREMAININGMETRICEVALUATOR_HPP

#include "../schema_runtime.hpp"
#include "CMotionMetricEvaluator.hpp"

namespace sdk {

struct CDistanceRemainingMetricEvaluator : CMotionMetricEvaluator {
    SCHEMA_CLASS("client.dll", "CDistanceRemainingMetricEvaluator");

};

} // namespace sdk

#endif // ISDK_CDISTANCEREMAININGMETRICEVALUATOR_HPP

