// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CEconItemAttribute (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CECONITEMATTRIBUTE_HPP
#define ISDK_CECONITEMATTRIBUTE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CEconItemAttribute {
    SCHEMA_CLASS("client.dll", "CEconItemAttribute");


    // --- Virtual functions (vtable RVA: 0x1BB4278, 6 total) ---
};

} // namespace sdk

#endif // ISDK_CECONITEMATTRIBUTE_HPP

