// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CEditableMotionGraph (runtime-resolved offsets)
// Module: client.dll
// Parent: CMotionGraph
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CEDITABLEMOTIONGRAPH_HPP
#define ISDK_CEDITABLEMOTIONGRAPH_HPP

#include "../schema_runtime.hpp"
#include "CMotionGraph.hpp"

namespace sdk {

struct CEditableMotionGraph : CMotionGraph {
    SCHEMA_CLASS("client.dll", "CEditableMotionGraph");

};

} // namespace sdk

#endif // ISDK_CEDITABLEMOTIONGRAPH_HPP

