// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CEffectData (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CEFFECTDATA_HPP
#define ISDK_CEFFECTDATA_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CEffectData {
    SCHEMA_CLASS("client.dll", "CEffectData");


    // --- Virtual functions (vtable RVA: 0x197E930, 4 total) ---
};

} // namespace sdk

#endif // ISDK_CEFFECTDATA_HPP

