// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CEmitTagActionUpdater (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimActionUpdater
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CEMITTAGACTIONUPDATER_HPP
#define ISDK_CEMITTAGACTIONUPDATER_HPP

#include "../schema_runtime.hpp"
#include "CAnimActionUpdater.hpp"

namespace sdk {

struct CEmitTagActionUpdater : CAnimActionUpdater {
    SCHEMA_CLASS("client.dll", "CEmitTagActionUpdater");

};

} // namespace sdk

#endif // ISDK_CEMITTAGACTIONUPDATER_HPP

