// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CEntitySubclassVDataBase (runtime-resolved offsets)
// Module: client.dll
// Parent: CMemZeroOnNew
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CENTITYSUBCLASSVDATABASE_HPP
#define ISDK_CENTITYSUBCLASSVDATABASE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CEntitySubclassVDataBase {
    SCHEMA_CLASS("client.dll", "CEntitySubclassVDataBase");


    // --- Virtual functions (vtable RVA: 0x199EA28, 6 total) ---
};

} // namespace sdk

#endif // ISDK_CENTITYSUBCLASSVDATABASE_HPP

