// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CEnvSoundscapeTriggerable (runtime-resolved offsets)
// Module: client.dll
// Parent: CEnvSoundscape
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CENVSOUNDSCAPETRIGGERABLE_HPP
#define ISDK_CENVSOUNDSCAPETRIGGERABLE_HPP

#include "../schema_runtime.hpp"
#include "CEnvSoundscape.hpp"

namespace sdk {

struct CEnvSoundscapeTriggerable : CEnvSoundscape {
    SCHEMA_CLASS("client.dll", "CEnvSoundscapeTriggerable");


    // --- Virtual functions (vtable RVA: 0x19B53C0, 215 total) ---
};

} // namespace sdk

#endif // ISDK_CENVSOUNDSCAPETRIGGERABLE_HPP

