// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CExampleSchemaVData_PolymorphicDerivedB (runtime-resolved offsets)
// Module: client.dll
// Parent: CExampleSchemaVData_PolymorphicBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CEXAMPLESCHEMAVDATA_POLYMORPHICDERIVEDB_HPP
#define ISDK_CEXAMPLESCHEMAVDATA_POLYMORPHICDERIVEDB_HPP

#include "../schema_runtime.hpp"
#include "CExampleSchemaVData_PolymorphicBase.hpp"

namespace sdk {

struct CExampleSchemaVData_PolymorphicDerivedB : CExampleSchemaVData_PolymorphicBase {
    SCHEMA_CLASS("client.dll", "CExampleSchemaVData_PolymorphicDerivedB");

};

} // namespace sdk

#endif // ISDK_CEXAMPLESCHEMAVDATA_POLYMORPHICDERIVEDB_HPP

