// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CExampleSchemaVData_PolymorphicBase (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CEXAMPLESCHEMAVDATA_POLYMORPHICBASE_HPP
#define ISDK_CEXAMPLESCHEMAVDATA_POLYMORPHICBASE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CExampleSchemaVData_PolymorphicBase {
    SCHEMA_CLASS("client.dll", "CExampleSchemaVData_PolymorphicBase");

};

} // namespace sdk

#endif // ISDK_CEXAMPLESCHEMAVDATA_POLYMORPHICBASE_HPP

