// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CExpressionActionUpdater (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimActionUpdater
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CEXPRESSIONACTIONUPDATER_HPP
#define ISDK_CEXPRESSIONACTIONUPDATER_HPP

#include "../schema_runtime.hpp"
#include "CAnimActionUpdater.hpp"

namespace sdk {

struct CExpressionActionUpdater : CAnimActionUpdater {
    SCHEMA_CLASS("client.dll", "CExpressionActionUpdater");

};

} // namespace sdk

#endif // ISDK_CEXPRESSIONACTIONUPDATER_HPP

