// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CFollowTargetUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CUnaryUpdateNode
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CFOLLOWTARGETUPDATENODE_HPP
#define ISDK_CFOLLOWTARGETUPDATENODE_HPP

#include "../schema_runtime.hpp"
#include "CUnaryUpdateNode.hpp"

namespace sdk {

struct CFollowTargetUpdateNode : CUnaryUpdateNode {
    SCHEMA_CLASS("client.dll", "CFollowTargetUpdateNode");

};

} // namespace sdk

#endif // ISDK_CFOLLOWTARGETUPDATENODE_HPP

