// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CFootFallAnimTag (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimTagBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CFOOTFALLANIMTAG_HPP
#define ISDK_CFOOTFALLANIMTAG_HPP

#include "../schema_runtime.hpp"
#include "CAnimTagBase.hpp"

namespace sdk {

struct CFootFallAnimTag : CAnimTagBase {
    SCHEMA_CLASS("client.dll", "CFootFallAnimTag");

};

} // namespace sdk

#endif // ISDK_CFOOTFALLANIMTAG_HPP

