// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CFootCycleMetricEvaluator (runtime-resolved offsets)
// Module: client.dll
// Parent: CMotionMetricEvaluator
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CFOOTCYCLEMETRICEVALUATOR_HPP
#define ISDK_CFOOTCYCLEMETRICEVALUATOR_HPP

#include "../schema_runtime.hpp"
#include "CMotionMetricEvaluator.hpp"

namespace sdk {

struct CFootCycleMetricEvaluator : CMotionMetricEvaluator {
    SCHEMA_CLASS("client.dll", "CFootCycleMetricEvaluator");

};

} // namespace sdk

#endif // ISDK_CFOOTCYCLEMETRICEVALUATOR_HPP

