// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CFootPinningUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CUnaryUpdateNode
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CFOOTPINNINGUPDATENODE_HPP
#define ISDK_CFOOTPINNINGUPDATENODE_HPP

#include "../schema_runtime.hpp"
#include "CUnaryUpdateNode.hpp"

namespace sdk {

struct CFootPinningUpdateNode : CUnaryUpdateNode {
    SCHEMA_CLASS("client.dll", "CFootPinningUpdateNode");

};

} // namespace sdk

#endif // ISDK_CFOOTPINNINGUPDATENODE_HPP

