// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CFootPositionMetricEvaluator (runtime-resolved offsets)
// Module: client.dll
// Parent: CMotionMetricEvaluator
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CFOOTPOSITIONMETRICEVALUATOR_HPP
#define ISDK_CFOOTPOSITIONMETRICEVALUATOR_HPP

#include "../schema_runtime.hpp"
#include "CMotionMetricEvaluator.hpp"

namespace sdk {

struct CFootPositionMetricEvaluator : CMotionMetricEvaluator {
    SCHEMA_CLASS("client.dll", "CFootPositionMetricEvaluator");

};

} // namespace sdk

#endif // ISDK_CFOOTPOSITIONMETRICEVALUATOR_HPP

