// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CFootAdjustmentUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CUnaryUpdateNode
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CFOOTADJUSTMENTUPDATENODE_HPP
#define ISDK_CFOOTADJUSTMENTUPDATENODE_HPP

#include "../schema_runtime.hpp"
#include "CUnaryUpdateNode.hpp"

namespace sdk {

struct CFootAdjustmentUpdateNode : CUnaryUpdateNode {
    SCHEMA_CLASS("client.dll", "CFootAdjustmentUpdateNode");

};

} // namespace sdk

#endif // ISDK_CFOOTADJUSTMENTUPDATENODE_HPP

