// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CFootLockUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CUnaryUpdateNode
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CFOOTLOCKUPDATENODE_HPP
#define ISDK_CFOOTLOCKUPDATENODE_HPP

#include "../schema_runtime.hpp"
#include "CUnaryUpdateNode.hpp"

namespace sdk {

struct CFootLockUpdateNode : CUnaryUpdateNode {
    SCHEMA_CLASS("client.dll", "CFootLockUpdateNode");

};

} // namespace sdk

#endif // ISDK_CFOOTLOCKUPDATENODE_HPP

