// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CFootstepLandedAnimTag (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimTagBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CFOOTSTEPLANDEDANIMTAG_HPP
#define ISDK_CFOOTSTEPLANDEDANIMTAG_HPP

#include "../schema_runtime.hpp"
#include "CAnimTagBase.hpp"

namespace sdk {

struct CFootstepLandedAnimTag : CAnimTagBase {
    SCHEMA_CLASS("client.dll", "CFootstepLandedAnimTag");

};

} // namespace sdk

#endif // ISDK_CFOOTSTEPLANDEDANIMTAG_HPP

