// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CFootTrajectory (runtime-resolved offsets)
// Module: client.dll
// Parent: IFootTrajectory
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CFOOTTRAJECTORY_HPP
#define ISDK_CFOOTTRAJECTORY_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CFootTrajectory {
    SCHEMA_CLASS("client.dll", "CFootTrajectory");

};

} // namespace sdk

#endif // ISDK_CFOOTTRAJECTORY_HPP

