// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CFutureFacingMetricEvaluator (runtime-resolved offsets)
// Module: client.dll
// Parent: CMotionMetricEvaluator
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CFUTUREFACINGMETRICEVALUATOR_HPP
#define ISDK_CFUTUREFACINGMETRICEVALUATOR_HPP

#include "../schema_runtime.hpp"
#include "CMotionMetricEvaluator.hpp"

namespace sdk {

struct CFutureFacingMetricEvaluator : CMotionMetricEvaluator {
    SCHEMA_CLASS("client.dll", "CFutureFacingMetricEvaluator");

};

} // namespace sdk

#endif // ISDK_CFUTUREFACINGMETRICEVALUATOR_HPP

