// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CGameChoreoServices (runtime-resolved offsets)
// Module: client.dll
// Parent: IChoreoServices
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CGAMECHOREOSERVICES_HPP
#define ISDK_CGAMECHOREOSERVICES_HPP

#include "../schema_runtime.hpp"
#include "IChoreoServices.hpp"

namespace sdk {

struct CGameChoreoServices : IChoreoServices {
    SCHEMA_CLASS("client.dll", "CGameChoreoServices");

};

} // namespace sdk

#endif // ISDK_CGAMECHOREOSERVICES_HPP

