// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CGameSceneNodeHandle (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CGAMESCENENODEHANDLE_HPP
#define ISDK_CGAMESCENENODEHANDLE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CGameSceneNodeHandle {
    SCHEMA_CLASS("client.dll", "CGameSceneNodeHandle");


    // --- Virtual functions (vtable RVA: 0x19AAF80, 8 total) ---
};

} // namespace sdk

#endif // ISDK_CGAMESCENENODEHANDLE_HPP

