// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CGameSceneNode (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CGAMESCENENODE_HPP
#define ISDK_CGAMESCENENODE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CGameSceneNode {
    SCHEMA_CLASS("client.dll", "CGameSceneNode");


    // --- Virtual functions (vtable RVA: 0x1ACD810, 32 total) ---
};

} // namespace sdk

#endif // ISDK_CGAMESCENENODE_HPP

