// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CGlowProperty (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CGLOWPROPERTY_HPP
#define ISDK_CGLOWPROPERTY_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CGlowProperty {
    SCHEMA_CLASS("client.dll", "CGlowProperty");


    // --- Virtual functions (vtable RVA: 0x1B09C40, 8 total) ---
};

} // namespace sdk

#endif // ISDK_CGLOWPROPERTY_HPP

