// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CGlobalLightBase (runtime-resolved offsets)
// Module: client.dll
// Parent: IToolObject
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CGLOBALLIGHTBASE_HPP
#define ISDK_CGLOBALLIGHTBASE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CGlobalLightBase {
    SCHEMA_CLASS("client.dll", "CGlobalLightBase");


    // --- Virtual functions (vtable RVA: 0x1AE6918, 11 total) ---
    VFUNC_RAW(0);                                           // sig: 48 89 5C 24 08 57 48 83 EC 20 8B DA 48 8...
    VFUNC_RAW(1);                                           // sig: 48 89 5C 24 08 48 89 74 24 10 55 57 41 5...
    VFUNC_RAW(2);                                           // sig: 48 89 5C 24 08 48 89 74 24 10 48 89 7C 2...
    VFUNC_RAW(8);                                           // sig: 40 53 48 83 EC 20 48 8B DA 48 8D 15 ? ? ...
    VFUNC_RAW(9);                                           // sig: 48 8B 05 ? ? ? ? C3 CC CC CC CC CC CC CC...
    VFUNC_RAW(10);                                          // sig: C7 02 00 00 00 00 48 8B C2 C3 CC CC CC C...
};

} // namespace sdk

#endif // ISDK_CGLOBALLIGHTBASE_HPP

