// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CHandshakeAnimTagBase (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimTagBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CHANDSHAKEANIMTAGBASE_HPP
#define ISDK_CHANDSHAKEANIMTAGBASE_HPP

#include "../schema_runtime.hpp"
#include "CAnimTagBase.hpp"

namespace sdk {

struct CHandshakeAnimTagBase : CAnimTagBase {
    SCHEMA_CLASS("client.dll", "CHandshakeAnimTagBase");

};

} // namespace sdk

#endif // ISDK_CHANDSHAKEANIMTAGBASE_HPP

