// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CHitboxComponent (runtime-resolved offsets)
// Module: client.dll
// Parent: CEntityComponent
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CHITBOXCOMPONENT_HPP
#define ISDK_CHITBOXCOMPONENT_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CHitboxComponent {
    SCHEMA_CLASS("client.dll", "CHitboxComponent");


    // --- Virtual functions (vtable RVA: 0x19780C0, 10 total) ---
};

} // namespace sdk

#endif // ISDK_CHITBOXCOMPONENT_HPP

