// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CHitReactUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CUnaryUpdateNode
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CHITREACTUPDATENODE_HPP
#define ISDK_CHITREACTUPDATENODE_HPP

#include "../schema_runtime.hpp"
#include "CUnaryUpdateNode.hpp"

namespace sdk {

struct CHitReactUpdateNode : CUnaryUpdateNode {
    SCHEMA_CLASS("client.dll", "CHitReactUpdateNode");

};

} // namespace sdk

#endif // ISDK_CHITREACTUPDATENODE_HPP

