// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CHostageRescueZone (runtime-resolved offsets)
// Module: client.dll
// Parent: CHostageRescueZoneShim
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CHOSTAGERESCUEZONE_HPP
#define ISDK_CHOSTAGERESCUEZONE_HPP

#include "../schema_runtime.hpp"
#include "CHostageRescueZoneShim.hpp"

namespace sdk {

struct CHostageRescueZone : CHostageRescueZoneShim {
    SCHEMA_CLASS("client.dll", "CHostageRescueZone");


    // --- Virtual functions (vtable RVA: 0x1A69C48, 254 total) ---
    VFUNC_RAW(246);                                         // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(247);                                         // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(248);                                         // sig: 40 53 48 83 EC 20 48 8B DA E8 ? ? ? ? 48...
    VFUNC_RAW(249);                                         // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(250);                                         // sig: 48 89 5C 24 08 57 48 83 EC 20 0F B6 FA 4... reads: 0xD28
    VFUNC_RAW(251);                                         // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(253);                                         // sig: 48 85 D2 0F 84 ? ? ? ? 48 89 5C 24 08 57... reads: 0x10
};

} // namespace sdk

#endif // ISDK_CHOSTAGERESCUEZONE_HPP

