// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CLeanMatrixUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CLeafUpdateNode
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CLEANMATRIXUPDATENODE_HPP
#define ISDK_CLEANMATRIXUPDATENODE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CLeanMatrixUpdateNode {
    SCHEMA_CLASS("client.dll", "CLeanMatrixUpdateNode");

};

} // namespace sdk

#endif // ISDK_CLEANMATRIXUPDATENODE_HPP

