// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CLightComponent (runtime-resolved offsets)
// Module: client.dll
// Parent: CEntityComponent
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CLIGHTCOMPONENT_HPP
#define ISDK_CLIGHTCOMPONENT_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CLightComponent {
    SCHEMA_CLASS("client.dll", "CLightComponent");


    // --- Virtual functions (vtable RVA: 0x1978C10, 7 total) ---
};

} // namespace sdk

#endif // ISDK_CLIGHTCOMPONENT_HPP

