// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CLookComponentUpdater (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimComponentUpdater
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CLOOKCOMPONENTUPDATER_HPP
#define ISDK_CLOOKCOMPONENTUPDATER_HPP

#include "../schema_runtime.hpp"
#include "CAnimComponentUpdater.hpp"

namespace sdk {

struct CLookComponentUpdater : CAnimComponentUpdater {
    SCHEMA_CLASS("client.dll", "CLookComponentUpdater");

};

} // namespace sdk

#endif // ISDK_CLOOKCOMPONENTUPDATER_HPP

