// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CLookAtUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CUnaryUpdateNode
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CLOOKATUPDATENODE_HPP
#define ISDK_CLOOKATUPDATENODE_HPP

#include "../schema_runtime.hpp"
#include "CUnaryUpdateNode.hpp"

namespace sdk {

struct CLookAtUpdateNode : CUnaryUpdateNode {
    SCHEMA_CLASS("client.dll", "CLookAtUpdateNode");

};

} // namespace sdk

#endif // ISDK_CLOOKATUPDATENODE_HPP

