// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CMaterialAttributeAnimTag (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimTagBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CMATERIALATTRIBUTEANIMTAG_HPP
#define ISDK_CMATERIALATTRIBUTEANIMTAG_HPP

#include "../schema_runtime.hpp"
#include "CAnimTagBase.hpp"

namespace sdk {

struct CMaterialAttributeAnimTag : CAnimTagBase {
    SCHEMA_CLASS("client.dll", "CMaterialAttributeAnimTag");

};

} // namespace sdk

#endif // ISDK_CMATERIALATTRIBUTEANIMTAG_HPP

