// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CModelConfigElement_RandomColor (runtime-resolved offsets)
// Module: client.dll
// Parent: CModelConfigElement
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CMODELCONFIGELEMENT_RANDOMCOLOR_HPP
#define ISDK_CMODELCONFIGELEMENT_RANDOMCOLOR_HPP

#include "../schema_runtime.hpp"
#include "CModelConfigElement.hpp"

namespace sdk {

struct CModelConfigElement_RandomColor : CModelConfigElement {
    SCHEMA_CLASS("client.dll", "CModelConfigElement_RandomColor");

};

} // namespace sdk

#endif // ISDK_CMODELCONFIGELEMENT_RANDOMCOLOR_HPP

