// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CMorphConstraint (runtime-resolved offsets)
// Module: client.dll
// Parent: CBaseConstraint
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CMORPHCONSTRAINT_HPP
#define ISDK_CMORPHCONSTRAINT_HPP

#include "../schema_runtime.hpp"
#include "CBaseConstraint.hpp"

namespace sdk {

struct CMorphConstraint : CBaseConstraint {
    SCHEMA_CLASS("client.dll", "CMorphConstraint");

};

} // namespace sdk

#endif // ISDK_CMORPHCONSTRAINT_HPP

