// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CMorphSetData (runtime-resolved offsets)
// Module: client.dll
// Parent: ?$CRefCounted@V?$CRefCountServiceBase@VCRefMT
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CMORPHSETDATA_HPP
#define ISDK_CMORPHSETDATA_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CMorphSetData {
    SCHEMA_CLASS("client.dll", "CMorphSetData");

};

} // namespace sdk

#endif // ISDK_CMORPHSETDATA_HPP

