// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CMotionMatchingUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CLeafUpdateNode
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CMOTIONMATCHINGUPDATENODE_HPP
#define ISDK_CMOTIONMATCHINGUPDATENODE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CMotionMatchingUpdateNode {
    SCHEMA_CLASS("client.dll", "CMotionMatchingUpdateNode");

};

} // namespace sdk

#endif // ISDK_CMOTIONMATCHINGUPDATENODE_HPP

