// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CMotionNode (runtime-resolved offsets)
// Module: client.dll
// Parent: ?$CMutableRefCounted@V?$CMutableRefCountBase@VCRefMT
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CMOTIONNODE_HPP
#define ISDK_CMOTIONNODE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CMotionNode {
    SCHEMA_CLASS("client.dll", "CMotionNode");

};

} // namespace sdk

#endif // ISDK_CMOTIONNODE_HPP

