// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CMotionGraphUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CLeafUpdateNode
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CMOTIONGRAPHUPDATENODE_HPP
#define ISDK_CMOTIONGRAPHUPDATENODE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CMotionGraphUpdateNode {
    SCHEMA_CLASS("client.dll", "CMotionGraphUpdateNode");

};

} // namespace sdk

#endif // ISDK_CMOTIONGRAPHUPDATENODE_HPP

