// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CMotionMetricEvaluator (runtime-resolved offsets)
// Module: client.dll
// Parent: ?$CMutableRefCounted@V?$CMutableRefCountBase@VCRefMT
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CMOTIONMETRICEVALUATOR_HPP
#define ISDK_CMOTIONMETRICEVALUATOR_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CMotionMetricEvaluator {
    SCHEMA_CLASS("client.dll", "CMotionMetricEvaluator");

};

} // namespace sdk

#endif // ISDK_CMOTIONMETRICEVALUATOR_HPP

