// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CMoverUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CUnaryUpdateNode
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CMOVERUPDATENODE_HPP
#define ISDK_CMOVERUPDATENODE_HPP

#include "../schema_runtime.hpp"
#include "CUnaryUpdateNode.hpp"

namespace sdk {

struct CMoverUpdateNode : CUnaryUpdateNode {
    SCHEMA_CLASS("client.dll", "CMoverUpdateNode");

};

} // namespace sdk

#endif // ISDK_CMOVERUPDATENODE_HPP

