// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CMovementStatsProperty (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CMOVEMENTSTATSPROPERTY_HPP
#define ISDK_CMOVEMENTSTATSPROPERTY_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CMovementStatsProperty {
    SCHEMA_CLASS("client.dll", "CMovementStatsProperty");

};

} // namespace sdk

#endif // ISDK_CMOVEMENTSTATSPROPERTY_HPP

