// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CMovementHandshakeAnimTag (runtime-resolved offsets)
// Module: client.dll
// Parent: CHandshakeAnimTagBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CMOVEMENTHANDSHAKEANIMTAG_HPP
#define ISDK_CMOVEMENTHANDSHAKEANIMTAG_HPP

#include "../schema_runtime.hpp"
#include "CHandshakeAnimTagBase.hpp"

namespace sdk {

struct CMovementHandshakeAnimTag : CHandshakeAnimTagBase {
    SCHEMA_CLASS("client.dll", "CMovementHandshakeAnimTag");

};

} // namespace sdk

#endif // ISDK_CMOVEMENTHANDSHAKEANIMTAG_HPP

