// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CMovementComponentUpdater (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimComponentUpdater
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CMOVEMENTCOMPONENTUPDATER_HPP
#define ISDK_CMOVEMENTCOMPONENTUPDATER_HPP

#include "../schema_runtime.hpp"
#include "CAnimComponentUpdater.hpp"

namespace sdk {

struct CMovementComponentUpdater : CAnimComponentUpdater {
    SCHEMA_CLASS("client.dll", "CMovementComponentUpdater");

};

} // namespace sdk

#endif // ISDK_CMOVEMENTCOMPONENTUPDATER_HPP

