// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CMultiplayer_Expresser (runtime-resolved offsets)
// Module: client.dll
// Parent: CAI_ExpresserWithFollowup
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CMULTIPLAYER_EXPRESSER_HPP
#define ISDK_CMULTIPLAYER_EXPRESSER_HPP

#include "../schema_runtime.hpp"
#include "CAI_ExpresserWithFollowup.hpp"

namespace sdk {

struct CMultiplayer_Expresser : CAI_ExpresserWithFollowup {
    SCHEMA_CLASS("client.dll", "CMultiplayer_Expresser");

};

} // namespace sdk

#endif // ISDK_CMULTIPLAYER_EXPRESSER_HPP

