// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CNavVolume (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CNAVVOLUME_HPP
#define ISDK_CNAVVOLUME_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CNavVolume {
    SCHEMA_CLASS("client.dll", "CNavVolume");

};

} // namespace sdk

#endif // ISDK_CNAVVOLUME_HPP

