// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CNetworkTransmitComponent (runtime-resolved offsets)
// Module: client.dll
// Parent: IEventRegisterCallback
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CNETWORKTRANSMITCOMPONENT_HPP
#define ISDK_CNETWORKTRANSMITCOMPONENT_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CNetworkTransmitComponent {
    SCHEMA_CLASS("client.dll", "CNetworkTransmitComponent");


    // --- Virtual functions (vtable RVA: 0x1977CA0, 6 total) ---
};

} // namespace sdk

#endif // ISDK_CNETWORKTRANSMITCOMPONENT_HPP

