// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CNetworkedSequenceOperation (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CNETWORKEDSEQUENCEOPERATION_HPP
#define ISDK_CNETWORKEDSEQUENCEOPERATION_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CNetworkedSequenceOperation {
    SCHEMA_CLASS("client.dll", "CNetworkedSequenceOperation");


    // --- Virtual functions (vtable RVA: 0x1ADFBC0, 10 total) ---
};

} // namespace sdk

#endif // ISDK_CNETWORKEDSEQUENCEOPERATION_HPP

