// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CNewParticleEffect (runtime-resolved offsets)
// Module: client.dll
// Parent: IParticleEffect
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CNEWPARTICLEEFFECT_HPP
#define ISDK_CNEWPARTICLEEFFECT_HPP

#include "../schema_runtime.hpp"
#include "IParticleEffect.hpp"

namespace sdk {

struct CNewParticleEffect : IParticleEffect {
    SCHEMA_CLASS("client.dll", "CNewParticleEffect");


    // --- Virtual functions (vtable RVA: 0x1CA8F80, 8 total) ---
    VFUNC_RAW(0);                                           // sig: 40 53 48 83 EC 20 48 8B DA E8 ? ? ? ? 48...
    VFUNC_RAW(1);                                           // sig: 48 89 5C 24 08 57 48 83 EC 20 8B DA 48 8...
    VFUNC_RAW(2);                                           // sig: 40 53 48 83 EC 30 48 8B D9 0F 29 74 24 2... reads: 0x20
    VFUNC_RAW(3);                                           // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(4);                                           // sig: 0F B6 41 30 C0 E8 ? ? ? ? CC CC CC CC CC... reads: 0x30
    VFUNC_RAW(5);                                           // sig: 0F B6 41 30 24 BF C0 E2 06 0A C2 88 41 3... reads: 0x30
    VFUNC_RAW(6);                                           // sig: F6 41 30 20 74 0C 48 8B 01 BA 01 00 00 0...
    VFUNC_RAW(7);                                           // sig: 48 8D 41 40 C3 CC CC CC CC CC CC CC CC C... reads: 0x40
};

} // namespace sdk

#endif // ISDK_CNEWPARTICLEEFFECT_HPP

