// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CNmAimCSTask (runtime-resolved offsets)
// Module: client.dll
// Parent: CNmPoseTask
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CNMAIMCSTASK_HPP
#define ISDK_CNMAIMCSTASK_HPP

#include "../schema_runtime.hpp"
#include "CNmPoseTask.hpp"

namespace sdk {

struct CNmAimCSTask : CNmPoseTask {
    SCHEMA_CLASS("client.dll", "CNmAimCSTask");


    // --- Virtual functions (vtable RVA: 0x1A497A0, 12 total) ---
};

} // namespace sdk

#endif // ISDK_CNMAIMCSTASK_HPP

