// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CNmChainLookatTask (runtime-resolved offsets)
// Module: client.dll
// Parent: CNmPoseTask
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CNMCHAINLOOKATTASK_HPP
#define ISDK_CNMCHAINLOOKATTASK_HPP

#include "../schema_runtime.hpp"
#include "CNmPoseTask.hpp"

namespace sdk {

struct CNmChainLookatTask : CNmPoseTask {
    SCHEMA_CLASS("client.dll", "CNmChainLookatTask");


    // --- Virtual functions (vtable RVA: 0x1BDF530, 12 total) ---
};

} // namespace sdk

#endif // ISDK_CNMCHAINLOOKATTASK_HPP

