// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CNmCachedPoseReadTask (runtime-resolved offsets)
// Module: client.dll
// Parent: CNmPoseTask
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CNMCACHEDPOSEREADTASK_HPP
#define ISDK_CNMCACHEDPOSEREADTASK_HPP

#include "../schema_runtime.hpp"
#include "CNmPoseTask.hpp"

namespace sdk {

struct CNmCachedPoseReadTask : CNmPoseTask {
    SCHEMA_CLASS("client.dll", "CNmCachedPoseReadTask");


    // --- Virtual functions (vtable RVA: 0x1BDF498, 12 total) ---
};

} // namespace sdk

#endif // ISDK_CNMCACHEDPOSEREADTASK_HPP

