// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CNmEventConsumerParticle (runtime-resolved offsets)
// Module: client.dll
// Parent: CNmEventConsumer
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CNMEVENTCONSUMERPARTICLE_HPP
#define ISDK_CNMEVENTCONSUMERPARTICLE_HPP

#include "../schema_runtime.hpp"
#include "CNmEventConsumer.hpp"

namespace sdk {

struct CNmEventConsumerParticle : CNmEventConsumer {
    SCHEMA_CLASS("client.dll", "CNmEventConsumerParticle");


    // --- Virtual functions (vtable RVA: 0x19D4BD0, 12 total) ---
    VFUNC_RAW(8);                                           // sig: 48 89 5C 24 08 57 48 83 EC 20 48 8B 5A 3...
    VFUNC_RAW(9);                                           // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(10);                                          // sig: 48 89 6C 24 10 48 89 74 24 18 57 48 83 E...
    VFUNC_RAW(11);                                          // sig: 40 53 48 83 EC 30 80 7A 2E 00 48 8B C2 7...
};

} // namespace sdk

#endif // ISDK_CNMEVENTCONSUMERPARTICLE_HPP

