// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CNmEventConsumerPulse (runtime-resolved offsets)
// Module: client.dll
// Parent: CNmEventConsumer
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CNMEVENTCONSUMERPULSE_HPP
#define ISDK_CNMEVENTCONSUMERPULSE_HPP

#include "../schema_runtime.hpp"
#include "CNmEventConsumer.hpp"

namespace sdk {

struct CNmEventConsumerPulse : CNmEventConsumer {
    SCHEMA_CLASS("client.dll", "CNmEventConsumerPulse");


    // --- Virtual functions (vtable RVA: 0x19D4C38, 12 total) ---
};

} // namespace sdk

#endif // ISDK_CNMEVENTCONSUMERPULSE_HPP

