// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CNmEventConsumerLegacy (runtime-resolved offsets)
// Module: client.dll
// Parent: CNmEventConsumer
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CNMEVENTCONSUMERLEGACY_HPP
#define ISDK_CNMEVENTCONSUMERLEGACY_HPP

#include "../schema_runtime.hpp"
#include "CNmEventConsumer.hpp"

namespace sdk {

struct CNmEventConsumerLegacy : CNmEventConsumer {
    SCHEMA_CLASS("client.dll", "CNmEventConsumerLegacy");


    // --- Virtual functions (vtable RVA: 0x19D4B68, 12 total) ---
};

} // namespace sdk

#endif // ISDK_CNMEVENTCONSUMERLEGACY_HPP

