// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CNmEventConsumerSound (runtime-resolved offsets)
// Module: client.dll
// Parent: CNmEventConsumer
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CNMEVENTCONSUMERSOUND_HPP
#define ISDK_CNMEVENTCONSUMERSOUND_HPP

#include "../schema_runtime.hpp"
#include "CNmEventConsumer.hpp"

namespace sdk {

struct CNmEventConsumerSound : CNmEventConsumer {
    SCHEMA_CLASS("client.dll", "CNmEventConsumerSound");


    // --- Virtual functions (vtable RVA: 0x19D4CA0, 14 total) ---
    VFUNC_RAW(8);                                           // sig: 40 53 48 83 EC 20 48 8B 42 30 49 8B D8 8...
    VFUNC_RAW(9);                                           // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(10);                                          // sig: 48 89 6C 24 18 48 89 74 24 20 41 56 48 8...
    VFUNC_RAW(11);                                          // sig: 48 83 EC 38 80 B9 B0 00 00 00 00 48 8B C... reads: 0xB0
    VFUNC_RAW(12);                                          // sig: 48 89 5C 24 08 57 48 83 EC 20 48 8B 01 4...
    VFUNC_RAW(13);                                          // sig: 48 89 5C 24 10 48 89 74 24 18 57 48 83 E... reads: 0x8, 0x10, 0x18
};

} // namespace sdk

#endif // ISDK_CNMEVENTCONSUMERSOUND_HPP

