// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CNmEntityAttributeEventBase (runtime-resolved offsets)
// Module: client.dll
// Parent: CNmEvent
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CNMENTITYATTRIBUTEEVENTBASE_HPP
#define ISDK_CNMENTITYATTRIBUTEEVENTBASE_HPP

#include "../schema_runtime.hpp"
#include "CNmEvent.hpp"

namespace sdk {

struct CNmEntityAttributeEventBase : CNmEvent {
    SCHEMA_CLASS("client.dll", "CNmEntityAttributeEventBase");


    // --- Virtual functions (vtable RVA: 0x1BDFDD8, 9 total) ---
    VFUNC_RAW(0);                                           // sig: 40 53 48 83 EC 20 48 8B DA 48 8D 15 ? ? ...
    VFUNC_RAW(1);                                           // sig: E9 ? ? ? ? CC CC CC CC CC CC CC CC CC CC...
    VFUNC_RAW(2);                                           // sig: 4C 8D 05 ? ? ? ? E9 ? ? ? ? CC CC CC CC ...
    VFUNC_RAW(4);                                           // sig: 48 89 5C 24 08 57 48 83 EC 20 48 8B D9 8...
    VFUNC_RAW(7);                                           // sig: 8B 41 18 C3 CC CC CC CC CC CC CC CC CC C... reads: 0x18
    VFUNC_RAW(8);                                           // sig: 40 53 48 83 EC 30 33 C0 C7 42 04 00 01 0...
};

} // namespace sdk

#endif // ISDK_CNMENTITYATTRIBUTEEVENTBASE_HPP

