// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CNmEvent (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CNMEVENT_HPP
#define ISDK_CNMEVENT_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CNmEvent {
    SCHEMA_CLASS("client.dll", "CNmEvent");

};

} // namespace sdk

#endif // ISDK_CNMEVENT_HPP

