// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CNmEntityAttributeFloatEvent (runtime-resolved offsets)
// Module: client.dll
// Parent: CNmEntityAttributeEventBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CNMENTITYATTRIBUTEFLOATEVENT_HPP
#define ISDK_CNMENTITYATTRIBUTEFLOATEVENT_HPP

#include "../schema_runtime.hpp"
#include "CNmEntityAttributeEventBase.hpp"

namespace sdk {

struct CNmEntityAttributeFloatEvent : CNmEntityAttributeEventBase {
    SCHEMA_CLASS("client.dll", "CNmEntityAttributeFloatEvent");


    // --- Virtual functions (vtable RVA: 0x1BDFEA8, 9 total) ---
    VFUNC_RAW(7);                                           // sig: 8B 41 18 C3 CC CC CC CC CC CC CC CC CC C... reads: 0x18
    VFUNC_RAW(8);                                           // sig: 40 53 48 83 EC 30 33 C0 C7 42 04 00 01 0...
};

} // namespace sdk

#endif // ISDK_CNMENTITYATTRIBUTEFLOATEVENT_HPP

