// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CNmFollowBoneTask (runtime-resolved offsets)
// Module: client.dll
// Parent: CNmPoseTask
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CNMFOLLOWBONETASK_HPP
#define ISDK_CNMFOLLOWBONETASK_HPP

#include "../schema_runtime.hpp"
#include "CNmPoseTask.hpp"

namespace sdk {

struct CNmFollowBoneTask : CNmPoseTask {
    SCHEMA_CLASS("client.dll", "CNmFollowBoneTask");


    // --- Virtual functions (vtable RVA: 0x1BD9CB0, 12 total) ---
    VFUNC_RAW(11);                                          // sig: 48 89 5C 24 10 57 48 83 EC 60 48 8B 01 4...
};

} // namespace sdk

#endif // ISDK_CNMFOLLOWBONETASK_HPP

