// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CNmFootEvent (runtime-resolved offsets)
// Module: client.dll
// Parent: CNmEvent
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CNMFOOTEVENT_HPP
#define ISDK_CNMFOOTEVENT_HPP

#include "../schema_runtime.hpp"
#include "CNmEvent.hpp"

namespace sdk {

struct CNmFootEvent : CNmEvent {
    SCHEMA_CLASS("client.dll", "CNmFootEvent");


    // --- Virtual functions (vtable RVA: 0x1BD9F68, 9 total) ---
    VFUNC_RAW(0);                                           // sig: 40 53 48 83 EC 20 48 8B DA 48 8D 15 ? ? ...
    VFUNC_RAW(1);                                           // sig: 40 55 53 56 48 8B EC 48 83 EC 70 48 8B D...
    VFUNC_RAW(2);                                           // sig: 4C 8D 05 ? ? ? ? E9 ? ? ? ? CC CC CC CC ...
    VFUNC_RAW(4);                                           // sig: 40 53 48 83 EC 20 48 8B D9 F6 C2 01 74 0...
    VFUNC_RAW(8);                                           // sig: 40 53 48 83 EC 30 0F B6 49 18 48 8B DA E... reads: 0x18
};

} // namespace sdk

#endif // ISDK_CNMFOOTEVENT_HPP

