// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CNmFrameSnapEvent (runtime-resolved offsets)
// Module: client.dll
// Parent: CNmEvent
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CNMFRAMESNAPEVENT_HPP
#define ISDK_CNMFRAMESNAPEVENT_HPP

#include "../schema_runtime.hpp"
#include "CNmEvent.hpp"

namespace sdk {

struct CNmFrameSnapEvent : CNmEvent {
    SCHEMA_CLASS("client.dll", "CNmFrameSnapEvent");


    // --- Virtual functions (vtable RVA: 0x1BDA050, 9 total) ---
};

} // namespace sdk

#endif // ISDK_CNMFRAMESNAPEVENT_HPP

