// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CNmGraphVariationUserData (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CNMGRAPHVARIATIONUSERDATA_HPP
#define ISDK_CNMGRAPHVARIATIONUSERDATA_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CNmGraphVariationUserData {
    SCHEMA_CLASS("client.dll", "CNmGraphVariationUserData");


    // --- Virtual functions (vtable RVA: 0x1AB9270, 9 total) ---
};

} // namespace sdk

#endif // ISDK_CNMGRAPHVARIATIONUSERDATA_HPP

