// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CNmMaterialAttributeEvent (runtime-resolved offsets)
// Module: client.dll
// Parent: CNmEvent
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CNMMATERIALATTRIBUTEEVENT_HPP
#define ISDK_CNMMATERIALATTRIBUTEEVENT_HPP

#include "../schema_runtime.hpp"
#include "CNmEvent.hpp"

namespace sdk {

struct CNmMaterialAttributeEvent : CNmEvent {
    SCHEMA_CLASS("client.dll", "CNmMaterialAttributeEvent");


    // --- Virtual functions (vtable RVA: 0x1BDFCC0, 9 total) ---
};

} // namespace sdk

#endif // ISDK_CNMMATERIALATTRIBUTEEVENT_HPP

