// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CNmModelSpaceBlendTask (runtime-resolved offsets)
// Module: client.dll
// Parent: CNmBlendTaskBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CNMMODELSPACEBLENDTASK_HPP
#define ISDK_CNMMODELSPACEBLENDTASK_HPP

#include "../schema_runtime.hpp"
#include "CNmBlendTaskBase.hpp"

namespace sdk {

struct CNmModelSpaceBlendTask : CNmBlendTaskBase {
    SCHEMA_CLASS("client.dll", "CNmModelSpaceBlendTask");


    // --- Virtual functions (vtable RVA: 0x1BDF368, 12 total) ---
    VFUNC_RAW(0);                                           // sig: 40 53 48 83 EC 20 48 8B DA 48 8D 15 ? ? ...
    VFUNC_RAW(1);                                           // sig: 48 89 5C 24 08 57 48 83 EC 20 8B DA 48 8...
    VFUNC_RAW(2);                                           // sig: 40 53 55 56 57 41 55 48 83 EC 50 44 8B 4...
    VFUNC_RAW(5);                                           // sig: 48 89 5C 24 08 48 89 74 24 10 57 48 83 E... reads: 0x70, 0xC8
    VFUNC_RAW(6);                                           // sig: 48 89 5C 24 08 57 48 83 EC 20 48 8B F9 4... reads: 0xC8
    VFUNC_RAW(8);                                           // sig: 40 53 48 83 EC 20 33 C0 C7 42 04 00 01 0...
    VFUNC_RAW(9);                                           // sig: 8B 05 ? ? ? ? 89 02 48 8B C2 C3 CC CC CC...
    VFUNC_RAW(10);                                          // sig: F3 0F 10 81 C8 00 00 00 C3 CC CC CC CC C... reads: 0xC8
    VFUNC_RAW(11);                                          // sig: 48 89 5C 24 08 57 48 83 EC 60 8B 05 ? ? ...
};

} // namespace sdk

#endif // ISDK_CNMMODELSPACEBLENDTASK_HPP

