// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CNmOrientationWarpEvent (runtime-resolved offsets)
// Module: client.dll
// Parent: CNmEvent
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CNMORIENTATIONWARPEVENT_HPP
#define ISDK_CNMORIENTATIONWARPEVENT_HPP

#include "../schema_runtime.hpp"
#include "CNmEvent.hpp"

namespace sdk {

struct CNmOrientationWarpEvent : CNmEvent {
    SCHEMA_CLASS("client.dll", "CNmOrientationWarpEvent");


    // --- Virtual functions (vtable RVA: 0x1BDA9A0, 9 total) ---
};

} // namespace sdk

#endif // ISDK_CNMORIENTATIONWARPEVENT_HPP

