// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CNmOverlayBlendTask (runtime-resolved offsets)
// Module: client.dll
// Parent: CNmBlendTaskBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CNMOVERLAYBLENDTASK_HPP
#define ISDK_CNMOVERLAYBLENDTASK_HPP

#include "../schema_runtime.hpp"
#include "CNmBlendTaskBase.hpp"

namespace sdk {

struct CNmOverlayBlendTask : CNmBlendTaskBase {
    SCHEMA_CLASS("client.dll", "CNmOverlayBlendTask");


    // --- Virtual functions (vtable RVA: 0x1BDF278, 12 total) ---
};

} // namespace sdk

#endif // ISDK_CNMOVERLAYBLENDTASK_HPP

