// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CNmParticleEvent (runtime-resolved offsets)
// Module: client.dll
// Parent: CNmEvent
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CNMPARTICLEEVENT_HPP
#define ISDK_CNMPARTICLEEVENT_HPP

#include "../schema_runtime.hpp"
#include "CNmEvent.hpp"

namespace sdk {

struct CNmParticleEvent : CNmEvent {
    SCHEMA_CLASS("client.dll", "CNmParticleEvent");


    // --- Virtual functions (vtable RVA: 0x1BDA258, 9 total) ---
};

} // namespace sdk

#endif // ISDK_CNMPARTICLEEVENT_HPP

