// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CNmPoseTask (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CNMPOSETASK_HPP
#define ISDK_CNMPOSETASK_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CNmPoseTask {
    SCHEMA_CLASS("client.dll", "CNmPoseTask");


    // --- Virtual functions (vtable RVA: 0x1A496D0, 12 total) ---
    VFUNC_RAW(8);                                           // sig: 33 C0 C7 42 04 00 01 00 C0 89 02 48 89 4...
    VFUNC_RAW(9);                                           // sig: 8B 05 ? ? ? ? 89 02 48 8B C2 C3 CC CC CC...
    VFUNC_RAW(11);                                          // sig: 48 89 5C 24 10 57 48 83 EC 60 48 8B 01 4...
};

} // namespace sdk

#endif // ISDK_CNMPOSETASK_HPP

