// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CNmReferencePoseTask (runtime-resolved offsets)
// Module: client.dll
// Parent: CNmPoseTask
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CNMREFERENCEPOSETASK_HPP
#define ISDK_CNMREFERENCEPOSETASK_HPP

#include "../schema_runtime.hpp"
#include "CNmPoseTask.hpp"

namespace sdk {

struct CNmReferencePoseTask : CNmPoseTask {
    SCHEMA_CLASS("client.dll", "CNmReferencePoseTask");


    // --- Virtual functions (vtable RVA: 0x1BD8D28, 12 total) ---
};

} // namespace sdk

#endif // ISDK_CNMREFERENCEPOSETASK_HPP

