// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CNmSnapWeaponTask (runtime-resolved offsets)
// Module: client.dll
// Parent: CNmPoseTask
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CNMSNAPWEAPONTASK_HPP
#define ISDK_CNMSNAPWEAPONTASK_HPP

#include "../schema_runtime.hpp"
#include "CNmPoseTask.hpp"

namespace sdk {

struct CNmSnapWeaponTask : CNmPoseTask {
    SCHEMA_CLASS("client.dll", "CNmSnapWeaponTask");


    // --- Virtual functions (vtable RVA: 0x1A49960, 12 total) ---
    VFUNC_RAW(0);                                           // sig: 40 53 48 83 EC 20 48 8B DA 48 8D 15 ? ? ...
    VFUNC_RAW(1);                                           // sig: 48 89 5C 24 08 48 89 74 24 10 57 48 83 E...
    VFUNC_RAW(2);                                           // sig: 40 55 53 56 57 41 55 41 56 48 8D AC 24 4...
    VFUNC_RAW(5);                                           // sig: 48 89 5C 24 08 57 48 83 EC 20 0F B6 79 7... reads: 0x70
    VFUNC_RAW(6);                                           // sig: 48 89 5C 24 08 48 8B D9 4C 8B D2 48 8B 5...
    VFUNC_RAW(8);                                           // sig: 33 C0 C7 42 04 00 01 00 C0 89 02 48 89 4...
    VFUNC_RAW(9);                                           // sig: 8B 05 ? ? ? ? 89 02 48 8B C2 C3 CC CC CC...
    VFUNC_RAW(11);                                          // sig: 48 89 5C 24 10 57 48 83 EC 60 48 8B 01 4...
};

} // namespace sdk

#endif // ISDK_CNMSNAPWEAPONTASK_HPP

