// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CNmSoundEvent (runtime-resolved offsets)
// Module: client.dll
// Parent: CNmEvent
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CNMSOUNDEVENT_HPP
#define ISDK_CNMSOUNDEVENT_HPP

#include "../schema_runtime.hpp"
#include "CNmEvent.hpp"

namespace sdk {

struct CNmSoundEvent : CNmEvent {
    SCHEMA_CLASS("client.dll", "CNmSoundEvent");


    // --- Virtual functions (vtable RVA: 0x1BDA458, 9 total) ---
};

} // namespace sdk

#endif // ISDK_CNMSOUNDEVENT_HPP

