// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CNmTargetWarpEvent (runtime-resolved offsets)
// Module: client.dll
// Parent: CNmEvent
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CNMTARGETWARPEVENT_HPP
#define ISDK_CNMTARGETWARPEVENT_HPP

#include "../schema_runtime.hpp"
#include "CNmEvent.hpp"

namespace sdk {

struct CNmTargetWarpEvent : CNmEvent {
    SCHEMA_CLASS("client.dll", "CNmTargetWarpEvent");


    // --- Virtual functions (vtable RVA: 0x1BDA9F8, 9 total) ---
    VFUNC_RAW(0);                                           // sig: 40 53 48 83 EC 20 48 8B DA 48 8D 15 ? ? ...
    VFUNC_RAW(1);                                           // sig: E9 ? ? ? ? CC CC CC CC CC CC CC CC CC CC...
    VFUNC_RAW(2);                                           // sig: 4C 8D 05 ? ? ? ? ? ? ? 00 00 CC CC CC CC...
    VFUNC_RAW(4);                                           // sig: 40 53 48 83 EC 20 48 8B D9 F6 C2 01 74 0...
    VFUNC_RAW(8);                                           // sig: 40 53 48 83 EC 30 0F B6 41 18 4C 8D 05 ?... reads: 0x18
};

} // namespace sdk

#endif // ISDK_CNMTARGETWARPEVENT_HPP

