// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CNmTwoBoneIKTask (runtime-resolved offsets)
// Module: client.dll
// Parent: CNmPoseTask
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CNMTWOBONEIKTASK_HPP
#define ISDK_CNMTWOBONEIKTASK_HPP

#include "../schema_runtime.hpp"
#include "CNmPoseTask.hpp"

namespace sdk {

struct CNmTwoBoneIKTask : CNmPoseTask {
    SCHEMA_CLASS("client.dll", "CNmTwoBoneIKTask");


    // --- Virtual functions (vtable RVA: 0x1BDF970, 12 total) ---
};

} // namespace sdk

#endif // ISDK_CNMTWOBONEIKTASK_HPP

