// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CNmTransitionEvent (runtime-resolved offsets)
// Module: client.dll
// Parent: CNmEvent
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CNMTRANSITIONEVENT_HPP
#define ISDK_CNMTRANSITIONEVENT_HPP

#include "../schema_runtime.hpp"
#include "CNmEvent.hpp"

namespace sdk {

struct CNmTransitionEvent : CNmEvent {
    SCHEMA_CLASS("client.dll", "CNmTransitionEvent");


    // --- Virtual functions (vtable RVA: 0x1BDA728, 9 total) ---
};

} // namespace sdk

#endif // ISDK_CNMTRANSITIONEVENT_HPP

