// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CNmZeroPoseTask (runtime-resolved offsets)
// Module: client.dll
// Parent: CNmPoseTask
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CNMZEROPOSETASK_HPP
#define ISDK_CNMZEROPOSETASK_HPP

#include "../schema_runtime.hpp"
#include "CNmPoseTask.hpp"

namespace sdk {

struct CNmZeroPoseTask : CNmPoseTask {
    SCHEMA_CLASS("client.dll", "CNmZeroPoseTask");


    // --- Virtual functions (vtable RVA: 0x1BDF5D8, 12 total) ---
    VFUNC_RAW(9);                                           // sig: 8B 05 ? ? ? ? 89 02 48 8B C2 C3 CC CC CC...
    VFUNC_RAW(11);                                          // sig: 48 89 5C 24 10 57 48 83 EC 60 48 8B 01 4...
};

} // namespace sdk

#endif // ISDK_CNMZEROPOSETASK_HPP

