// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: ConstraintSoundInfo (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CONSTRAINTSOUNDINFO_HPP
#define ISDK_CONSTRAINTSOUNDINFO_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct ConstraintSoundInfo {
    SCHEMA_CLASS("client.dll", "ConstraintSoundInfo");

};

} // namespace sdk

#endif // ISDK_CONSTRAINTSOUNDINFO_HPP

