// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: COrientationWarpUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CUnaryUpdateNode
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CORIENTATIONWARPUPDATENODE_HPP
#define ISDK_CORIENTATIONWARPUPDATENODE_HPP

#include "../schema_runtime.hpp"
#include "CUnaryUpdateNode.hpp"

namespace sdk {

struct COrientationWarpUpdateNode : CUnaryUpdateNode {
    SCHEMA_CLASS("client.dll", "COrientationWarpUpdateNode");

};

} // namespace sdk

#endif // ISDK_CORIENTATIONWARPUPDATENODE_HPP

