// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: COrientConstraint (runtime-resolved offsets)
// Module: client.dll
// Parent: CBaseConstraint
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CORIENTCONSTRAINT_HPP
#define ISDK_CORIENTCONSTRAINT_HPP

#include "../schema_runtime.hpp"
#include "CBaseConstraint.hpp"

namespace sdk {

struct COrientConstraint : CBaseConstraint {
    SCHEMA_CLASS("client.dll", "COrientConstraint");

};

} // namespace sdk

#endif // ISDK_CORIENTCONSTRAINT_HPP

