// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CountdownTimer (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_COUNTDOWNTIMER_HPP
#define ISDK_COUNTDOWNTIMER_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CountdownTimer {
    SCHEMA_CLASS("client.dll", "CountdownTimer");


    // --- Virtual functions (vtable RVA: 0x1ADFC18, 9 total) ---
    VFUNC_RAW(8);                                           // sig: 48 8B 05 ? ? ? ? C3 CC CC CC CC CC CC CC...
};

} // namespace sdk

#endif // ISDK_COUNTDOWNTIMER_HPP

