// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPairedSequenceUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CSequenceUpdateNodeBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPAIREDSEQUENCEUPDATENODE_HPP
#define ISDK_CPAIREDSEQUENCEUPDATENODE_HPP

#include "../schema_runtime.hpp"
#include "CSequenceUpdateNodeBase.hpp"

namespace sdk {

struct CPairedSequenceUpdateNode : CSequenceUpdateNodeBase {
    SCHEMA_CLASS("client.dll", "CPairedSequenceUpdateNode");

};

} // namespace sdk

#endif // ISDK_CPAIREDSEQUENCEUPDATENODE_HPP

