// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPairedSequenceComponentUpdater (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimComponentUpdater
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPAIREDSEQUENCECOMPONENTUPDATER_HPP
#define ISDK_CPAIREDSEQUENCECOMPONENTUPDATER_HPP

#include "../schema_runtime.hpp"
#include "CAnimComponentUpdater.hpp"

namespace sdk {

struct CPairedSequenceComponentUpdater : CAnimComponentUpdater {
    SCHEMA_CLASS("client.dll", "CPairedSequenceComponentUpdater");

};

} // namespace sdk

#endif // ISDK_CPAIREDSEQUENCECOMPONENTUPDATER_HPP

