// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CParticleCollectionFloatInput (runtime-resolved offsets)
// Module: client.dll
// Parent: CParticleFloatInput
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPARTICLECOLLECTIONFLOATINPUT_HPP
#define ISDK_CPARTICLECOLLECTIONFLOATINPUT_HPP

#include "../schema_runtime.hpp"
#include "CParticleFloatInput.hpp"

namespace sdk {

struct CParticleCollectionFloatInput : CParticleFloatInput {
    SCHEMA_CLASS("client.dll", "CParticleCollectionFloatInput");

};

} // namespace sdk

#endif // ISDK_CPARTICLECOLLECTIONFLOATINPUT_HPP

