// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CParticleRemapFloatInput (runtime-resolved offsets)
// Module: client.dll
// Parent: CParticleFloatInput
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPARTICLEREMAPFLOATINPUT_HPP
#define ISDK_CPARTICLEREMAPFLOATINPUT_HPP

#include "../schema_runtime.hpp"
#include "CParticleFloatInput.hpp"

namespace sdk {

struct CParticleRemapFloatInput : CParticleFloatInput {
    SCHEMA_CLASS("client.dll", "CParticleRemapFloatInput");

};

} // namespace sdk

#endif // ISDK_CPARTICLEREMAPFLOATINPUT_HPP

