// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CParticleFunctionForce (runtime-resolved offsets)
// Module: client.dll
// Parent: CParticleFunction
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPARTICLEFUNCTIONFORCE_HPP
#define ISDK_CPARTICLEFUNCTIONFORCE_HPP

#include "../schema_runtime.hpp"
#include "CParticleFunction.hpp"

namespace sdk {

struct CParticleFunctionForce : CParticleFunction {
    SCHEMA_CLASS("client.dll", "CParticleFunctionForce");

};

} // namespace sdk

#endif // ISDK_CPARTICLEFUNCTIONFORCE_HPP

