// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CParticleSystemDefinition (runtime-resolved offsets)
// Module: client.dll
// Parent: IParticleSystemDefinition
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPARTICLESYSTEMDEFINITION_HPP
#define ISDK_CPARTICLESYSTEMDEFINITION_HPP

#include "../schema_runtime.hpp"
#include "IParticleSystemDefinition.hpp"

namespace sdk {

struct CParticleSystemDefinition : IParticleSystemDefinition {
    SCHEMA_CLASS("client.dll", "CParticleSystemDefinition");

};

} // namespace sdk

#endif // ISDK_CPARTICLESYSTEMDEFINITION_HPP

