// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CParticleCollectionRendererFloatInput (runtime-resolved offsets)
// Module: client.dll
// Parent: CParticleCollectionFloatInput
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPARTICLECOLLECTIONRENDERERFLOATINPUT_HPP
#define ISDK_CPARTICLECOLLECTIONRENDERERFLOATINPUT_HPP

#include "../schema_runtime.hpp"
#include "CParticleCollectionFloatInput.hpp"

namespace sdk {

struct CParticleCollectionRendererFloatInput : CParticleCollectionFloatInput {
    SCHEMA_CLASS("client.dll", "CParticleCollectionRendererFloatInput");

};

} // namespace sdk

#endif // ISDK_CPARTICLECOLLECTIONRENDERERFLOATINPUT_HPP

