// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CParticleAnimTag (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimTagBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPARTICLEANIMTAG_HPP
#define ISDK_CPARTICLEANIMTAG_HPP

#include "../schema_runtime.hpp"
#include "CAnimTagBase.hpp"

namespace sdk {

struct CParticleAnimTag : CAnimTagBase {
    SCHEMA_CLASS("client.dll", "CParticleAnimTag");

};

} // namespace sdk

#endif // ISDK_CPARTICLEANIMTAG_HPP

