// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CParentConstraint (runtime-resolved offsets)
// Module: client.dll
// Parent: CBaseConstraint
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPARENTCONSTRAINT_HPP
#define ISDK_CPARENTCONSTRAINT_HPP

#include "../schema_runtime.hpp"
#include "CBaseConstraint.hpp"

namespace sdk {

struct CParentConstraint : CBaseConstraint {
    SCHEMA_CLASS("client.dll", "CParentConstraint");

};

} // namespace sdk

#endif // ISDK_CPARENTCONSTRAINT_HPP

