// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CParticleCollectionRendererVecInput (runtime-resolved offsets)
// Module: client.dll
// Parent: CParticleCollectionVecInput
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPARTICLECOLLECTIONRENDERERVECINPUT_HPP
#define ISDK_CPARTICLECOLLECTIONRENDERERVECINPUT_HPP

#include "../schema_runtime.hpp"
#include "CParticleCollectionVecInput.hpp"

namespace sdk {

struct CParticleCollectionRendererVecInput : CParticleCollectionVecInput {
    SCHEMA_CLASS("client.dll", "CParticleCollectionRendererVecInput");

};

} // namespace sdk

#endif // ISDK_CPARTICLECOLLECTIONRENDERERVECINPUT_HPP

