// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CParticleFunction (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPARTICLEFUNCTION_HPP
#define ISDK_CPARTICLEFUNCTION_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CParticleFunction {
    SCHEMA_CLASS("client.dll", "CParticleFunction");

};

} // namespace sdk

#endif // ISDK_CPARTICLEFUNCTION_HPP

