// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CParticleTransformInput (runtime-resolved offsets)
// Module: client.dll
// Parent: CParticleInput
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPARTICLETRANSFORMINPUT_HPP
#define ISDK_CPARTICLETRANSFORMINPUT_HPP

#include "../schema_runtime.hpp"
#include "CParticleInput.hpp"

namespace sdk {

struct CParticleTransformInput : CParticleInput {
    SCHEMA_CLASS("client.dll", "CParticleTransformInput");

};

} // namespace sdk

#endif // ISDK_CPARTICLETRANSFORMINPUT_HPP

