// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPathMetricEvaluator (runtime-resolved offsets)
// Module: client.dll
// Parent: CMotionMetricEvaluator
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPATHMETRICEVALUATOR_HPP
#define ISDK_CPATHMETRICEVALUATOR_HPP

#include "../schema_runtime.hpp"
#include "CMotionMetricEvaluator.hpp"

namespace sdk {

struct CPathMetricEvaluator : CMotionMetricEvaluator {
    SCHEMA_CLASS("client.dll", "CPathMetricEvaluator");

};

} // namespace sdk

#endif // ISDK_CPATHMETRICEVALUATOR_HPP

