// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPathQueryComponent (runtime-resolved offsets)
// Module: client.dll
// Parent: CEntityComponent
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPATHQUERYCOMPONENT_HPP
#define ISDK_CPATHQUERYCOMPONENT_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CPathQueryComponent {
    SCHEMA_CLASS("client.dll", "CPathQueryComponent");


    // --- Virtual functions (vtable RVA: 0x1AD6D18, 7 total) ---
    VFUNC_RAW(0);                                           // sig: 40 53 48 83 EC 20 48 8B DA E8 ? ? ? ? 48...
    VFUNC_RAW(2);                                           // sig: 48 8B 05 ? ? ? ? C3 CC CC CC CC CC CC CC...
    VFUNC_RAW(3);                                           // sig: 48 83 C1 10 E9 ? ? ? ? CC CC CC CC CC CC...
    VFUNC_RAW(4);                                           // sig: 48 83 C1 10 4C 8D 05 ? ? ? ? E9 ? ? ? ? ...
    VFUNC_RAW(5);                                           // sig: E9 ? ? ? ? CC CC CC CC CC CC CC CC CC CC...
};

} // namespace sdk

#endif // ISDK_CPATHQUERYCOMPONENT_HPP

