// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPathAnimMotorUpdaterBase (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimMotorUpdaterBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPATHANIMMOTORUPDATERBASE_HPP
#define ISDK_CPATHANIMMOTORUPDATERBASE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CPathAnimMotorUpdaterBase {
    SCHEMA_CLASS("client.dll", "CPathAnimMotorUpdaterBase");

};

} // namespace sdk

#endif // ISDK_CPATHANIMMOTORUPDATERBASE_HPP

