// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPathSimple (runtime-resolved offsets)
// Module: client.dll
// Parent: C_BaseEntity
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPATHSIMPLE_HPP
#define ISDK_CPATHSIMPLE_HPP

#include "../schema_runtime.hpp"
#include "C_BaseEntity.hpp"

namespace sdk {

struct CPathSimple : C_BaseEntity {
    SCHEMA_CLASS("client.dll", "CPathSimple");


    // --- Virtual functions (vtable RVA: 0x1AD6DD8, 217 total) ---
};

} // namespace sdk

#endif // ISDK_CPATHSIMPLE_HPP

