// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPathAnimMotorUpdater (runtime-resolved offsets)
// Module: client.dll
// Parent: CPathAnimMotorUpdaterBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPATHANIMMOTORUPDATER_HPP
#define ISDK_CPATHANIMMOTORUPDATER_HPP

#include "../schema_runtime.hpp"
#include "CPathAnimMotorUpdaterBase.hpp"

namespace sdk {

struct CPathAnimMotorUpdater : CPathAnimMotorUpdaterBase {
    SCHEMA_CLASS("client.dll", "CPathAnimMotorUpdater");

};

} // namespace sdk

#endif // ISDK_CPATHANIMMOTORUPDATER_HPP

