// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPathHelperUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CUnaryUpdateNode
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPATHHELPERUPDATENODE_HPP
#define ISDK_CPATHHELPERUPDATENODE_HPP

#include "../schema_runtime.hpp"
#include "CUnaryUpdateNode.hpp"

namespace sdk {

struct CPathHelperUpdateNode : CUnaryUpdateNode {
    SCHEMA_CLASS("client.dll", "CPathHelperUpdateNode");

};

} // namespace sdk

#endif // ISDK_CPATHHELPERUPDATENODE_HPP

