// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPerParticleFloatInput (runtime-resolved offsets)
// Module: client.dll
// Parent: CParticleFloatInput
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPERPARTICLEFLOATINPUT_HPP
#define ISDK_CPERPARTICLEFLOATINPUT_HPP

#include "../schema_runtime.hpp"
#include "CParticleFloatInput.hpp"

namespace sdk {

struct CPerParticleFloatInput : CParticleFloatInput {
    SCHEMA_CLASS("client.dll", "CPerParticleFloatInput");

};

} // namespace sdk

#endif // ISDK_CPERPARTICLEFLOATINPUT_HPP

