// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPhysicsShake (runtime-resolved offsets)
// Module: client.dll
// Parent: IMotionEvent
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPHYSICSSHAKE_HPP
#define ISDK_CPHYSICSSHAKE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CPhysicsShake {
    SCHEMA_CLASS("client.dll", "CPhysicsShake");

};

} // namespace sdk

#endif // ISDK_CPHYSICSSHAKE_HPP

