// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPlayerPawnComponent (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPLAYERPAWNCOMPONENT_HPP
#define ISDK_CPLAYERPAWNCOMPONENT_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CPlayerPawnComponent {
    SCHEMA_CLASS("client.dll", "CPlayerPawnComponent");


    // --- Virtual functions (vtable RVA: 0x1AA8C78, 30 total) ---
};

} // namespace sdk

#endif // ISDK_CPLAYERPAWNCOMPONENT_HPP

