// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPlayerInputAnimMotorUpdater (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimMotorUpdaterBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPLAYERINPUTANIMMOTORUPDATER_HPP
#define ISDK_CPLAYERINPUTANIMMOTORUPDATER_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CPlayerInputAnimMotorUpdater {
    SCHEMA_CLASS("client.dll", "CPlayerInputAnimMotorUpdater");

};

} // namespace sdk

#endif // ISDK_CPLAYERINPUTANIMMOTORUPDATER_HPP

