// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPlayer_WaterServices (runtime-resolved offsets)
// Module: client.dll
// Parent: CPlayerPawnComponent
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPLAYER_WATERSERVICES_HPP
#define ISDK_CPLAYER_WATERSERVICES_HPP

#include "../schema_runtime.hpp"
#include "CPlayerPawnComponent.hpp"

namespace sdk {

struct CPlayer_WaterServices : CPlayerPawnComponent {
    SCHEMA_CLASS("client.dll", "CPlayer_WaterServices");


    // --- Virtual functions (vtable RVA: 0x1ADAA20, 31 total) ---
};

} // namespace sdk

#endif // ISDK_CPLAYER_WATERSERVICES_HPP

