// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPointOrient (runtime-resolved offsets)
// Module: client.dll
// Parent: C_BaseEntity
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPOINTORIENT_HPP
#define ISDK_CPOINTORIENT_HPP

#include "../schema_runtime.hpp"
#include "C_BaseEntity.hpp"

namespace sdk {

struct CPointOrient : C_BaseEntity {
    SCHEMA_CLASS("client.dll", "CPointOrient");


    // --- Virtual functions (vtable RVA: 0x1993918, 215 total) ---
};

} // namespace sdk

#endif // ISDK_CPOINTORIENT_HPP

