// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPointOffScreenIndicatorUi (runtime-resolved offsets)
// Module: client.dll
// Parent: C_PointClientUIWorldPanel
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPOINTOFFSCREENINDICATORUI_HPP
#define ISDK_CPOINTOFFSCREENINDICATORUI_HPP

#include "../schema_runtime.hpp"
#include "C_PointClientUIWorldPanel.hpp"

namespace sdk {

struct CPointOffScreenIndicatorUi : C_PointClientUIWorldPanel {
    SCHEMA_CLASS("client.dll", "CPointOffScreenIndicatorUi");


    // --- Virtual functions (vtable RVA: 0x1973450, 266 total) ---
    VFUNC_RAW(253);                                         // sig: 48 89 5C 24 18 57 48 83 EC 20 48 8B F9 4... reads: 0x10, 0xFD8
    VFUNC_RAW(254);                                         // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(256);                                         // sig: 40 53 48 83 EC 20 48 8B DA E8 ? ? ? ? F2...
    VFUNC_RAW(257);                                         // sig: 0F B6 81 A8 11 00 00 C3 CC CC CC CC CC C... reads: 0x11A8
    VFUNC_RAW(258);                                         // sig: 48 89 5C 24 08 57 48 83 EC 20 48 8B FA 4... reads: 0x52C
    VFUNC_RAW(259);                                         // sig: 48 8B C4 55 56 41 57 48 8D A8 D8 FD FF F... reads: 0x1010, 0x11B4, 0x11B8...
    VFUNC_RAW(260);                                         // sig: 48 89 5C 24 08 48 89 74 24 10 57 48 83 E... reads: 0x10, 0x1088
    VFUNC_RAW(261);                                         // sig: 40 53 48 83 EC 20 F3 0F 10 0D 52 0C 7E 0...
    VFUNC_RAW(262);                                         // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(263);                                         // sig: 40 55 41 54 48 8D AC 24 A8 FD FF FF 48 8...
    VFUNC_RAW(265);                                         // sig: 48 81 EC 38 02 00 00 48 89 91 80 11 00 0... reads: 0x1180
};

} // namespace sdk

#endif // ISDK_CPOINTOFFSCREENINDICATORUI_HPP

