// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPointConstraint (runtime-resolved offsets)
// Module: client.dll
// Parent: CBaseConstraint
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPOINTCONSTRAINT_HPP
#define ISDK_CPOINTCONSTRAINT_HPP

#include "../schema_runtime.hpp"
#include "CBaseConstraint.hpp"

namespace sdk {

struct CPointConstraint : CBaseConstraint {
    SCHEMA_CLASS("client.dll", "CPointConstraint");

};

} // namespace sdk

#endif // ISDK_CPOINTCONSTRAINT_HPP

