// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPointChildModifier (runtime-resolved offsets)
// Module: client.dll
// Parent: C_PointEntity
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPOINTCHILDMODIFIER_HPP
#define ISDK_CPOINTCHILDMODIFIER_HPP

#include "../schema_runtime.hpp"
#include "C_PointEntity.hpp"

namespace sdk {

struct CPointChildModifier : C_PointEntity {
    SCHEMA_CLASS("client.dll", "CPointChildModifier");


    // --- Virtual functions (vtable RVA: 0x1993238, 215 total) ---
};

} // namespace sdk

#endif // ISDK_CPOINTCHILDMODIFIER_HPP

