// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPrecipitationVData (runtime-resolved offsets)
// Module: client.dll
// Parent: CEntitySubclassVDataBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPRECIPITATIONVDATA_HPP
#define ISDK_CPRECIPITATIONVDATA_HPP

#include "../schema_runtime.hpp"
#include "CEntitySubclassVDataBase.hpp"

namespace sdk {

struct CPrecipitationVData : CEntitySubclassVDataBase {
    SCHEMA_CLASS("client.dll", "CPrecipitationVData");


    // --- Virtual functions (vtable RVA: 0x199FD00, 6 total) ---
};

} // namespace sdk

#endif // ISDK_CPRECIPITATIONVDATA_HPP

