// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPropDataComponent (runtime-resolved offsets)
// Module: client.dll
// Parent: CEntityComponent
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPROPDATACOMPONENT_HPP
#define ISDK_CPROPDATACOMPONENT_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CPropDataComponent {
    SCHEMA_CLASS("client.dll", "CPropDataComponent");


    // --- Virtual functions (vtable RVA: 0x1995D88, 7 total) ---
    VFUNC_RAW(0);                                           // sig: 40 53 48 83 EC 20 48 8B DA 48 8D 15 ? ? ...
    VFUNC_RAW(2);                                           // sig: 48 8B 05 ? ? ? ? C3 CC CC CC CC CC CC CC...
    VFUNC_RAW(3);                                           // sig: E9 ? ? ? ? CC CC CC CC CC CC CC CC CC CC...
    VFUNC_RAW(4);                                           // sig: 4C 8D 05 ? ? ? ? E9 ? ? ? ? CC CC CC CC ...
    VFUNC_RAW(5);                                           // sig: E9 ? ? ? ? CC CC CC CC CC CC CC CC CC CC...
};

} // namespace sdk

#endif // ISDK_CPROPDATACOMPONENT_HPP

