// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPulseCell_WaitForCursorsWithTagBase (runtime-resolved offsets)
// Module: client.dll
// Parent: CPulseCell_BaseYieldingInflow
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPULSECELL_WAITFORCURSORSWITHTAGBASE_HPP
#define ISDK_CPULSECELL_WAITFORCURSORSWITHTAGBASE_HPP

#include "../schema_runtime.hpp"
#include "CPulseCell_BaseYieldingInflow.hpp"

namespace sdk {

struct CPulseCell_WaitForCursorsWithTagBase : CPulseCell_BaseYieldingInflow {
    SCHEMA_CLASS("client.dll", "CPulseCell_WaitForCursorsWithTagBase");


    // --- Virtual functions (vtable RVA: 0x1CC7DF0, 27 total) ---
};

} // namespace sdk

#endif // ISDK_CPULSECELL_WAITFORCURSORSWITHTAGBASE_HPP

