// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPulseGameBlackboard (runtime-resolved offsets)
// Module: client.dll
// Parent: C_BaseEntity
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPULSEGAMEBLACKBOARD_HPP
#define ISDK_CPULSEGAMEBLACKBOARD_HPP

#include "../schema_runtime.hpp"
#include "C_BaseEntity.hpp"

namespace sdk {

struct CPulseGameBlackboard : C_BaseEntity {
    SCHEMA_CLASS("client.dll", "CPulseGameBlackboard");


    // --- Virtual functions (vtable RVA: 0x1A48248, 215 total) ---
};

} // namespace sdk

#endif // ISDK_CPULSEGAMEBLACKBOARD_HPP

