// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPulseCell_LimitCount (runtime-resolved offsets)
// Module: client.dll
// Parent: CPulseCell_BaseRequirement
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPULSECELL_LIMITCOUNT_HPP
#define ISDK_CPULSECELL_LIMITCOUNT_HPP

#include "../schema_runtime.hpp"
#include "CPulseCell_BaseRequirement.hpp"

namespace sdk {

struct CPulseCell_LimitCount : CPulseCell_BaseRequirement {
    SCHEMA_CLASS("client.dll", "CPulseCell_LimitCount");


    // --- Virtual functions (vtable RVA: 0x1CC5478, 15 total) ---
};

} // namespace sdk

#endif // ISDK_CPULSECELL_LIMITCOUNT_HPP

