// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPulseCell_Value_RandomInt (runtime-resolved offsets)
// Module: client.dll
// Parent: CPulseCell_BaseValue
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPULSECELL_VALUE_RANDOMINT_HPP
#define ISDK_CPULSECELL_VALUE_RANDOMINT_HPP

#include "../schema_runtime.hpp"
#include "CPulseCell_BaseValue.hpp"

namespace sdk {

struct CPulseCell_Value_RandomInt : CPulseCell_BaseValue {
    SCHEMA_CLASS("client.dll", "CPulseCell_Value_RandomInt");


    // --- Virtual functions (vtable RVA: 0x1CBEB70, 12 total) ---
};

} // namespace sdk

#endif // ISDK_CPULSECELL_VALUE_RANDOMINT_HPP

