// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPulseCell_Inflow_BaseEntrypoint (runtime-resolved offsets)
// Module: client.dll
// Parent: CPulseCell_BaseFlow
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPULSECELL_INFLOW_BASEENTRYPOINT_HPP
#define ISDK_CPULSECELL_INFLOW_BASEENTRYPOINT_HPP

#include "../schema_runtime.hpp"
#include "CPulseCell_BaseFlow.hpp"

namespace sdk {

struct CPulseCell_Inflow_BaseEntrypoint : CPulseCell_BaseFlow {
    SCHEMA_CLASS("client.dll", "CPulseCell_Inflow_BaseEntrypoint");


    // --- Virtual functions (vtable RVA: 0x1CBE568, 12 total) ---
};

} // namespace sdk

#endif // ISDK_CPULSECELL_INFLOW_BASEENTRYPOINT_HPP

