// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPulseCell_Unknown (runtime-resolved offsets)
// Module: client.dll
// Parent: CPulseCell_Base
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPULSECELL_UNKNOWN_HPP
#define ISDK_CPULSECELL_UNKNOWN_HPP

#include "../schema_runtime.hpp"
#include "CPulseCell_Base.hpp"

namespace sdk {

struct CPulseCell_Unknown : CPulseCell_Base {
    SCHEMA_CLASS("client.dll", "CPulseCell_Unknown");


    // --- Virtual functions (vtable RVA: 0x1CBED70, 12 total) ---
    VFUNC_RAW(0);                                           // sig: 40 53 48 83 EC 20 48 8B DA 48 8D 15 ? ? ...
    VFUNC_RAW(1);                                           // sig: 48 89 5C 24 08 57 48 83 EC 20 48 8B FA 4... reads: 0x48
    VFUNC_RAW(2);                                           // sig: 48 89 5C 24 08 57 48 83 EC 30 48 8B FA 4... reads: 0x48
    VFUNC_RAW(4);                                           // sig: 40 53 48 83 EC 30 48 8B 01 48 8D 54 24 4...
    VFUNC_RAW(5);                                           // sig: 40 53 48 83 EC 20 48 8B 01 48 8B DA 48 8...
    VFUNC_RAW(6);                                           // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(7);                                           // sig: 48 C7 02 00 00 00 00 48 8B C2 48 C7 42 0...
    VFUNC_RAW(8);                                           // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(9);                                           // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(10);                                          // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(11);                                          // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
};

} // namespace sdk

#endif // ISDK_CPULSECELL_UNKNOWN_HPP

