// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPulseCell_BaseRequirement (runtime-resolved offsets)
// Module: client.dll
// Parent: CPulseCell_Base
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPULSECELL_BASEREQUIREMENT_HPP
#define ISDK_CPULSECELL_BASEREQUIREMENT_HPP

#include "../schema_runtime.hpp"
#include "CPulseCell_Base.hpp"

namespace sdk {

struct CPulseCell_BaseRequirement : CPulseCell_Base {
    SCHEMA_CLASS("client.dll", "CPulseCell_BaseRequirement");


    // --- Virtual functions (vtable RVA: 0x1CBE4E8, 15 total) ---
};

} // namespace sdk

#endif // ISDK_CPULSECELL_BASEREQUIREMENT_HPP

