// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPulseCell_Inflow_Method (runtime-resolved offsets)
// Module: client.dll
// Parent: CPulseCell_Inflow_BaseEntrypoint
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPULSECELL_INFLOW_METHOD_HPP
#define ISDK_CPULSECELL_INFLOW_METHOD_HPP

#include "../schema_runtime.hpp"
#include "CPulseCell_Inflow_BaseEntrypoint.hpp"

namespace sdk {

struct CPulseCell_Inflow_Method : CPulseCell_Inflow_BaseEntrypoint {
    SCHEMA_CLASS("client.dll", "CPulseCell_Inflow_Method");


    // --- Virtual functions (vtable RVA: 0x1CBE5D0, 12 total) ---
};

} // namespace sdk

#endif // ISDK_CPULSECELL_INFLOW_METHOD_HPP

