// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPulseCell_Outflow_CycleRandom (runtime-resolved offsets)
// Module: client.dll
// Parent: CPulseCell_BaseFlow
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPULSECELL_OUTFLOW_CYCLERANDOM_HPP
#define ISDK_CPULSECELL_OUTFLOW_CYCLERANDOM_HPP

#include "../schema_runtime.hpp"
#include "CPulseCell_BaseFlow.hpp"

namespace sdk {

struct CPulseCell_Outflow_CycleRandom : CPulseCell_BaseFlow {
    SCHEMA_CLASS("client.dll", "CPulseCell_Outflow_CycleRandom");


    // --- Virtual functions (vtable RVA: 0x1CBEAA0, 12 total) ---
    VFUNC_RAW(10);                                          // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(11);                                          // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
};

} // namespace sdk

#endif // ISDK_CPULSECELL_OUTFLOW_CYCLERANDOM_HPP

