// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPulseCell_Value_Curve (runtime-resolved offsets)
// Module: client.dll
// Parent: CPulseCell_BaseValue
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPULSECELL_VALUE_CURVE_HPP
#define ISDK_CPULSECELL_VALUE_CURVE_HPP

#include "../schema_runtime.hpp"
#include "CPulseCell_BaseValue.hpp"

namespace sdk {

struct CPulseCell_Value_Curve : CPulseCell_BaseValue {
    SCHEMA_CLASS("client.dll", "CPulseCell_Value_Curve");


    // --- Virtual functions (vtable RVA: 0x1CC6478, 12 total) ---
};

} // namespace sdk

#endif // ISDK_CPULSECELL_VALUE_CURVE_HPP

