// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPulseCell_Base (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPULSECELL_BASE_HPP
#define ISDK_CPULSECELL_BASE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CPulseCell_Base {
    SCHEMA_CLASS("client.dll", "CPulseCell_Base");


    // --- Virtual functions (vtable RVA: 0x1992A10, 12 total) ---
};

} // namespace sdk

#endif // ISDK_CPULSECELL_BASE_HPP

