// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPulseCell_Outflow_CycleShuffled (runtime-resolved offsets)
// Module: client.dll
// Parent: CPulseCell_BaseFlow
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPULSECELL_OUTFLOW_CYCLESHUFFLED_HPP
#define ISDK_CPULSECELL_OUTFLOW_CYCLESHUFFLED_HPP

#include "../schema_runtime.hpp"
#include "CPulseCell_BaseFlow.hpp"

namespace sdk {

struct CPulseCell_Outflow_CycleShuffled : CPulseCell_BaseFlow {
    SCHEMA_CLASS("client.dll", "CPulseCell_Outflow_CycleShuffled");


    // --- Virtual functions (vtable RVA: 0x1CBEB08, 12 total) ---
};

} // namespace sdk

#endif // ISDK_CPULSECELL_OUTFLOW_CYCLESHUFFLED_HPP

