// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPulseCell_BaseValue (runtime-resolved offsets)
// Module: client.dll
// Parent: CPulseCell_Base
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPULSECELL_BASEVALUE_HPP
#define ISDK_CPULSECELL_BASEVALUE_HPP

#include "../schema_runtime.hpp"
#include "CPulseCell_Base.hpp"

namespace sdk {

struct CPulseCell_BaseValue : CPulseCell_Base {
    SCHEMA_CLASS("client.dll", "CPulseCell_BaseValue");


    // --- Virtual functions (vtable RVA: 0x1CBE7D8, 12 total) ---
};

} // namespace sdk

#endif // ISDK_CPULSECELL_BASEVALUE_HPP

