// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPulseCell_Inflow_Yield (runtime-resolved offsets)
// Module: client.dll
// Parent: CPulseCell_BaseYieldingInflow
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPULSECELL_INFLOW_YIELD_HPP
#define ISDK_CPULSECELL_INFLOW_YIELD_HPP

#include "../schema_runtime.hpp"
#include "CPulseCell_BaseYieldingInflow.hpp"

namespace sdk {

struct CPulseCell_Inflow_Yield : CPulseCell_BaseYieldingInflow {
    SCHEMA_CLASS("client.dll", "CPulseCell_Inflow_Yield");


    // --- Virtual functions (vtable RVA: 0x1CBE8A8, 24 total) ---
    VFUNC_RAW(17);                                          // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(19);                                          // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(22);                                          // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
};

} // namespace sdk

#endif // ISDK_CPULSECELL_INFLOW_YIELD_HPP

