// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPulseGraphDef (runtime-resolved offsets)
// Module: client.dll
// Parent: IPulseGraphDef
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPULSEGRAPHDEF_HPP
#define ISDK_CPULSEGRAPHDEF_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CPulseGraphDef {
    SCHEMA_CLASS("client.dll", "CPulseGraphDef");


    // --- Virtual functions (vtable RVA: 0x1CC0BC8, 23 total) ---
    VFUNC_RAW(0);                                           // sig: 45 33 C0 4C 89 02 48 8B 41 08 48 89 02 4...
    VFUNC_RAW(1);                                           // sig: 40 53 48 83 EC 20 48 8B DA 48 8D 51 18 4... reads: 0x18
    VFUNC_RAW(2);                                           // sig: 45 33 C0 4C 89 02 48 8B 41 30 48 89 02 4...
    VFUNC_RAW(3);                                           // sig: 4C 8B DC 49 89 53 10 55 49 8D 6B A1 48 8... reads: 0x110, 0x118
    VFUNC_RAW(4);                                           // sig: 48 89 54 24 10 48 89 4C 24 08 53 55 56 5... reads: 0x68, 0x70, 0x98...
    VFUNC_RAW(5);                                           // sig: 40 55 57 41 54 41 57 48 83 EC 28 48 8B A... reads: 0xF8, 0x100
    VFUNC_RAW(6);                                           // sig: 4C 8B C1 85 D2 74 02 78 1F 3B 91 98 00 0... reads: 0x98, 0xA0
    VFUNC_RAW(7);                                           // sig: 0F 10 81 40 01 00 00 48 8B C2 0F 11 02 C... reads: 0x140
    VFUNC_RAW(8);                                           // sig: 48 89 4C 24 08 55 53 56 57 41 54 41 55 4... reads: 0x8, 0x30
    VFUNC_RAW(9);                                           // sig: 8B 81 80 00 00 00 89 02 48 8B C2 C3 CC C... reads: 0x80
    VFUNC_RAW(10);                                          // sig: 48 89 5C 24 08 8B 81 80 00 00 00 4C 8B D... reads: 0x80
    VFUNC_RAW(11);                                          // sig: 48 8B C4 48 89 58 08 48 89 68 10 48 89 7...
    VFUNC_RAW(12);                                          // sig: 4C 8B C1 85 D2 74 02 78 22 3B 91 80 00 0... reads: 0x80, 0x88
    VFUNC_RAW(13);                                          // sig: 4C 8B C1 85 D2 74 02 78 1F 3B 91 80 00 0... reads: 0x80, 0x88
    VFUNC_RAW(14);                                          // sig: 4C 8B C1 85 D2 74 02 78 1F 3B 91 80 00 0... reads: 0x80
    VFUNC_RAW(15);                                          // sig: 4C 8B C1 85 D2 74 02 78 2E 3B 91 80 00 0... reads: 0x80, 0x88
    VFUNC_RAW(16);                                          // sig: 4C 8B C9 45 85 C0 74 02 78 25 44 3B 81 8... reads: 0x80, 0x88
    VFUNC_RAW(17);                                          // sig: 4C 8B C1 85 D2 74 02 78 20 3B 91 80 00 0... reads: 0x80, 0x88
    VFUNC_RAW(18);                                          // sig: 4C 8B C1 85 D2 74 02 78 20 3B 91 80 00 0... reads: 0x80, 0x88
    VFUNC_RAW(19);                                          // sig: 48 89 5C 24 08 57 48 83 EC 20 65 48 8B 0...
    VFUNC_RAW(20);                                          // sig: 40 53 56 57 41 54 41 56 48 83 EC 20 49 8...
    VFUNC_RAW(21);                                          // sig: 40 53 48 83 EC 20 48 8B DA 48 8D 15 ? ? ...
    VFUNC_RAW(22);                                          // sig: 48 89 5C 24 10 48 89 6C 24 20 56 57 41 5... reads: 0x68, 0x70
};

} // namespace sdk

#endif // ISDK_CPULSEGRAPHDEF_HPP

