// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPulseCell_Step_DebugLog (runtime-resolved offsets)
// Module: client.dll
// Parent: CPulseCell_BaseFlow
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPULSECELL_STEP_DEBUGLOG_HPP
#define ISDK_CPULSECELL_STEP_DEBUGLOG_HPP

#include "../schema_runtime.hpp"
#include "CPulseCell_BaseFlow.hpp"

namespace sdk {

struct CPulseCell_Step_DebugLog : CPulseCell_BaseFlow {
    SCHEMA_CLASS("client.dll", "CPulseCell_Step_DebugLog");


    // --- Virtual functions (vtable RVA: 0x1CBEC40, 12 total) ---
};

} // namespace sdk

#endif // ISDK_CPULSECELL_STEP_DEBUGLOG_HPP

