// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPulseCell_Inflow_Wait (runtime-resolved offsets)
// Module: client.dll
// Parent: CPulseCell_BaseYieldingInflow
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPULSECELL_INFLOW_WAIT_HPP
#define ISDK_CPULSECELL_INFLOW_WAIT_HPP

#include "../schema_runtime.hpp"
#include "CPulseCell_BaseYieldingInflow.hpp"

namespace sdk {

struct CPulseCell_Inflow_Wait : CPulseCell_BaseYieldingInflow {
    SCHEMA_CLASS("client.dll", "CPulseCell_Inflow_Wait");


    // --- Virtual functions (vtable RVA: 0x1CBE970, 24 total) ---
};

} // namespace sdk

#endif // ISDK_CPULSECELL_INFLOW_WAIT_HPP

