// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPulseExecCursor (runtime-resolved offsets)
// Module: client.dll
// Parent: IPulseExecLog
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPULSEEXECCURSOR_HPP
#define ISDK_CPULSEEXECCURSOR_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CPulseExecCursor {
    SCHEMA_CLASS("client.dll", "CPulseExecCursor");


    // --- Virtual functions (vtable RVA: 0x1CBEEE0, 11 total) ---
    VFUNC_RAW(0);                                           // sig: 48 8B C4 48 89 50 10 4C 89 40 18 4C 89 4...
    VFUNC_RAW(1);                                           // sig: 48 8B C4 48 89 50 10 4C 89 40 18 4C 89 4...
    VFUNC_RAW(2);                                           // sig: 40 53 48 83 EC 20 48 8B DA E8 ? ? ? ? 48...
    VFUNC_RAW(3);                                           // sig: 48 89 5C 24 08 57 48 83 EC 20 8B DA 48 8...
    VFUNC_RAW(4);                                           // sig: 48 89 5C 24 10 48 89 74 24 18 48 89 7C 2... reads: 0xC8
    VFUNC_RAW(5);                                           // sig: 48 89 5C 24 10 55 56 57 41 54 41 55 41 5... reads: 0xC8
    VFUNC_RAW(6);                                           // sig: 48 89 5C 24 08 48 89 6C 24 10 48 89 74 2... reads: 0x20, 0xC0, 0xCC
    VFUNC_RAW(7);                                           // sig: 48 89 5C 24 08 57 48 83 EC 40 48 8B FA 4... reads: 0x20, 0xC0, 0xCC
    VFUNC_RAW(8);                                           // sig: 48 8B 41 20 48 8B D1 48 8B 08 48 8B 01 4... reads: 0x20
    VFUNC_RAW(9);                                           // sig: 40 53 48 83 EC 20 33 C0 C7 44 24 30 00 0...
    VFUNC_RAW(10);                                          // sig: 48 83 EC 28 B9 08 00 00 00 E8 ? ? ? ? 48...
};

} // namespace sdk

#endif // ISDK_CPULSEEXECCURSOR_HPP

