// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPulseCell_BaseFlow (runtime-resolved offsets)
// Module: client.dll
// Parent: CPulseCell_Base
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPULSECELL_BASEFLOW_HPP
#define ISDK_CPULSECELL_BASEFLOW_HPP

#include "../schema_runtime.hpp"
#include "CPulseCell_Base.hpp"

namespace sdk {

struct CPulseCell_BaseFlow : CPulseCell_Base {
    SCHEMA_CLASS("client.dll", "CPulseCell_BaseFlow");


    // --- Virtual functions (vtable RVA: 0x1992A88, 12 total) ---
};

} // namespace sdk

#endif // ISDK_CPULSECELL_BASEFLOW_HPP

