// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CPulseCell_InlineNodeSkipSelector (runtime-resolved offsets)
// Module: client.dll
// Parent: CPulseCell_BaseFlow
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPULSECELL_INLINENODESKIPSELECTOR_HPP
#define ISDK_CPULSECELL_INLINENODESKIPSELECTOR_HPP

#include "../schema_runtime.hpp"
#include "CPulseCell_BaseFlow.hpp"

namespace sdk {

struct CPulseCell_InlineNodeSkipSelector : CPulseCell_BaseFlow {
    SCHEMA_CLASS("client.dll", "CPulseCell_InlineNodeSkipSelector");


    // --- Virtual functions (vtable RVA: 0x1CC5578, 12 total) ---
};

} // namespace sdk

#endif // ISDK_CPULSECELL_INLINENODESKIPSELECTOR_HPP

