// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CQuaternionAnimParameter (runtime-resolved offsets)
// Module: client.dll
// Parent: CConcreteAnimParameter
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CQUATERNIONANIMPARAMETER_HPP
#define ISDK_CQUATERNIONANIMPARAMETER_HPP

#include "../schema_runtime.hpp"
#include "CConcreteAnimParameter.hpp"

namespace sdk {

struct CQuaternionAnimParameter : CConcreteAnimParameter {
    SCHEMA_CLASS("client.dll", "CQuaternionAnimParameter");

};

} // namespace sdk

#endif // ISDK_CQUATERNIONANIMPARAMETER_HPP

