// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CRagdollUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CUnaryUpdateNode
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CRAGDOLLUPDATENODE_HPP
#define ISDK_CRAGDOLLUPDATENODE_HPP

#include "../schema_runtime.hpp"
#include "CUnaryUpdateNode.hpp"

namespace sdk {

struct CRagdollUpdateNode : CUnaryUpdateNode {
    SCHEMA_CLASS("client.dll", "CRagdollUpdateNode");

};

} // namespace sdk

#endif // ISDK_CRAGDOLLUPDATENODE_HPP

