// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CRagdollManager (runtime-resolved offsets)
// Module: client.dll
// Parent: C_BaseEntity
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CRAGDOLLMANAGER_HPP
#define ISDK_CRAGDOLLMANAGER_HPP

#include "../schema_runtime.hpp"
#include "C_BaseEntity.hpp"

namespace sdk {

struct CRagdollManager : C_BaseEntity {
    SCHEMA_CLASS("client.dll", "CRagdollManager");


    // --- Virtual functions (vtable RVA: 0x1996C38, 215 total) ---
};

} // namespace sdk

#endif // ISDK_CRAGDOLLMANAGER_HPP

