// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CRagdollAnimTag (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimTagBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CRAGDOLLANIMTAG_HPP
#define ISDK_CRAGDOLLANIMTAG_HPP

#include "../schema_runtime.hpp"
#include "CAnimTagBase.hpp"

namespace sdk {

struct CRagdollAnimTag : CAnimTagBase {
    SCHEMA_CLASS("client.dll", "CRagdollAnimTag");

};

} // namespace sdk

#endif // ISDK_CRAGDOLLANIMTAG_HPP

