// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CRagdollComponentUpdater (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimComponentUpdater
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CRAGDOLLCOMPONENTUPDATER_HPP
#define ISDK_CRAGDOLLCOMPONENTUPDATER_HPP

#include "../schema_runtime.hpp"
#include "CAnimComponentUpdater.hpp"

namespace sdk {

struct CRagdollComponentUpdater : CAnimComponentUpdater {
    SCHEMA_CLASS("client.dll", "CRagdollComponentUpdater");

};

} // namespace sdk

#endif // ISDK_CRAGDOLLCOMPONENTUPDATER_HPP

