// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CRemapValueComponentUpdater (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimComponentUpdater
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CREMAPVALUECOMPONENTUPDATER_HPP
#define ISDK_CREMAPVALUECOMPONENTUPDATER_HPP

#include "../schema_runtime.hpp"
#include "CAnimComponentUpdater.hpp"

namespace sdk {

struct CRemapValueComponentUpdater : CAnimComponentUpdater {
    SCHEMA_CLASS("client.dll", "CRemapValueComponentUpdater");

};

} // namespace sdk

#endif // ISDK_CREMAPVALUECOMPONENTUPDATER_HPP

