// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CRenderMesh (runtime-resolved offsets)
// Module: client.dll
// Parent: ?$CRefCounted@V?$CRefCountServiceBase@VCRefMT
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CRENDERMESH_HPP
#define ISDK_CRENDERMESH_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CRenderMesh {
    SCHEMA_CLASS("client.dll", "CRenderMesh");

};

} // namespace sdk

#endif // ISDK_CRENDERMESH_HPP

