// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CResponseCriteriaSet (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CRESPONSECRITERIASET_HPP
#define ISDK_CRESPONSECRITERIASET_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CResponseCriteriaSet {
    SCHEMA_CLASS("client.dll", "CResponseCriteriaSet");

};

} // namespace sdk

#endif // ISDK_CRESPONSECRITERIASET_HPP

