// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CRootUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CUnaryUpdateNode
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CROOTUPDATENODE_HPP
#define ISDK_CROOTUPDATENODE_HPP

#include "../schema_runtime.hpp"
#include "CUnaryUpdateNode.hpp"

namespace sdk {

struct CRootUpdateNode : CUnaryUpdateNode {
    SCHEMA_CLASS("client.dll", "CRootUpdateNode");

};

} // namespace sdk

#endif // ISDK_CROOTUPDATENODE_HPP

