// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CScriptUniformRandomStream (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CSCRIPTUNIFORMRANDOMSTREAM_HPP
#define ISDK_CSCRIPTUNIFORMRANDOMSTREAM_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CScriptUniformRandomStream {
    SCHEMA_CLASS("client.dll", "CScriptUniformRandomStream");


    // --- Virtual functions (vtable RVA: 0x19B7FF0, 3 total) ---
};

} // namespace sdk

#endif // ISDK_CSCRIPTUNIFORMRANDOMSTREAM_HPP

