// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CScriptComponent (runtime-resolved offsets)
// Module: client.dll
// Parent: CEntityComponent
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CSCRIPTCOMPONENT_HPP
#define ISDK_CSCRIPTCOMPONENT_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CScriptComponent {
    SCHEMA_CLASS("client.dll", "CScriptComponent");


    // --- Virtual functions (vtable RVA: 0x1C284F0, 7 total) ---
    VFUNC_RAW(0);                                           // sig: 40 53 48 83 EC 20 48 8B DA E8 ? ? ? ? 48...
    VFUNC_RAW(2);                                           // sig: 48 8B 05 ? ? ? ? C3 CC CC CC CC CC CC CC...
    VFUNC_RAW(3);                                           // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(4);                                           // sig: 48 81 EC B8 01 00 00 48 83 BA 40 01 00 0...
    VFUNC_RAW(5);                                           // sig: E9 ? ? ? ? CC CC CC CC CC CC CC CC CC CC...
};

} // namespace sdk

#endif // ISDK_CSCRIPTCOMPONENT_HPP

