// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CSequenceFinishedAnimTag (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimTagBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CSEQUENCEFINISHEDANIMTAG_HPP
#define ISDK_CSEQUENCEFINISHEDANIMTAG_HPP

#include "../schema_runtime.hpp"
#include "CAnimTagBase.hpp"

namespace sdk {

struct CSequenceFinishedAnimTag : CAnimTagBase {
    SCHEMA_CLASS("client.dll", "CSequenceFinishedAnimTag");

};

} // namespace sdk

#endif // ISDK_CSEQUENCEFINISHEDANIMTAG_HPP

