// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CSequenceUpdateNodeBase (runtime-resolved offsets)
// Module: client.dll
// Parent: CLeafUpdateNode
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CSEQUENCEUPDATENODEBASE_HPP
#define ISDK_CSEQUENCEUPDATENODEBASE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CSequenceUpdateNodeBase {
    SCHEMA_CLASS("client.dll", "CSequenceUpdateNodeBase");

};

} // namespace sdk

#endif // ISDK_CSEQUENCEUPDATENODEBASE_HPP

