// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CSequenceUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CSequenceUpdateNodeBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CSEQUENCEUPDATENODE_HPP
#define ISDK_CSEQUENCEUPDATENODE_HPP

#include "../schema_runtime.hpp"
#include "CSequenceUpdateNodeBase.hpp"

namespace sdk {

struct CSequenceUpdateNode : CSequenceUpdateNodeBase {
    SCHEMA_CLASS("client.dll", "CSequenceUpdateNode");

};

} // namespace sdk

#endif // ISDK_CSEQUENCEUPDATENODE_HPP

