// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CSetParameterActionUpdater (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimActionUpdater
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CSETPARAMETERACTIONUPDATER_HPP
#define ISDK_CSETPARAMETERACTIONUPDATER_HPP

#include "../schema_runtime.hpp"
#include "CAnimActionUpdater.hpp"

namespace sdk {

struct CSetParameterActionUpdater : CAnimActionUpdater {
    SCHEMA_CLASS("client.dll", "CSetParameterActionUpdater");

};

} // namespace sdk

#endif // ISDK_CSETPARAMETERACTIONUPDATER_HPP

