// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CShatterGlassShard (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CSHATTERGLASSSHARD_HPP
#define ISDK_CSHATTERGLASSSHARD_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CShatterGlassShard {
    SCHEMA_CLASS("client.dll", "CShatterGlassShard");

};

} // namespace sdk

#endif // ISDK_CSHATTERGLASSSHARD_HPP

