// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CSingleFrameUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CLeafUpdateNode
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CSINGLEFRAMEUPDATENODE_HPP
#define ISDK_CSINGLEFRAMEUPDATENODE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CSingleFrameUpdateNode {
    SCHEMA_CLASS("client.dll", "CSingleFrameUpdateNode");

};

} // namespace sdk

#endif // ISDK_CSINGLEFRAMEUPDATENODE_HPP

