// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CSkeletonAnimationController (runtime-resolved offsets)
// Module: client.dll
// Parent: ISkeletonAnimationController
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CSKELETONANIMATIONCONTROLLER_HPP
#define ISDK_CSKELETONANIMATIONCONTROLLER_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CSkeletonAnimationController {
    SCHEMA_CLASS("client.dll", "CSkeletonAnimationController");


    // --- Virtual functions (vtable RVA: 0x1ADFAA8, 34 total) ---
};

} // namespace sdk

#endif // ISDK_CSKELETONANIMATIONCONTROLLER_HPP

