// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CSkeletonInstance (runtime-resolved offsets)
// Module: client.dll
// Parent: CGameSceneNode
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CSKELETONINSTANCE_HPP
#define ISDK_CSKELETONINSTANCE_HPP

#include "../schema_runtime.hpp"
#include "CGameSceneNode.hpp"

namespace sdk {

struct CSkeletonInstance : CGameSceneNode {
    SCHEMA_CLASS("client.dll", "CSkeletonInstance");


    // --- Virtual functions (vtable RVA: 0x1ADF7F8, 32 total) ---
};

} // namespace sdk

#endif // ISDK_CSKELETONINSTANCE_HPP

