// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CSlopeComponentUpdater (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimComponentUpdater
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CSLOPECOMPONENTUPDATER_HPP
#define ISDK_CSLOPECOMPONENTUPDATER_HPP

#include "../schema_runtime.hpp"
#include "CAnimComponentUpdater.hpp"

namespace sdk {

struct CSlopeComponentUpdater : CAnimComponentUpdater {
    SCHEMA_CLASS("client.dll", "CSlopeComponentUpdater");

};

} // namespace sdk

#endif // ISDK_CSLOPECOMPONENTUPDATER_HPP

