// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CSlowDownOnSlopesUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CUnaryUpdateNode
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CSLOWDOWNONSLOPESUPDATENODE_HPP
#define ISDK_CSLOWDOWNONSLOPESUPDATENODE_HPP

#include "../schema_runtime.hpp"
#include "CUnaryUpdateNode.hpp"

namespace sdk {

struct CSlowDownOnSlopesUpdateNode : CUnaryUpdateNode {
    SCHEMA_CLASS("client.dll", "CSlowDownOnSlopesUpdateNode");

};

} // namespace sdk

#endif // ISDK_CSLOWDOWNONSLOPESUPDATENODE_HPP

