// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CSndSeqInstBaseSchema (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CSNDSEQINSTBASESCHEMA_HPP
#define ISDK_CSNDSEQINSTBASESCHEMA_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CSndSeqInstBaseSchema {
    SCHEMA_CLASS("client.dll", "CSndSeqInstBaseSchema");

};

} // namespace sdk

#endif // ISDK_CSNDSEQINSTBASESCHEMA_HPP

