// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CSndSeqInstruments (runtime-resolved offsets)
// Module: client.dll
// Parent: ISndSeqInstruments
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CSNDSEQINSTRUMENTS_HPP
#define ISDK_CSNDSEQINSTRUMENTS_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CSndSeqInstruments {
    SCHEMA_CLASS("client.dll", "CSndSeqInstruments");

};

} // namespace sdk

#endif // ISDK_CSNDSEQINSTRUMENTS_HPP

