// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CSndSeqInstMidiSampler (runtime-resolved offsets)
// Module: client.dll
// Parent: CSndSeqInstBaseSchema
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CSNDSEQINSTMIDISAMPLER_HPP
#define ISDK_CSNDSEQINSTMIDISAMPLER_HPP

#include "../schema_runtime.hpp"
#include "CSndSeqInstBaseSchema.hpp"

namespace sdk {

struct CSndSeqInstMidiSampler : CSndSeqInstBaseSchema {
    SCHEMA_CLASS("client.dll", "CSndSeqInstMidiSampler");

};

} // namespace sdk

#endif // ISDK_CSNDSEQINSTMIDISAMPLER_HPP

