// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CSndSeqInstSndEvtSchema (runtime-resolved offsets)
// Module: client.dll
// Parent: CSndSeqInstBaseSchema
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CSNDSEQINSTSNDEVTSCHEMA_HPP
#define ISDK_CSNDSEQINSTSNDEVTSCHEMA_HPP

#include "../schema_runtime.hpp"
#include "CSndSeqInstBaseSchema.hpp"

namespace sdk {

struct CSndSeqInstSndEvtSchema : CSndSeqInstBaseSchema {
    SCHEMA_CLASS("client.dll", "CSndSeqInstSndEvtSchema");

};

} // namespace sdk

#endif // ISDK_CSNDSEQINSTSNDEVTSCHEMA_HPP

