// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CSolveIKChainUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CUnaryUpdateNode
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CSOLVEIKCHAINUPDATENODE_HPP
#define ISDK_CSOLVEIKCHAINUPDATENODE_HPP

#include "../schema_runtime.hpp"
#include "CUnaryUpdateNode.hpp"

namespace sdk {

struct CSolveIKChainUpdateNode : CUnaryUpdateNode {
    SCHEMA_CLASS("client.dll", "CSolveIKChainUpdateNode");

};

} // namespace sdk

#endif // ISDK_CSOLVEIKCHAINUPDATENODE_HPP

