// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CSosGroupActionMemberCountEnvelopeSchema (runtime-resolved offsets)
// Module: client.dll
// Parent: CSosGroupActionSchema
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CSOSGROUPACTIONMEMBERCOUNTENVELOPESCHEMA_HPP
#define ISDK_CSOSGROUPACTIONMEMBERCOUNTENVELOPESCHEMA_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CSosGroupActionMemberCountEnvelopeSchema {
    SCHEMA_CLASS("client.dll", "CSosGroupActionMemberCountEnvelopeSchema");

};

} // namespace sdk

#endif // ISDK_CSOSGROUPACTIONMEMBERCOUNTENVELOPESCHEMA_HPP

