// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CSosGroupActionSoundeventMinMaxValuesSchema (runtime-resolved offsets)
// Module: client.dll
// Parent: CSosGroupActionSchema
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CSOSGROUPACTIONSOUNDEVENTMINMAXVALUESSCHEMA_HPP
#define ISDK_CSOSGROUPACTIONSOUNDEVENTMINMAXVALUESSCHEMA_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CSosGroupActionSoundeventMinMaxValuesSchema {
    SCHEMA_CLASS("client.dll", "CSosGroupActionSoundeventMinMaxValuesSchema");

};

} // namespace sdk

#endif // ISDK_CSOSGROUPACTIONSOUNDEVENTMINMAXVALUESSCHEMA_HPP

