// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CSosGroupActionSoundeventCountSchema (runtime-resolved offsets)
// Module: client.dll
// Parent: CSosGroupActionSchema
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CSOSGROUPACTIONSOUNDEVENTCOUNTSCHEMA_HPP
#define ISDK_CSOSGROUPACTIONSOUNDEVENTCOUNTSCHEMA_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CSosGroupActionSoundeventCountSchema {
    SCHEMA_CLASS("client.dll", "CSosGroupActionSoundeventCountSchema");

};

} // namespace sdk

#endif // ISDK_CSOSGROUPACTIONSOUNDEVENTCOUNTSCHEMA_HPP

