// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CSosGroupActionOcclusionSchema (runtime-resolved offsets)
// Module: client.dll
// Parent: CSosGroupActionSchema
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CSOSGROUPACTIONOCCLUSIONSCHEMA_HPP
#define ISDK_CSOSGROUPACTIONOCCLUSIONSCHEMA_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CSosGroupActionOcclusionSchema {
    SCHEMA_CLASS("client.dll", "CSosGroupActionOcclusionSchema");

};

} // namespace sdk

#endif // ISDK_CSOSGROUPACTIONOCCLUSIONSCHEMA_HPP

