// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CSosGroupActionSetSoundeventParameterSchema (runtime-resolved offsets)
// Module: client.dll
// Parent: CSosGroupActionSchema
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CSOSGROUPACTIONSETSOUNDEVENTPARAMETERSCHEMA_HPP
#define ISDK_CSOSGROUPACTIONSETSOUNDEVENTPARAMETERSCHEMA_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CSosGroupActionSetSoundeventParameterSchema {
    SCHEMA_CLASS("client.dll", "CSosGroupActionSetSoundeventParameterSchema");

};

} // namespace sdk

#endif // ISDK_CSOSGROUPACTIONSETSOUNDEVENTPARAMETERSCHEMA_HPP

