// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CSosGroupActionSoundeventClusterSchema (runtime-resolved offsets)
// Module: client.dll
// Parent: CSosGroupActionSchema
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CSOSGROUPACTIONSOUNDEVENTCLUSTERSCHEMA_HPP
#define ISDK_CSOSGROUPACTIONSOUNDEVENTCLUSTERSCHEMA_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CSosGroupActionSoundeventClusterSchema {
    SCHEMA_CLASS("client.dll", "CSosGroupActionSoundeventClusterSchema");

};

} // namespace sdk

#endif // ISDK_CSOSGROUPACTIONSOUNDEVENTCLUSTERSCHEMA_HPP

