// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CSosGroupActionTimeLimitSchema (runtime-resolved offsets)
// Module: client.dll
// Parent: CSosGroupActionSchema
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CSOSGROUPACTIONTIMELIMITSCHEMA_HPP
#define ISDK_CSOSGROUPACTIONTIMELIMITSCHEMA_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CSosGroupActionTimeLimitSchema {
    SCHEMA_CLASS("client.dll", "CSosGroupActionTimeLimitSchema");

};

} // namespace sdk

#endif // ISDK_CSOSGROUPACTIONTIMELIMITSCHEMA_HPP

