// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CSosGroupActionSoundeventPrioritySchema (runtime-resolved offsets)
// Module: client.dll
// Parent: CSosGroupActionSchema
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CSOSGROUPACTIONSOUNDEVENTPRIORITYSCHEMA_HPP
#define ISDK_CSOSGROUPACTIONSOUNDEVENTPRIORITYSCHEMA_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CSosGroupActionSoundeventPrioritySchema {
    SCHEMA_CLASS("client.dll", "CSosGroupActionSoundeventPrioritySchema");

};

} // namespace sdk

#endif // ISDK_CSOSGROUPACTIONSOUNDEVENTPRIORITYSCHEMA_HPP

