// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CSpeedScaleUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CUnaryUpdateNode
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CSPEEDSCALEUPDATENODE_HPP
#define ISDK_CSPEEDSCALEUPDATENODE_HPP

#include "../schema_runtime.hpp"
#include "CUnaryUpdateNode.hpp"

namespace sdk {

struct CSpeedScaleUpdateNode : CUnaryUpdateNode {
    SCHEMA_CLASS("client.dll", "CSpeedScaleUpdateNode");

};

} // namespace sdk

#endif // ISDK_CSPEEDSCALEUPDATENODE_HPP

