// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CSPerRoundStats_t (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CSPERROUNDSTATS_T_HPP
#define ISDK_CSPERROUNDSTATS_T_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CSPerRoundStats_t {
    SCHEMA_CLASS("client.dll", "CSPerRoundStats_t");


    // --- Virtual functions (vtable RVA: 0x1A5CF50, 6 total) ---
};

} // namespace sdk

#endif // ISDK_CSPERROUNDSTATS_T_HPP

