// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CStaticPoseCache (runtime-resolved offsets)
// Module: client.dll
// Parent: ?$CMutableRefCounted@V?$CMutableRefCountBase@VCRefMT
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CSTATICPOSECACHE_HPP
#define ISDK_CSTATICPOSECACHE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CStaticPoseCache {
    SCHEMA_CLASS("client.dll", "CStaticPoseCache");

};

} // namespace sdk

#endif // ISDK_CSTATICPOSECACHE_HPP

