// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CStateMachineComponentUpdater (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimComponentUpdater
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CSTATEMACHINECOMPONENTUPDATER_HPP
#define ISDK_CSTATEMACHINECOMPONENTUPDATER_HPP

#include "../schema_runtime.hpp"
#include "CAnimComponentUpdater.hpp"

namespace sdk {

struct CStateMachineComponentUpdater : CAnimComponentUpdater {
    SCHEMA_CLASS("client.dll", "CStateMachineComponentUpdater");

};

} // namespace sdk

#endif // ISDK_CSTATEMACHINECOMPONENTUPDATER_HPP

