// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CStanceOverrideUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CUnaryUpdateNode
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CSTANCEOVERRIDEUPDATENODE_HPP
#define ISDK_CSTANCEOVERRIDEUPDATENODE_HPP

#include "../schema_runtime.hpp"
#include "CUnaryUpdateNode.hpp"

namespace sdk {

struct CStanceOverrideUpdateNode : CUnaryUpdateNode {
    SCHEMA_CLASS("client.dll", "CStanceOverrideUpdateNode");

};

} // namespace sdk

#endif // ISDK_CSTANCEOVERRIDEUPDATENODE_HPP

