// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CStaticPoseCacheBuilder (runtime-resolved offsets)
// Module: client.dll
// Parent: CStaticPoseCache
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CSTATICPOSECACHEBUILDER_HPP
#define ISDK_CSTATICPOSECACHEBUILDER_HPP

#include "../schema_runtime.hpp"
#include "CStaticPoseCache.hpp"

namespace sdk {

struct CStaticPoseCacheBuilder : CStaticPoseCache {
    SCHEMA_CLASS("client.dll", "CStaticPoseCacheBuilder");

};

} // namespace sdk

#endif // ISDK_CSTATICPOSECACHEBUILDER_HPP

