// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CStepsRemainingMetricEvaluator (runtime-resolved offsets)
// Module: client.dll
// Parent: CMotionMetricEvaluator
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CSTEPSREMAININGMETRICEVALUATOR_HPP
#define ISDK_CSTEPSREMAININGMETRICEVALUATOR_HPP

#include "../schema_runtime.hpp"
#include "CMotionMetricEvaluator.hpp"

namespace sdk {

struct CStepsRemainingMetricEvaluator : CMotionMetricEvaluator {
    SCHEMA_CLASS("client.dll", "CStepsRemainingMetricEvaluator");

};

} // namespace sdk

#endif // ISDK_CSTEPSREMAININGMETRICEVALUATOR_HPP

