// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CStopAtGoalUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CUnaryUpdateNode
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CSTOPATGOALUPDATENODE_HPP
#define ISDK_CSTOPATGOALUPDATENODE_HPP

#include "../schema_runtime.hpp"
#include "CUnaryUpdateNode.hpp"

namespace sdk {

struct CStopAtGoalUpdateNode : CUnaryUpdateNode {
    SCHEMA_CLASS("client.dll", "CStopAtGoalUpdateNode");

};

} // namespace sdk

#endif // ISDK_CSTOPATGOALUPDATENODE_HPP

