// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CStringAnimTag (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimTagBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CSTRINGANIMTAG_HPP
#define ISDK_CSTRINGANIMTAG_HPP

#include "../schema_runtime.hpp"
#include "CAnimTagBase.hpp"

namespace sdk {

struct CStringAnimTag : CAnimTagBase {
    SCHEMA_CLASS("client.dll", "CStringAnimTag");

};

} // namespace sdk

#endif // ISDK_CSTRINGANIMTAG_HPP

