// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CSubtractUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CBinaryUpdateNode
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CSUBTRACTUPDATENODE_HPP
#define ISDK_CSUBTRACTUPDATENODE_HPP

#include "../schema_runtime.hpp"
#include "CBinaryUpdateNode.hpp"

namespace sdk {

struct CSubtractUpdateNode : CBinaryUpdateNode {
    SCHEMA_CLASS("client.dll", "CSubtractUpdateNode");

};

} // namespace sdk

#endif // ISDK_CSUBTRACTUPDATENODE_HPP

