// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CSymbolAnimParameter (runtime-resolved offsets)
// Module: client.dll
// Parent: CConcreteAnimParameter
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CSYMBOLANIMPARAMETER_HPP
#define ISDK_CSYMBOLANIMPARAMETER_HPP

#include "../schema_runtime.hpp"
#include "CConcreteAnimParameter.hpp"

namespace sdk {

struct CSymbolAnimParameter : CConcreteAnimParameter {
    SCHEMA_CLASS("client.dll", "CSymbolAnimParameter");

};

} // namespace sdk

#endif // ISDK_CSYMBOLANIMPARAMETER_HPP

