// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CTakeDamageInfo (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CTAKEDAMAGEINFO_HPP
#define ISDK_CTAKEDAMAGEINFO_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CTakeDamageInfo {
    SCHEMA_CLASS("client.dll", "CTakeDamageInfo");


    // --- Virtual functions (vtable RVA: 0x1B15A40, 6 total) ---
};

} // namespace sdk

#endif // ISDK_CTAKEDAMAGEINFO_HPP

