// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CTargetSelectorUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimUpdateNodeBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CTARGETSELECTORUPDATENODE_HPP
#define ISDK_CTARGETSELECTORUPDATENODE_HPP

#include "../schema_runtime.hpp"
#include "CAnimUpdateNodeBase.hpp"

namespace sdk {

struct CTargetSelectorUpdateNode : CAnimUpdateNodeBase {
    SCHEMA_CLASS("client.dll", "CTargetSelectorUpdateNode");

};

} // namespace sdk

#endif // ISDK_CTARGETSELECTORUPDATENODE_HPP

