// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CTargetWarpUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CUnaryUpdateNode
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CTARGETWARPUPDATENODE_HPP
#define ISDK_CTARGETWARPUPDATENODE_HPP

#include "../schema_runtime.hpp"
#include "CUnaryUpdateNode.hpp"

namespace sdk {

struct CTargetWarpUpdateNode : CUnaryUpdateNode {
    SCHEMA_CLASS("client.dll", "CTargetWarpUpdateNode");

};

} // namespace sdk

#endif // ISDK_CTARGETWARPUPDATENODE_HPP

