// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CTaskHandshakeAnimTag (runtime-resolved offsets)
// Module: client.dll
// Parent: CHandshakeAnimTagBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CTASKHANDSHAKEANIMTAG_HPP
#define ISDK_CTASKHANDSHAKEANIMTAG_HPP

#include "../schema_runtime.hpp"
#include "CHandshakeAnimTagBase.hpp"

namespace sdk {

struct CTaskHandshakeAnimTag : CHandshakeAnimTagBase {
    SCHEMA_CLASS("client.dll", "CTaskHandshakeAnimTag");

};

} // namespace sdk

#endif // ISDK_CTASKHANDSHAKEANIMTAG_HPP

