// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CTestPulseIOComponent (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CTESTPULSEIOCOMPONENT_HPP
#define ISDK_CTESTPULSEIOCOMPONENT_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CTestPulseIOComponent {
    SCHEMA_CLASS("client.dll", "CTestPulseIOComponent");

};

} // namespace sdk

#endif // ISDK_CTESTPULSEIOCOMPONENT_HPP

