// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CTestPulseIOComponent_Derived (runtime-resolved offsets)
// Module: client.dll
// Parent: CTestPulseIOComponent
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CTESTPULSEIOCOMPONENT_DERIVED_HPP
#define ISDK_CTESTPULSEIOCOMPONENT_DERIVED_HPP

#include "../schema_runtime.hpp"
#include "CTestPulseIOComponent.hpp"

namespace sdk {

struct CTestPulseIOComponent_Derived : CTestPulseIOComponent {
    SCHEMA_CLASS("client.dll", "CTestPulseIOComponent_Derived");

};

} // namespace sdk

#endif // ISDK_CTESTPULSEIOCOMPONENT_DERIVED_HPP

