// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CTiltTwistConstraint (runtime-resolved offsets)
// Module: client.dll
// Parent: CBaseConstraint
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CTILTTWISTCONSTRAINT_HPP
#define ISDK_CTILTTWISTCONSTRAINT_HPP

#include "../schema_runtime.hpp"
#include "CBaseConstraint.hpp"

namespace sdk {

struct CTiltTwistConstraint : CBaseConstraint {
    SCHEMA_CLASS("client.dll", "CTiltTwistConstraint");

};

} // namespace sdk

#endif // ISDK_CTILTTWISTCONSTRAINT_HPP

