// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CTimeRemainingMetricEvaluator (runtime-resolved offsets)
// Module: client.dll
// Parent: CMotionMetricEvaluator
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CTIMEREMAININGMETRICEVALUATOR_HPP
#define ISDK_CTIMEREMAININGMETRICEVALUATOR_HPP

#include "../schema_runtime.hpp"
#include "CMotionMetricEvaluator.hpp"

namespace sdk {

struct CTimeRemainingMetricEvaluator : CMotionMetricEvaluator {
    SCHEMA_CLASS("client.dll", "CTimeRemainingMetricEvaluator");

};

} // namespace sdk

#endif // ISDK_CTIMEREMAININGMETRICEVALUATOR_HPP

