// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CToggleComponentActionUpdater (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimActionUpdater
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CTOGGLECOMPONENTACTIONUPDATER_HPP
#define ISDK_CTOGGLECOMPONENTACTIONUPDATER_HPP

#include "../schema_runtime.hpp"
#include "CAnimActionUpdater.hpp"

namespace sdk {

struct CToggleComponentActionUpdater : CAnimActionUpdater {
    SCHEMA_CLASS("client.dll", "CToggleComponentActionUpdater");

};

} // namespace sdk

#endif // ISDK_CTOGGLECOMPONENTACTIONUPDATER_HPP

