// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CTwistConstraint (runtime-resolved offsets)
// Module: client.dll
// Parent: CBaseConstraint
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CTWISTCONSTRAINT_HPP
#define ISDK_CTWISTCONSTRAINT_HPP

#include "../schema_runtime.hpp"
#include "CBaseConstraint.hpp"

namespace sdk {

struct CTwistConstraint : CBaseConstraint {
    SCHEMA_CLASS("client.dll", "CTwistConstraint");

};

} // namespace sdk

#endif // ISDK_CTWISTCONSTRAINT_HPP

