// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CUnaryUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimUpdateNodeBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CUNARYUPDATENODE_HPP
#define ISDK_CUNARYUPDATENODE_HPP

#include "../schema_runtime.hpp"
#include "CAnimUpdateNodeBase.hpp"

namespace sdk {

struct CUnaryUpdateNode : CAnimUpdateNodeBase {
    SCHEMA_CLASS("client.dll", "CUnaryUpdateNode");

};

} // namespace sdk

#endif // ISDK_CUNARYUPDATENODE_HPP

