// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVirtualAnimParameter (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimParameterBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVIRTUALANIMPARAMETER_HPP
#define ISDK_CVIRTUALANIMPARAMETER_HPP

#include "../schema_runtime.hpp"
#include "CAnimParameterBase.hpp"

namespace sdk {

struct CVirtualAnimParameter : CAnimParameterBase {
    SCHEMA_CLASS("client.dll", "CVirtualAnimParameter");

};

} // namespace sdk

#endif // ISDK_CVIRTUALANIMPARAMETER_HPP

