// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVMixEffectChainProcessorDesc (runtime-resolved offsets)
// Module: client.dll
// Parent: CVMixBaseProcessorDesc
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVMIXEFFECTCHAINPROCESSORDESC_HPP
#define ISDK_CVMIXEFFECTCHAINPROCESSORDESC_HPP

#include "../schema_runtime.hpp"
#include "CVMixBaseProcessorDesc.hpp"

namespace sdk {

struct CVMixEffectChainProcessorDesc : CVMixBaseProcessorDesc {
    SCHEMA_CLASS("client.dll", "CVMixEffectChainProcessorDesc");

};

} // namespace sdk

#endif // ISDK_CVMIXEFFECTCHAINPROCESSORDESC_HPP

