// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVMixBaseProcessorDesc (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVMIXBASEPROCESSORDESC_HPP
#define ISDK_CVMIXBASEPROCESSORDESC_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CVMixBaseProcessorDesc {
    SCHEMA_CLASS("client.dll", "CVMixBaseProcessorDesc");

};

} // namespace sdk

#endif // ISDK_CVMIXBASEPROCESSORDESC_HPP

