// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVMixBoxverbProcessorDesc (runtime-resolved offsets)
// Module: client.dll
// Parent: CVMixBaseProcessorDesc
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVMIXBOXVERBPROCESSORDESC_HPP
#define ISDK_CVMIXBOXVERBPROCESSORDESC_HPP

#include "../schema_runtime.hpp"
#include "CVMixBaseProcessorDesc.hpp"

namespace sdk {

struct CVMixBoxverbProcessorDesc : CVMixBaseProcessorDesc {
    SCHEMA_CLASS("client.dll", "CVMixBoxverbProcessorDesc");

};

} // namespace sdk

#endif // ISDK_CVMIXBOXVERBPROCESSORDESC_HPP

