// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVMixDynamicsCompressorProcessorDesc (runtime-resolved offsets)
// Module: client.dll
// Parent: CVMixBaseProcessorDesc
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVMIXDYNAMICSCOMPRESSORPROCESSORDESC_HPP
#define ISDK_CVMIXDYNAMICSCOMPRESSORPROCESSORDESC_HPP

#include "../schema_runtime.hpp"
#include "CVMixBaseProcessorDesc.hpp"

namespace sdk {

struct CVMixDynamicsCompressorProcessorDesc : CVMixBaseProcessorDesc {
    SCHEMA_CLASS("client.dll", "CVMixDynamicsCompressorProcessorDesc");

};

} // namespace sdk

#endif // ISDK_CVMIXDYNAMICSCOMPRESSORPROCESSORDESC_HPP

