// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVMixVocoderProcessorDesc (runtime-resolved offsets)
// Module: client.dll
// Parent: CVMixBaseProcessorDesc
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVMIXVOCODERPROCESSORDESC_HPP
#define ISDK_CVMIXVOCODERPROCESSORDESC_HPP

#include "../schema_runtime.hpp"
#include "CVMixBaseProcessorDesc.hpp"

namespace sdk {

struct CVMixVocoderProcessorDesc : CVMixBaseProcessorDesc {
    SCHEMA_CLASS("client.dll", "CVMixVocoderProcessorDesc");

};

} // namespace sdk

#endif // ISDK_CVMIXVOCODERPROCESSORDESC_HPP

