// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVMixSteamAudioHybridReverbProcessorDesc (runtime-resolved offsets)
// Module: client.dll
// Parent: CVMixBaseProcessorDesc
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVMIXSTEAMAUDIOHYBRIDREVERBPROCESSORDESC_HPP
#define ISDK_CVMIXSTEAMAUDIOHYBRIDREVERBPROCESSORDESC_HPP

#include "../schema_runtime.hpp"
#include "CVMixBaseProcessorDesc.hpp"

namespace sdk {

struct CVMixSteamAudioHybridReverbProcessorDesc : CVMixBaseProcessorDesc {
    SCHEMA_CLASS("client.dll", "CVMixSteamAudioHybridReverbProcessorDesc");

};

} // namespace sdk

#endif // ISDK_CVMIXSTEAMAUDIOHYBRIDREVERBPROCESSORDESC_HPP

