// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVMixDualCompressorProcessorDesc (runtime-resolved offsets)
// Module: client.dll
// Parent: CVMixBaseProcessorDesc
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVMIXDUALCOMPRESSORPROCESSORDESC_HPP
#define ISDK_CVMIXDUALCOMPRESSORPROCESSORDESC_HPP

#include "../schema_runtime.hpp"
#include "CVMixBaseProcessorDesc.hpp"

namespace sdk {

struct CVMixDualCompressorProcessorDesc : CVMixBaseProcessorDesc {
    SCHEMA_CLASS("client.dll", "CVMixDualCompressorProcessorDesc");

};

} // namespace sdk

#endif // ISDK_CVMIXDUALCOMPRESSORPROCESSORDESC_HPP

