// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVMixShaperProcessorDesc (runtime-resolved offsets)
// Module: client.dll
// Parent: CVMixBaseProcessorDesc
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVMIXSHAPERPROCESSORDESC_HPP
#define ISDK_CVMIXSHAPERPROCESSORDESC_HPP

#include "../schema_runtime.hpp"
#include "CVMixBaseProcessorDesc.hpp"

namespace sdk {

struct CVMixShaperProcessorDesc : CVMixBaseProcessorDesc {
    SCHEMA_CLASS("client.dll", "CVMixShaperProcessorDesc");

};

} // namespace sdk

#endif // ISDK_CVMIXSHAPERPROCESSORDESC_HPP

