// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVMixBoxverb2ProcessorDesc (runtime-resolved offsets)
// Module: client.dll
// Parent: CVMixBaseProcessorDesc
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVMIXBOXVERB2PROCESSORDESC_HPP
#define ISDK_CVMIXBOXVERB2PROCESSORDESC_HPP

#include "../schema_runtime.hpp"
#include "CVMixBaseProcessorDesc.hpp"

namespace sdk {

struct CVMixBoxverb2ProcessorDesc : CVMixBaseProcessorDesc {
    SCHEMA_CLASS("client.dll", "CVMixBoxverb2ProcessorDesc");

};

} // namespace sdk

#endif // ISDK_CVMIXBOXVERB2PROCESSORDESC_HPP

