// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVMixConvolutionProcessorDesc (runtime-resolved offsets)
// Module: client.dll
// Parent: CVMixBaseProcessorDesc
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVMIXCONVOLUTIONPROCESSORDESC_HPP
#define ISDK_CVMIXCONVOLUTIONPROCESSORDESC_HPP

#include "../schema_runtime.hpp"
#include "CVMixBaseProcessorDesc.hpp"

namespace sdk {

struct CVMixConvolutionProcessorDesc : CVMixBaseProcessorDesc {
    SCHEMA_CLASS("client.dll", "CVMixConvolutionProcessorDesc");

};

} // namespace sdk

#endif // ISDK_CVMIXCONVOLUTIONPROCESSORDESC_HPP

