// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVMixPlateReverbProcessorDesc (runtime-resolved offsets)
// Module: client.dll
// Parent: CVMixBaseProcessorDesc
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVMIXPLATEREVERBPROCESSORDESC_HPP
#define ISDK_CVMIXPLATEREVERBPROCESSORDESC_HPP

#include "../schema_runtime.hpp"
#include "CVMixBaseProcessorDesc.hpp"

namespace sdk {

struct CVMixPlateReverbProcessorDesc : CVMixBaseProcessorDesc {
    SCHEMA_CLASS("client.dll", "CVMixPlateReverbProcessorDesc");

};

} // namespace sdk

#endif // ISDK_CVMIXPLATEREVERBPROCESSORDESC_HPP

