// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVMixDelayProcessorDesc (runtime-resolved offsets)
// Module: client.dll
// Parent: CVMixBaseProcessorDesc
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVMIXDELAYPROCESSORDESC_HPP
#define ISDK_CVMIXDELAYPROCESSORDESC_HPP

#include "../schema_runtime.hpp"
#include "CVMixBaseProcessorDesc.hpp"

namespace sdk {

struct CVMixDelayProcessorDesc : CVMixBaseProcessorDesc {
    SCHEMA_CLASS("client.dll", "CVMixDelayProcessorDesc");

};

} // namespace sdk

#endif // ISDK_CVMIXDELAYPROCESSORDESC_HPP

