// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVMixModDelayProcessorDesc (runtime-resolved offsets)
// Module: client.dll
// Parent: CVMixBaseProcessorDesc
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVMIXMODDELAYPROCESSORDESC_HPP
#define ISDK_CVMIXMODDELAYPROCESSORDESC_HPP

#include "../schema_runtime.hpp"
#include "CVMixBaseProcessorDesc.hpp"

namespace sdk {

struct CVMixModDelayProcessorDesc : CVMixBaseProcessorDesc {
    SCHEMA_CLASS("client.dll", "CVMixModDelayProcessorDesc");

};

} // namespace sdk

#endif // ISDK_CVMIXMODDELAYPROCESSORDESC_HPP

