// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVMixDynamics3BandProcessorDesc (runtime-resolved offsets)
// Module: client.dll
// Parent: CVMixBaseProcessorDesc
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVMIXDYNAMICS3BANDPROCESSORDESC_HPP
#define ISDK_CVMIXDYNAMICS3BANDPROCESSORDESC_HPP

#include "../schema_runtime.hpp"
#include "CVMixBaseProcessorDesc.hpp"

namespace sdk {

struct CVMixDynamics3BandProcessorDesc : CVMixBaseProcessorDesc {
    SCHEMA_CLASS("client.dll", "CVMixDynamics3BandProcessorDesc");

};

} // namespace sdk

#endif // ISDK_CVMIXDYNAMICS3BANDPROCESSORDESC_HPP

