// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVMixSteamAudioDirectProcessorDesc (runtime-resolved offsets)
// Module: client.dll
// Parent: CVMixBaseProcessorDesc
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVMIXSTEAMAUDIODIRECTPROCESSORDESC_HPP
#define ISDK_CVMIXSTEAMAUDIODIRECTPROCESSORDESC_HPP

#include "../schema_runtime.hpp"
#include "CVMixBaseProcessorDesc.hpp"

namespace sdk {

struct CVMixSteamAudioDirectProcessorDesc : CVMixBaseProcessorDesc {
    SCHEMA_CLASS("client.dll", "CVMixSteamAudioDirectProcessorDesc");

};

} // namespace sdk

#endif // ISDK_CVMIXSTEAMAUDIODIRECTPROCESSORDESC_HPP

