// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVMixAutoFilterProcessorDesc (runtime-resolved offsets)
// Module: client.dll
// Parent: CVMixBaseProcessorDesc
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVMIXAUTOFILTERPROCESSORDESC_HPP
#define ISDK_CVMIXAUTOFILTERPROCESSORDESC_HPP

#include "../schema_runtime.hpp"
#include "CVMixBaseProcessorDesc.hpp"

namespace sdk {

struct CVMixAutoFilterProcessorDesc : CVMixBaseProcessorDesc {
    SCHEMA_CLASS("client.dll", "CVMixAutoFilterProcessorDesc");

};

} // namespace sdk

#endif // ISDK_CVMIXAUTOFILTERPROCESSORDESC_HPP

