// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVMixFreeverbProcessorDesc (runtime-resolved offsets)
// Module: client.dll
// Parent: CVMixBaseProcessorDesc
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVMIXFREEVERBPROCESSORDESC_HPP
#define ISDK_CVMIXFREEVERBPROCESSORDESC_HPP

#include "../schema_runtime.hpp"
#include "CVMixBaseProcessorDesc.hpp"

namespace sdk {

struct CVMixFreeverbProcessorDesc : CVMixBaseProcessorDesc {
    SCHEMA_CLASS("client.dll", "CVMixFreeverbProcessorDesc");

};

} // namespace sdk

#endif // ISDK_CVMIXFREEVERBPROCESSORDESC_HPP

