// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVMixStereoDelayProcessorDesc (runtime-resolved offsets)
// Module: client.dll
// Parent: CVMixBaseProcessorDesc
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVMIXSTEREODELAYPROCESSORDESC_HPP
#define ISDK_CVMIXSTEREODELAYPROCESSORDESC_HPP

#include "../schema_runtime.hpp"
#include "CVMixBaseProcessorDesc.hpp"

namespace sdk {

struct CVMixStereoDelayProcessorDesc : CVMixBaseProcessorDesc {
    SCHEMA_CLASS("client.dll", "CVMixStereoDelayProcessorDesc");

};

} // namespace sdk

#endif // ISDK_CVMIXSTEREODELAYPROCESSORDESC_HPP

