// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVMixDiffusorProcessorDesc (runtime-resolved offsets)
// Module: client.dll
// Parent: CVMixBaseProcessorDesc
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVMIXDIFFUSORPROCESSORDESC_HPP
#define ISDK_CVMIXDIFFUSORPROCESSORDESC_HPP

#include "../schema_runtime.hpp"
#include "CVMixBaseProcessorDesc.hpp"

namespace sdk {

struct CVMixDiffusorProcessorDesc : CVMixBaseProcessorDesc {
    SCHEMA_CLASS("client.dll", "CVMixDiffusorProcessorDesc");

};

} // namespace sdk

#endif // ISDK_CVMIXDIFFUSORPROCESSORDESC_HPP

