// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVMixSubgraphSwitchProcessorDesc (runtime-resolved offsets)
// Module: client.dll
// Parent: CVMixBaseProcessorDesc
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVMIXSUBGRAPHSWITCHPROCESSORDESC_HPP
#define ISDK_CVMIXSUBGRAPHSWITCHPROCESSORDESC_HPP

#include "../schema_runtime.hpp"
#include "CVMixBaseProcessorDesc.hpp"

namespace sdk {

struct CVMixSubgraphSwitchProcessorDesc : CVMixBaseProcessorDesc {
    SCHEMA_CLASS("client.dll", "CVMixSubgraphSwitchProcessorDesc");

};

} // namespace sdk

#endif // ISDK_CVMIXSUBGRAPHSWITCHPROCESSORDESC_HPP

