// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVMixFilterProcessorDesc (runtime-resolved offsets)
// Module: client.dll
// Parent: CVMixBaseProcessorDesc
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVMIXFILTERPROCESSORDESC_HPP
#define ISDK_CVMIXFILTERPROCESSORDESC_HPP

#include "../schema_runtime.hpp"
#include "CVMixBaseProcessorDesc.hpp"

namespace sdk {

struct CVMixFilterProcessorDesc : CVMixBaseProcessorDesc {
    SCHEMA_CLASS("client.dll", "CVMixFilterProcessorDesc");

};

} // namespace sdk

#endif // ISDK_CVMIXFILTERPROCESSORDESC_HPP

