// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVMixEnvelopeProcessorDesc (runtime-resolved offsets)
// Module: client.dll
// Parent: CVMixBaseProcessorDesc
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVMIXENVELOPEPROCESSORDESC_HPP
#define ISDK_CVMIXENVELOPEPROCESSORDESC_HPP

#include "../schema_runtime.hpp"
#include "CVMixBaseProcessorDesc.hpp"

namespace sdk {

struct CVMixEnvelopeProcessorDesc : CVMixBaseProcessorDesc {
    SCHEMA_CLASS("client.dll", "CVMixEnvelopeProcessorDesc");

};

} // namespace sdk

#endif // ISDK_CVMIXENVELOPEPROCESSORDESC_HPP

