// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVMixOscProcessorDesc (runtime-resolved offsets)
// Module: client.dll
// Parent: CVMixBaseProcessorDesc
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVMIXOSCPROCESSORDESC_HPP
#define ISDK_CVMIXOSCPROCESSORDESC_HPP

#include "../schema_runtime.hpp"
#include "CVMixBaseProcessorDesc.hpp"

namespace sdk {

struct CVMixOscProcessorDesc : CVMixBaseProcessorDesc {
    SCHEMA_CLASS("client.dll", "CVMixOscProcessorDesc");

};

} // namespace sdk

#endif // ISDK_CVMIXOSCPROCESSORDESC_HPP

