// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVMixSteamAudioHRTFProcessorDesc (runtime-resolved offsets)
// Module: client.dll
// Parent: CVMixBaseProcessorDesc
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVMIXSTEAMAUDIOHRTFPROCESSORDESC_HPP
#define ISDK_CVMIXSTEAMAUDIOHRTFPROCESSORDESC_HPP

#include "../schema_runtime.hpp"
#include "CVMixBaseProcessorDesc.hpp"

namespace sdk {

struct CVMixSteamAudioHRTFProcessorDesc : CVMixBaseProcessorDesc {
    SCHEMA_CLASS("client.dll", "CVMixSteamAudioHRTFProcessorDesc");

};

} // namespace sdk

#endif // ISDK_CVMIXSTEAMAUDIOHRTFPROCESSORDESC_HPP

