// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVoiceContainerVsndTrigger (runtime-resolved offsets)
// Module: client.dll
// Parent: CVoiceContainerBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVOICECONTAINERVSNDTRIGGER_HPP
#define ISDK_CVOICECONTAINERVSNDTRIGGER_HPP

#include "../schema_runtime.hpp"
#include "CVoiceContainerBase.hpp"

namespace sdk {

struct CVoiceContainerVsndTrigger : CVoiceContainerBase {
    SCHEMA_CLASS("client.dll", "CVoiceContainerVsndTrigger");

};

} // namespace sdk

#endif // ISDK_CVOICECONTAINERVSNDTRIGGER_HPP

