// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVoiceContainerBase (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVOICECONTAINERBASE_HPP
#define ISDK_CVOICECONTAINERBASE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CVoiceContainerBase {
    SCHEMA_CLASS("client.dll", "CVoiceContainerBase");

};

} // namespace sdk

#endif // ISDK_CVOICECONTAINERBASE_HPP

