// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVoiceContainerAmpedDecayingSineWave (runtime-resolved offsets)
// Module: client.dll
// Parent: CVoiceContainerDecayingSineWave
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVOICECONTAINERAMPEDDECAYINGSINEWAVE_HPP
#define ISDK_CVOICECONTAINERAMPEDDECAYINGSINEWAVE_HPP

#include "../schema_runtime.hpp"
#include "CVoiceContainerDecayingSineWave.hpp"

namespace sdk {

struct CVoiceContainerAmpedDecayingSineWave : CVoiceContainerDecayingSineWave {
    SCHEMA_CLASS("client.dll", "CVoiceContainerAmpedDecayingSineWave");

};

} // namespace sdk

#endif // ISDK_CVOICECONTAINERAMPEDDECAYINGSINEWAVE_HPP

