// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVoiceContainerLoopXFade (runtime-resolved offsets)
// Module: client.dll
// Parent: CVoiceContainerBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVOICECONTAINERLOOPXFADE_HPP
#define ISDK_CVOICECONTAINERLOOPXFADE_HPP

#include "../schema_runtime.hpp"
#include "CVoiceContainerBase.hpp"

namespace sdk {

struct CVoiceContainerLoopXFade : CVoiceContainerBase {
    SCHEMA_CLASS("client.dll", "CVoiceContainerLoopXFade");

};

} // namespace sdk

#endif // ISDK_CVOICECONTAINERLOOPXFADE_HPP

