// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVoiceContainerAsyncGenerator (runtime-resolved offsets)
// Module: client.dll
// Parent: CVoiceContainerGenerator
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVOICECONTAINERASYNCGENERATOR_HPP
#define ISDK_CVOICECONTAINERASYNCGENERATOR_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CVoiceContainerAsyncGenerator {
    SCHEMA_CLASS("client.dll", "CVoiceContainerAsyncGenerator");

};

} // namespace sdk

#endif // ISDK_CVOICECONTAINERASYNCGENERATOR_HPP

