// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVoiceContainerSet (runtime-resolved offsets)
// Module: client.dll
// Parent: CVoiceContainerBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVOICECONTAINERSET_HPP
#define ISDK_CVOICECONTAINERSET_HPP

#include "../schema_runtime.hpp"
#include "CVoiceContainerBase.hpp"

namespace sdk {

struct CVoiceContainerSet : CVoiceContainerBase {
    SCHEMA_CLASS("client.dll", "CVoiceContainerSet");

};

} // namespace sdk

#endif // ISDK_CVOICECONTAINERSET_HPP

