// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVoiceContainerEnvelopeAnalyzer (runtime-resolved offsets)
// Module: client.dll
// Parent: CVoiceContainerAnalysisBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVOICECONTAINERENVELOPEANALYZER_HPP
#define ISDK_CVOICECONTAINERENVELOPEANALYZER_HPP

#include "../schema_runtime.hpp"
#include "CVoiceContainerAnalysisBase.hpp"

namespace sdk {

struct CVoiceContainerEnvelopeAnalyzer : CVoiceContainerAnalysisBase {
    SCHEMA_CLASS("client.dll", "CVoiceContainerEnvelopeAnalyzer");

};

} // namespace sdk

#endif // ISDK_CVOICECONTAINERENVELOPEANALYZER_HPP

