// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVoiceContainerSelector (runtime-resolved offsets)
// Module: client.dll
// Parent: CVoiceContainerBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVOICECONTAINERSELECTOR_HPP
#define ISDK_CVOICECONTAINERSELECTOR_HPP

#include "../schema_runtime.hpp"
#include "CVoiceContainerBase.hpp"

namespace sdk {

struct CVoiceContainerSelector : CVoiceContainerBase {
    SCHEMA_CLASS("client.dll", "CVoiceContainerSelector");

};

} // namespace sdk

#endif // ISDK_CVOICECONTAINERSELECTOR_HPP

