// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVoiceContainerShapedNoise (runtime-resolved offsets)
// Module: client.dll
// Parent: CVoiceContainerGenerator
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVOICECONTAINERSHAPEDNOISE_HPP
#define ISDK_CVOICECONTAINERSHAPEDNOISE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CVoiceContainerShapedNoise {
    SCHEMA_CLASS("client.dll", "CVoiceContainerShapedNoise");

};

} // namespace sdk

#endif // ISDK_CVOICECONTAINERSHAPEDNOISE_HPP

