// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVoiceContainerRealtimeFMSineWave (runtime-resolved offsets)
// Module: client.dll
// Parent: CVoiceContainerGenerator
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVOICECONTAINERREALTIMEFMSINEWAVE_HPP
#define ISDK_CVOICECONTAINERREALTIMEFMSINEWAVE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CVoiceContainerRealtimeFMSineWave {
    SCHEMA_CLASS("client.dll", "CVoiceContainerRealtimeFMSineWave");

};

} // namespace sdk

#endif // ISDK_CVOICECONTAINERREALTIMEFMSINEWAVE_HPP

