// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVoiceContainerEnum (runtime-resolved offsets)
// Module: client.dll
// Parent: CVoiceContainerBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVOICECONTAINERENUM_HPP
#define ISDK_CVOICECONTAINERENUM_HPP

#include "../schema_runtime.hpp"
#include "CVoiceContainerBase.hpp"

namespace sdk {

struct CVoiceContainerEnum : CVoiceContainerBase {
    SCHEMA_CLASS("client.dll", "CVoiceContainerEnum");

};

} // namespace sdk

#endif // ISDK_CVOICECONTAINERENUM_HPP

