// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVoiceContainerAnalysisBase (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVOICECONTAINERANALYSISBASE_HPP
#define ISDK_CVOICECONTAINERANALYSISBASE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CVoiceContainerAnalysisBase {
    SCHEMA_CLASS("client.dll", "CVoiceContainerAnalysisBase");

};

} // namespace sdk

#endif // ISDK_CVOICECONTAINERANALYSISBASE_HPP

