// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVoiceContainerBlender (runtime-resolved offsets)
// Module: client.dll
// Parent: CVoiceContainerBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVOICECONTAINERBLENDER_HPP
#define ISDK_CVOICECONTAINERBLENDER_HPP

#include "../schema_runtime.hpp"
#include "CVoiceContainerBase.hpp"

namespace sdk {

struct CVoiceContainerBlender : CVoiceContainerBase {
    SCHEMA_CLASS("client.dll", "CVoiceContainerBlender");

};

} // namespace sdk

#endif // ISDK_CVOICECONTAINERBLENDER_HPP

