// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVoiceContainerNull (runtime-resolved offsets)
// Module: client.dll
// Parent: CVoiceContainerGenerator
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVOICECONTAINERNULL_HPP
#define ISDK_CVOICECONTAINERNULL_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CVoiceContainerNull {
    SCHEMA_CLASS("client.dll", "CVoiceContainerNull");

};

} // namespace sdk

#endif // ISDK_CVOICECONTAINERNULL_HPP

