// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVoiceContainerParameterBlender (runtime-resolved offsets)
// Module: client.dll
// Parent: CVoiceContainerBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVOICECONTAINERPARAMETERBLENDER_HPP
#define ISDK_CVOICECONTAINERPARAMETERBLENDER_HPP

#include "../schema_runtime.hpp"
#include "CVoiceContainerBase.hpp"

namespace sdk {

struct CVoiceContainerParameterBlender : CVoiceContainerBase {
    SCHEMA_CLASS("client.dll", "CVoiceContainerParameterBlender");

};

} // namespace sdk

#endif // ISDK_CVOICECONTAINERPARAMETERBLENDER_HPP

