// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVoiceContainerDefault (runtime-resolved offsets)
// Module: client.dll
// Parent: CVoiceContainerBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVOICECONTAINERDEFAULT_HPP
#define ISDK_CVOICECONTAINERDEFAULT_HPP

#include "../schema_runtime.hpp"
#include "CVoiceContainerBase.hpp"

namespace sdk {

struct CVoiceContainerDefault : CVoiceContainerBase {
    SCHEMA_CLASS("client.dll", "CVoiceContainerDefault");

};

} // namespace sdk

#endif // ISDK_CVOICECONTAINERDEFAULT_HPP

