// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVoiceContainerLoopTriggerWithRandomPanner (runtime-resolved offsets)
// Module: client.dll
// Parent: CVoiceContainerLoopTrigger
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVOICECONTAINERLOOPTRIGGERWITHRANDOMPANNER_HPP
#define ISDK_CVOICECONTAINERLOOPTRIGGERWITHRANDOMPANNER_HPP

#include "../schema_runtime.hpp"
#include "CVoiceContainerLoopTrigger.hpp"

namespace sdk {

struct CVoiceContainerLoopTriggerWithRandomPanner : CVoiceContainerLoopTrigger {
    SCHEMA_CLASS("client.dll", "CVoiceContainerLoopTriggerWithRandomPanner");

};

} // namespace sdk

#endif // ISDK_CVOICECONTAINERLOOPTRIGGERWITHRANDOMPANNER_HPP

