// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVoiceContainerDecayingSineWave (runtime-resolved offsets)
// Module: client.dll
// Parent: CVoiceContainerGenerator
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVOICECONTAINERDECAYINGSINEWAVE_HPP
#define ISDK_CVOICECONTAINERDECAYINGSINEWAVE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CVoiceContainerDecayingSineWave {
    SCHEMA_CLASS("client.dll", "CVoiceContainerDecayingSineWave");

};

} // namespace sdk

#endif // ISDK_CVOICECONTAINERDECAYINGSINEWAVE_HPP

