// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVoiceContainerSwitch (runtime-resolved offsets)
// Module: client.dll
// Parent: CVoiceContainerBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVOICECONTAINERSWITCH_HPP
#define ISDK_CVOICECONTAINERSWITCH_HPP

#include "../schema_runtime.hpp"
#include "CVoiceContainerBase.hpp"

namespace sdk {

struct CVoiceContainerSwitch : CVoiceContainerBase {
    SCHEMA_CLASS("client.dll", "CVoiceContainerSwitch");

};

} // namespace sdk

#endif // ISDK_CVOICECONTAINERSWITCH_HPP

