// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVoiceContainerMultiBlender (runtime-resolved offsets)
// Module: client.dll
// Parent: CVoiceContainerBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVOICECONTAINERMULTIBLENDER_HPP
#define ISDK_CVOICECONTAINERMULTIBLENDER_HPP

#include "../schema_runtime.hpp"
#include "CVoiceContainerBase.hpp"

namespace sdk {

struct CVoiceContainerMultiBlender : CVoiceContainerBase {
    SCHEMA_CLASS("client.dll", "CVoiceContainerMultiBlender");

};

} // namespace sdk

#endif // ISDK_CVOICECONTAINERMULTIBLENDER_HPP

