// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVoiceContainerRandomSampler (runtime-resolved offsets)
// Module: client.dll
// Parent: CVoiceContainerAsyncGenerator
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVOICECONTAINERRANDOMSAMPLER_HPP
#define ISDK_CVOICECONTAINERRANDOMSAMPLER_HPP

#include "../schema_runtime.hpp"
#include "CVoiceContainerAsyncGenerator.hpp"

namespace sdk {

struct CVoiceContainerRandomSampler : CVoiceContainerAsyncGenerator {
    SCHEMA_CLASS("client.dll", "CVoiceContainerRandomSampler");

};

} // namespace sdk

#endif // ISDK_CVOICECONTAINERRANDOMSAMPLER_HPP

