// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVoiceContainerGranulator (runtime-resolved offsets)
// Module: client.dll
// Parent: CVoiceContainerAsyncGenerator
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVOICECONTAINERGRANULATOR_HPP
#define ISDK_CVOICECONTAINERGRANULATOR_HPP

#include "../schema_runtime.hpp"
#include "CVoiceContainerAsyncGenerator.hpp"

namespace sdk {

struct CVoiceContainerGranulator : CVoiceContainerAsyncGenerator {
    SCHEMA_CLASS("client.dll", "CVoiceContainerGranulator");

};

} // namespace sdk

#endif // ISDK_CVOICECONTAINERGRANULATOR_HPP

