// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CVoiceContainerVMixSnd (runtime-resolved offsets)
// Module: client.dll
// Parent: CVoiceContainerBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CVOICECONTAINERVMIXSND_HPP
#define ISDK_CVOICECONTAINERVMIXSND_HPP

#include "../schema_runtime.hpp"
#include "CVoiceContainerBase.hpp"

namespace sdk {

struct CVoiceContainerVMixSnd : CVoiceContainerBase {
    SCHEMA_CLASS("client.dll", "CVoiceContainerVMixSnd");

};

} // namespace sdk

#endif // ISDK_CVOICECONTAINERVMIXSND_HPP

