// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CWarpSectionAnimTagBase (runtime-resolved offsets)
// Module: client.dll
// Parent: CAnimTagBase
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CWARPSECTIONANIMTAGBASE_HPP
#define ISDK_CWARPSECTIONANIMTAGBASE_HPP

#include "../schema_runtime.hpp"
#include "CAnimTagBase.hpp"

namespace sdk {

struct CWarpSectionAnimTagBase : CAnimTagBase {
    SCHEMA_CLASS("client.dll", "CWarpSectionAnimTagBase");

};

} // namespace sdk

#endif // ISDK_CWARPSECTIONANIMTAGBASE_HPP

