// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CWayPointHelperUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CUnaryUpdateNode
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CWAYPOINTHELPERUPDATENODE_HPP
#define ISDK_CWAYPOINTHELPERUPDATENODE_HPP

#include "../schema_runtime.hpp"
#include "CUnaryUpdateNode.hpp"

namespace sdk {

struct CWayPointHelperUpdateNode : CUnaryUpdateNode {
    SCHEMA_CLASS("client.dll", "CWayPointHelperUpdateNode");

};

} // namespace sdk

#endif // ISDK_CWAYPOINTHELPERUPDATENODE_HPP

