// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CZeroPoseUpdateNode (runtime-resolved offsets)
// Module: client.dll
// Parent: CLeafUpdateNode
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CZEROPOSEUPDATENODE_HPP
#define ISDK_CZEROPOSEUPDATENODE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct CZeroPoseUpdateNode {
    SCHEMA_CLASS("client.dll", "CZeroPoseUpdateNode");

};

} // namespace sdk

#endif // ISDK_CZEROPOSEUPDATENODE_HPP

