// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: DebugDrawBoneTransforms_t (runtime-resolved offsets)
// Module: client.dll
// Parent: DebugSnapshotBaseStructuredData_t
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_DEBUGDRAWBONETRANSFORMS_T_HPP
#define ISDK_DEBUGDRAWBONETRANSFORMS_T_HPP

#include "../schema_runtime.hpp"
#include "DebugSnapshotBaseStructuredData_t.hpp"

namespace sdk {

struct DebugDrawBoneTransforms_t : DebugSnapshotBaseStructuredData_t {
    SCHEMA_CLASS("client.dll", "DebugDrawBoneTransforms_t");


    // --- Virtual functions (vtable RVA: 0x19CED20, 5 total) ---
    VFUNC_RAW(0);                                           // sig: 40 53 48 83 EC 20 48 8B DA 48 8D 15 ? ? ...
    VFUNC_RAW(1);                                           // sig: 40 53 56 48 83 EC 48 48 83 BA 40 01 00 0...
    VFUNC_RAW(2);                                           // sig: 4C 8D 05 ? ? ? ? E9 ? ? ? ? CC CC CC CC ...
    VFUNC_RAW(4);                                           // sig: 48 89 5C 24 08 48 89 74 24 10 57 48 83 E...
};

} // namespace sdk

#endif // ISDK_DEBUGDRAWBONETRANSFORMS_T_HPP

