// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: EntityKeyValueData_t (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_ENTITYKEYVALUEDATA_T_HPP
#define ISDK_ENTITYKEYVALUEDATA_T_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct EntityKeyValueData_t {
    SCHEMA_CLASS("client.dll", "EntityKeyValueData_t");

};

} // namespace sdk

#endif // ISDK_ENTITYKEYVALUEDATA_T_HPP

