// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: EntityRenderAttribute_t (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_ENTITYRENDERATTRIBUTE_T_HPP
#define ISDK_ENTITYRENDERATTRIBUTE_T_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct EntityRenderAttribute_t {
    SCHEMA_CLASS("client.dll", "EntityRenderAttribute_t");


    // --- Virtual functions (vtable RVA: 0x19C0CC8, 9 total) ---
    VFUNC_RAW(0);                                           // sig: 40 53 48 83 EC 20 48 8B DA 48 8D 15 ? ? ...
    VFUNC_RAW(1);                                           // sig: 80 79 2C 00 74 09 48 83 C1 08 E9 ? ? ? ?... reads: 0x2C
    VFUNC_RAW(2);                                           // sig: 80 79 2C 00 74 09 48 83 C1 08 E9 ? ? ? ?... reads: 0x2C
    VFUNC_RAW(3);                                           // sig: 80 79 2C 00 74 09 48 83 C1 08 E9 ? ? ? ?... reads: 0x2C
    VFUNC_RAW(4);                                           // sig: 80 79 2C 00 4C 8B C9 74 0C 48 83 C1 08 4... reads: 0x2C
    VFUNC_RAW(5);                                           // sig: E9 ? ? ? ? CC CC CC CC CC CC CC CC CC CC...
    VFUNC_RAW(6);                                           // sig: 4C 8D 05 ? ? ? ? ? 94 26 00 00 CC CC CC ...
    VFUNC_RAW(8);                                           // sig: 48 8B 05 ? ? ? ? ? ? ? CC CC CC CC CC CC...
};

} // namespace sdk

#endif // ISDK_ENTITYRENDERATTRIBUTE_T_HPP

