// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: EntitySpottedState_t (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_ENTITYSPOTTEDSTATE_T_HPP
#define ISDK_ENTITYSPOTTEDSTATE_T_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct EntitySpottedState_t {
    SCHEMA_CLASS("client.dll", "EntitySpottedState_t");


    // --- Virtual functions (vtable RVA: 0x1A50E60, 5 total) ---
};

} // namespace sdk

#endif // ISDK_ENTITYSPOTTEDSTATE_T_HPP

