// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: FilterHealth (runtime-resolved offsets)
// Module: client.dll
// Parent: CBaseFilter
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_FILTERHEALTH_HPP
#define ISDK_FILTERHEALTH_HPP

#include "../schema_runtime.hpp"
#include "CBaseFilter.hpp"

namespace sdk {

struct FilterHealth : CBaseFilter {
    SCHEMA_CLASS("client.dll", "FilterHealth");


    // --- Virtual functions (vtable RVA: 0x1AC8A60, 217 total) ---
};

} // namespace sdk

#endif // ISDK_FILTERHEALTH_HPP

