// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: fogparams_t (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_FOGPARAMS_T_HPP
#define ISDK_FOGPARAMS_T_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct fogparams_t {
    SCHEMA_CLASS("client.dll", "fogparams_t");


    // --- Virtual functions (vtable RVA: 0x196D470, 8 total) ---
};

} // namespace sdk

#endif // ISDK_FOGPARAMS_T_HPP

