// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: INavObstacle (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_INAVOBSTACLE_HPP
#define ISDK_INAVOBSTACLE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct INavObstacle {
    SCHEMA_CLASS("client.dll", "INavObstacle");

};

} // namespace sdk

#endif // ISDK_INAVOBSTACLE_HPP

