// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: IntervalTimer (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_INTERVALTIMER_HPP
#define ISDK_INTERVALTIMER_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct IntervalTimer {
    SCHEMA_CLASS("client.dll", "IntervalTimer");


    // --- Virtual functions (vtable RVA: 0x19D2E30, 8 total) ---
    VFUNC_RAW(0);                                           // sig: 40 53 48 83 EC 20 48 8B DA 48 8D 15 ? ? ...
    VFUNC_RAW(2);                                           // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(3);                                           // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(4);                                           // sig: C2 00 00 CC CC CC CC CC CC CC CC CC CC C...
    VFUNC_RAW(5);                                           // sig: E9 ? ? ? ? CC CC CC CC CC CC CC CC CC CC...
    VFUNC_RAW(6);                                           // sig: 4C 8D 05 ? ? ? ? ? A4 2E 00 00 CC CC CC ...
};

} // namespace sdk

#endif // ISDK_INTERVALTIMER_HPP

