// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: IParticleEffect (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_IPARTICLEEFFECT_HPP
#define ISDK_IPARTICLEEFFECT_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct IParticleEffect {
    SCHEMA_CLASS("client.dll", "IParticleEffect");


    // --- Virtual functions (vtable RVA: 0x1CA8F38, 8 total) ---
};

} // namespace sdk

#endif // ISDK_IPARTICLEEFFECT_HPP

