// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: IParticleCollection (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_IPARTICLECOLLECTION_HPP
#define ISDK_IPARTICLECOLLECTION_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct IParticleCollection {
    SCHEMA_CLASS("client.dll", "IParticleCollection");

};

} // namespace sdk

#endif // ISDK_IPARTICLECOLLECTION_HPP

