// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: IPhysAggregateInstance (runtime-resolved offsets)
// Module: client.dll
// Parent: IPhysicsBodyList
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_IPHYSAGGREGATEINSTANCE_HPP
#define ISDK_IPHYSAGGREGATEINSTANCE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct IPhysAggregateInstance {
    SCHEMA_CLASS("client.dll", "IPhysAggregateInstance");

};

} // namespace sdk

#endif // ISDK_IPHYSAGGREGATEINSTANCE_HPP

