// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: locksound_t (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_LOCKSOUND_T_HPP
#define ISDK_LOCKSOUND_T_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct locksound_t {
    SCHEMA_CLASS("client.dll", "locksound_t");

};

} // namespace sdk

#endif // ISDK_LOCKSOUND_T_HPP

