// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: PermEntityLumpData_t (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_PERMENTITYLUMPDATA_T_HPP
#define ISDK_PERMENTITYLUMPDATA_T_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct PermEntityLumpData_t {
    SCHEMA_CLASS("client.dll", "PermEntityLumpData_t");

};

} // namespace sdk

#endif // ISDK_PERMENTITYLUMPDATA_T_HPP

