// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: PhysicsRagdollPose_t (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_PHYSICSRAGDOLLPOSE_T_HPP
#define ISDK_PHYSICSRAGDOLLPOSE_T_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct PhysicsRagdollPose_t {
    SCHEMA_CLASS("client.dll", "PhysicsRagdollPose_t");


    // --- Virtual functions (vtable RVA: 0x19A3C40, 8 total) ---
};

} // namespace sdk

#endif // ISDK_PHYSICSRAGDOLLPOSE_T_HPP

