// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: SellbackPurchaseEntry_t (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_SELLBACKPURCHASEENTRY_T_HPP
#define ISDK_SELLBACKPURCHASEENTRY_T_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct SellbackPurchaseEntry_t {
    SCHEMA_CLASS("client.dll", "SellbackPurchaseEntry_t");


    // --- Virtual functions (vtable RVA: 0x1AACE98, 6 total) ---
    VFUNC_RAW(0);                                           // sig: 40 53 48 83 EC 20 48 8B DA 48 8D 15 ? ? ...
    VFUNC_RAW(1);                                           // sig: 80 79 2C 00 74 09 48 83 C1 08 E9 ? ? ? ?... reads: 0x2C
    VFUNC_RAW(2);                                           // sig: 80 79 2C 00 74 09 48 83 C1 08 E9 ? ? ? ?... reads: 0x2C
    VFUNC_RAW(3);                                           // sig: 80 79 2C 00 74 09 48 83 C1 08 E9 ? ? ? ?... reads: 0x2C
    VFUNC_RAW(4);                                           // sig: 80 79 2C 00 4C 8B C9 74 0C 48 83 C1 08 4... reads: 0x2C
    VFUNC_RAW(5);                                           // sig: 48 8B 05 ? ? ? ? C3 CC CC CC CC CC CC CC...
};

} // namespace sdk

#endif // ISDK_SELLBACKPURCHASEENTRY_T_HPP

