// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: SimpleConstraintSoundProfile (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_SIMPLECONSTRAINTSOUNDPROFILE_HPP
#define ISDK_SIMPLECONSTRAINTSOUNDPROFILE_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct SimpleConstraintSoundProfile {
    SCHEMA_CLASS("client.dll", "SimpleConstraintSoundProfile");

};

} // namespace sdk

#endif // ISDK_SIMPLECONSTRAINTSOUNDPROFILE_HPP

