// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: SndBeatEventKeyedFloats_t (runtime-resolved offsets)
// Module: client.dll
// Parent: SndBeatEventKeys_t
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_SNDBEATEVENTKEYEDFLOATS_T_HPP
#define ISDK_SNDBEATEVENTKEYEDFLOATS_T_HPP

#include "../schema_runtime.hpp"
#include "SndBeatEventKeys_t.hpp"

namespace sdk {

struct SndBeatEventKeyedFloats_t : SndBeatEventKeys_t {
    SCHEMA_CLASS("client.dll", "SndBeatEventKeyedFloats_t");

};

} // namespace sdk

#endif // ISDK_SNDBEATEVENTKEYEDFLOATS_T_HPP

