// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: SndBeatEventKeys_t (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_SNDBEATEVENTKEYS_T_HPP
#define ISDK_SNDBEATEVENTKEYS_T_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct SndBeatEventKeys_t {
    SCHEMA_CLASS("client.dll", "SndBeatEventKeys_t");

};

} // namespace sdk

#endif // ISDK_SNDBEATEVENTKEYS_T_HPP

