// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: sndopvarlatchdata_t (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_SNDOPVARLATCHDATA_T_HPP
#define ISDK_SNDOPVARLATCHDATA_T_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct sndopvarlatchdata_t {
    SCHEMA_CLASS("client.dll", "sndopvarlatchdata_t");


    // --- Virtual functions (vtable RVA: 0x199EBD0, 7 total) ---
};

} // namespace sdk

#endif // ISDK_SNDOPVARLATCHDATA_T_HPP

