// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: ViewAngleServerChange_t (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_VIEWANGLESERVERCHANGE_T_HPP
#define ISDK_VIEWANGLESERVERCHANGE_T_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct ViewAngleServerChange_t {
    SCHEMA_CLASS("client.dll", "ViewAngleServerChange_t");


    // --- Virtual functions (vtable RVA: 0x19C2038, 6 total) ---
};

} // namespace sdk

#endif // ISDK_VIEWANGLESERVERCHANGE_T_HPP

