// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: VPhysicsCollisionAttribute_t (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_VPHYSICSCOLLISIONATTRIBUTE_T_HPP
#define ISDK_VPHYSICSCOLLISIONATTRIBUTE_T_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct VPhysicsCollisionAttribute_t {
    SCHEMA_CLASS("client.dll", "VPhysicsCollisionAttribute_t");


    // --- Virtual functions (vtable RVA: 0x199EAB0, 8 total) ---
};

} // namespace sdk

#endif // ISDK_VPHYSICSCOLLISIONATTRIBUTE_T_HPP

