// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: WeaponPurchaseTracker_t (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_WEAPONPURCHASETRACKER_T_HPP
#define ISDK_WEAPONPURCHASETRACKER_T_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct WeaponPurchaseTracker_t {
    SCHEMA_CLASS("client.dll", "WeaponPurchaseTracker_t");


    // --- Virtual functions (vtable RVA: 0x1AA9D70, 5 total) ---
};

} // namespace sdk

#endif // ISDK_WEAPONPURCHASETRACKER_T_HPP

