// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: WeaponPurchaseCount_t (runtime-resolved offsets)
// Module: client.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_WEAPONPURCHASECOUNT_T_HPP
#define ISDK_WEAPONPURCHASECOUNT_T_HPP

#include "../schema_runtime.hpp"

namespace sdk {

struct WeaponPurchaseCount_t {
    SCHEMA_CLASS("client.dll", "WeaponPurchaseCount_t");


    // --- Virtual functions (vtable RVA: 0x1AA9D38, 6 total) ---
};

} // namespace sdk

#endif // ISDK_WEAPONPURCHASECOUNT_T_HPP

