// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Enums for module: animationsystem.dll
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_ANIMATIONSYSTEM_ENUMS_HPP
#define ISDK_ANIMATIONSYSTEM_ENUMS_HPP

#include <cstdint>

namespace sdk::enums::animationsystem {

enum class AimMatrixBlendMode : int32_t {
    AimMatrixBlendMode_None = 0,
    AimMatrixBlendMode_Additive = 1,
    AimMatrixBlendMode_ModelSpaceAdditive = 2,
    AimMatrixBlendMode_BoneMask = 3,
};

enum class AnimNodeNetworkMode : int32_t {
    ServerAuthoritative = 0,
    ClientSimulate = 1,
};

enum class AnimParamButton_t : int32_t {
    ANIMPARAM_BUTTON_NONE = 0,
    ANIMPARAM_BUTTON_DPAD_UP = 1,
    ANIMPARAM_BUTTON_DPAD_RIGHT = 2,
    ANIMPARAM_BUTTON_DPAD_DOWN = 3,
    ANIMPARAM_BUTTON_DPAD_LEFT = 4,
    ANIMPARAM_BUTTON_A = 5,
    ANIMPARAM_BUTTON_B = 6,
    ANIMPARAM_BUTTON_X = 7,
    ANIMPARAM_BUTTON_Y = 8,
    ANIMPARAM_BUTTON_LEFT_SHOULDER = 9,
    ANIMPARAM_BUTTON_RIGHT_SHOULDER = 10,
    ANIMPARAM_BUTTON_LTRIGGER = 11,
    ANIMPARAM_BUTTON_RTRIGGER = 12,
};

enum class AnimParamNetworkSetting : int32_t {
    Auto = 0,
    AlwaysNetwork = 1,
    NeverNetwork = 2,
};

enum class AnimParamType_t : uint8_t {
    ANIMPARAM_UNKNOWN = 0,
    ANIMPARAM_BOOL = 1,
    ANIMPARAM_ENUM = 2,
    ANIMPARAM_INT = 3,
    ANIMPARAM_FLOAT = 4,
    ANIMPARAM_VECTOR = 5,
    ANIMPARAM_QUATERNION = 6,
    ANIMPARAM_GLOBALSYMBOL = 7,
    ANIMPARAM_COUNT = 8,
};

enum class AnimParamVectorType_t : int32_t {
    ANIMPARAM_VECTOR_TYPE_NONE = 0,
    ANIMPARAM_VECTOR_TYPE_POSITION_WS = 1,
    ANIMPARAM_VECTOR_TYPE_POSITION_LS = 2,
    ANIMPARAM_VECTOR_TYPE_DIRECTION_WS = 3,
    ANIMPARAM_VECTOR_TYPE_DIRECTION_LS = 4,
};

enum class AnimScriptType : int16_t {
    ANIMSCRIPT_TYPE_INVALID = -1,
    ANIMSCRIPT_FUSE_GENERAL = 0,
    ANIMSCRIPT_FUSE_STATEMACHINE = 1,
};

enum class AnimValueSource : int32_t {
    MoveHeading = 0,
    MoveSpeed = 1,
    ForwardSpeed = 2,
    StrafeSpeed = 3,
    FacingHeading = 4,
    LookHeading = 5,
    LookHeadingNormalized = 6,
    LookPitch = 7,
    LookDistance = 8,
    Parameter = 9,
    WayPointHeading = 10,
    WayPointDistance = 11,
    BoundaryRadius = 12,
    TargetMoveHeading = 13,
    TargetMoveSpeed = 14,
    AccelerationHeading = 15,
    AccelerationSpeed = 16,
    SlopeHeading = 17,
    SlopeAngle = 18,
    SlopePitch = 19,
    SlopeYaw = 20,
    GoalDistance = 21,
    AccelerationLeftRight = 22,
    AccelerationFrontBack = 23,
    RootMotionSpeed = 24,
    RootMotionTurnSpeed = 25,
    MoveHeadingRelativeToLookHeading = 26,
    MaxMoveSpeed = 27,
    FingerCurl_Thumb = 28,
    FingerCurl_Index = 29,
    FingerCurl_Middle = 30,
    FingerCurl_Ring = 31,
    FingerCurl_Pinky = 32,
    FingerSplay_Thumb_Index = 33,
    FingerSplay_Index_Middle = 34,
    FingerSplay_Middle_Ring = 35,
    FingerSplay_Ring_Pinky = 36,
};

enum class AnimVectorSource : int32_t {
    MoveDirection = 0,
    FacingPosition = 1,
    LookDirection = 2,
    VectorParameter = 3,
    WayPointDirection = 4,
    Acceleration = 5,
    SlopeNormal = 6,
    SlopeNormal_WorldSpace = 7,
    LookTarget = 8,
    LookTarget_WorldSpace = 9,
    WayPointPosition = 10,
    GoalPosition = 11,
    RootMotionVelocity = 12,
    ManualTarget_WorldSpace = 13,
};

enum class AnimationProcessingType_t : int32_t {
    ANIMATION_PROCESSING_SERVER_SIMULATION = 0,
    ANIMATION_PROCESSING_CLIENT_SIMULATION = 1,
    ANIMATION_PROCESSING_CLIENT_PREDICTION = 2,
    ANIMATION_PROCESSING_CLIENT_INTERPOLATION = 3,
    ANIMATION_PROCESSING_CLIENT_RENDER = 4,
    ANIMATION_PROCESSING_MAX = 5,
};

enum class AnimationSnapshotType_t : int32_t {
    ANIMATION_SNAPSHOT_SERVER_SIMULATION = 0,
    ANIMATION_SNAPSHOT_CLIENT_SIMULATION = 1,
    ANIMATION_SNAPSHOT_CLIENT_PREDICTION = 2,
    ANIMATION_SNAPSHOT_CLIENT_INTERPOLATION = 3,
    ANIMATION_SNAPSHOT_CLIENT_RENDER = 4,
    ANIMATION_SNAPSHOT_FINAL_COMPOSITE = 5,
    ANIMATION_SNAPSHOT_MAX = 6,
};

enum class AnimationType_t : int32_t {
    ANIMATION_TYPE_FIXED_RATE = 0,
    ANIMATION_TYPE_FIT_LIFETIME = 1,
    ANIMATION_TYPE_MANUAL_FRAMES = 2,
};

enum class BinaryNodeChildOption : int32_t {
    Child1 = 0,
    Child2 = 1,
};

enum class BinaryNodeTiming : int32_t {
    UseChild1 = 0,
    UseChild2 = 1,
    SyncChildren = 2,
};

enum class Blend2DMode : int32_t {
    Blend2DMode_General = 0,
    Blend2DMode_Directional = 1,
};

enum class BlendKeyType : int32_t {
    BlendKey_UserValue = 0,
    BlendKey_Velocity = 1,
    BlendKey_Distance = 2,
    BlendKey_RemainingDistance = 3,
};

enum class BoneMaskBlendSpace : int32_t {
    BlendSpace_Parent = 0,
    BlendSpace_Model = 1,
    BlendSpace_Model_RotationOnly = 2,
    BlendSpace_Model_TranslationOnly = 3,
};

enum class BoneTransformSpace_t : int32_t {
    BoneTransformSpace_Invalid = -1,
    BoneTransformSpace_Parent = 0,
    BoneTransformSpace_Model = 1,
    BoneTransformSpace_World = 2,
};

enum class CAnimationGraphVisualizerPrimitiveType : int32_t {
    ANIMATIONGRAPHVISUALIZERPRIMITIVETYPE_Text = 0,
    ANIMATIONGRAPHVISUALIZERPRIMITIVETYPE_Sphere = 1,
    ANIMATIONGRAPHVISUALIZERPRIMITIVETYPE_Line = 2,
    ANIMATIONGRAPHVISUALIZERPRIMITIVETYPE_Pie = 3,
    ANIMATIONGRAPHVISUALIZERPRIMITIVETYPE_Axis = 4,
};

enum class CNmCurrentSyncEventNode::InfoType_t : uint8_t {
    IndexAndPercentage = 0,
    IndexOnly = 1,
    PercentageOnly = 2,
};

enum class CNmEventRelevance_t : int32_t {
    ClientOnly = 0,
    ServerOnly = 1,
    ClientAndServer = 2,
};

enum class CNmEventTargetEntity_t : int32_t {
    Self = 0,
    Weapon = 1,
    HeldItem = 2,
    Custom = 3,
};

enum class CNmFloatAngleMathNode::Operation_t : uint8_t {
    ClampTo180 = 0,
    ClampTo360 = 1,
    FlipHemisphere = 2,
    FlipHemisphereNegate = 3,
};

enum class CNmFloatComparisonNode::Comparison_t : uint8_t {
    GreaterThanEqual = 0,
    LessThanEqual = 1,
    NearEqual = 2,
    GreaterThan = 3,
    LessThan = 4,
};

enum class CNmFloatMathNode::Operator_t : uint8_t {
    Add = 0,
    Sub = 1,
    Mul = 2,
    Div = 3,
    Mod = 4,
    Abs = 5,
    Negate = 6,
    Floor = 7,
    Ceiling = 8,
    IntegerPart = 9,
    FractionalPart = 10,
    InverseFractionalPart = 11,
};

enum class CNmIDComparisonNode::Comparison_t : uint8_t {
    Matches = 0,
    DoesntMatch = 1,
};

enum class CNmParticleEvent::Type_t : int32_t {
    Create = 0,
    Create_CFG = 1,
};

enum class CNmRootMotionData::SamplingMode_t : uint8_t {
    Delta = 0,
    WorldSpace = 1,
};

enum class CNmRootMotionOverrideNode::OverrideFlags_t : uint8_t {
    AllowMoveX = 0,
    AllowMoveY = 1,
    AllowMoveZ = 2,
    AllowFacingPitch = 3,
    ListenForEvents = 4,
};

enum class CNmSoundEvent::Position_t : int32_t {
    None = 0,
    World = 1,
    EntityPos = 2,
    EntityEyePos = 3,
    EntityAttachment = 4,
};

enum class CNmStateNode::TimedEvent_t::Comparison_t : uint8_t {
    LessThanEqual = 0,
    GreaterThanEqual = 1,
};

enum class CNmSyncEventIndexConditionNode::TriggerMode_t : uint8_t {
    ExactlyAtEventIndex = 0,
    GreaterThanEqualToEventIndex = 1,
};

enum class CNmTargetInfoNode::Info_t : int32_t {
    AngleHorizontal = 0,
    AngleVertical = 1,
    Distance = 2,
    DistanceHorizontalOnly = 3,
    DistanceVerticalOnly = 4,
    DeltaOrientationX = 5,
    DeltaOrientationY = 6,
    DeltaOrientationZ = 7,
};

enum class CNmTargetWarpNode::TargetUpdateRule_t : uint8_t {
    None = 0,
    Recalculate = 1,
    Offset = 2,
    RecalculateOrOffset = 3,
};

enum class CNmTimeConditionNode::ComparisonType_t : uint8_t {
    PercentageThroughState = 0,
    PercentageThroughSyncEvent = 1,
    ElapsedTime = 2,
};

enum class CNmTimeConditionNode::Operator_t : uint8_t {
    LessThan = 0,
    LessThanEqual = 1,
    GreaterThan = 2,
    GreaterThanEqual = 3,
};

enum class CNmTransitionNode::TransitionOptions_t : uint8_t {
    None = 0,
    ClampDuration = 1,
    Synchronized = 2,
    MatchSourceTime = 3,
    MatchSyncEventIndex = 4,
    MatchSyncEventID = 5,
    MatchSyncEventPercentage = 6,
    PreferClosestSyncEventID = 7,
    MatchTimeInSeconds = 8,
    OffsetTimeInSeconds = 9,
};

enum class CNmVectorInfoNode::Info_t : uint8_t {
    X = 0,
    Y = 1,
    Z = 2,
    Length = 3,
    AngleHorizontal = 4,
    AngleVertical = 5,
};

enum class ChoiceBlendMethod : int32_t {
    SingleBlendTime = 0,
    PerChoiceBlendTimes = 1,
};

enum class ChoiceChangeMethod : int32_t {
    OnReset = 0,
    OnCycleEnd = 1,
    OnResetOrCycleEnd = 2,
};

enum class ChoiceMethod : int32_t {
    WeightedRandom = 0,
    WeightedRandomNoRepeat = 1,
    Iterate = 2,
    IterateRandom = 3,
};

enum class DampingSpeedFunction : int32_t {
    NoDamping = 0,
    Constant = 1,
    Spring = 2,
    AsymmetricSpring = 3,
};

enum class EDemoBoneSelectionMode : int32_t {
    CaptureAllBones = 0,
    CaptureSelectedBones = 1,
};

enum class EIKEndEffectorRotationFixUpMode : int32_t {
    None = 0,
    MatchTargetOrientation = 1,
    LookAtTargetForward = 2,
    MaintainParentOrientation = 3,
    Count = 4,
};

enum class EPulseGraphExecutionHistoryFlag : int32_t {
    NO_FLAGS = 0,
    CURSOR_ADD_TAG = 1,
    CURSOR_REMOVE_TAG = 2,
    CURSOR_RETIRED = 4,
    REQUIREMENT_PASS = 8,
    REQUIREMENT_FAIL = 16,
};

enum class FacingMode : uint8_t {
    FacingMode_Invalid = 0,
    FacingMode_Manual = 1,
    FacingMode_Path = 2,
    FacingMode_LookTarget = 3,
    FacingMode_ManualPosition = 4,
};

enum class FieldNetworkOption : int32_t {
    Auto = 0,
    ForceEnable = 1,
    ForceDisable = 2,
};

enum class FlexOpCode_t : int32_t {
    FLEX_OP_CONST = 1,
    FLEX_OP_FETCH1 = 2,
    FLEX_OP_FETCH2 = 3,
    FLEX_OP_ADD = 4,
    FLEX_OP_SUB = 5,
    FLEX_OP_MUL = 6,
    FLEX_OP_DIV = 7,
    FLEX_OP_NEG = 8,
    FLEX_OP_EXP = 9,
    FLEX_OP_OPEN = 10,
    FLEX_OP_CLOSE = 11,
    FLEX_OP_COMMA = 12,
    FLEX_OP_MAX = 13,
    FLEX_OP_MIN = 14,
    FLEX_OP_2WAY_0 = 15,
    FLEX_OP_2WAY_1 = 16,
    FLEX_OP_NWAY = 17,
    FLEX_OP_COMBO = 18,
    FLEX_OP_DOMINATE = 19,
    FLEX_OP_DME_LOWER_EYELID = 20,
    FLEX_OP_DME_UPPER_EYELID = 21,
    FLEX_OP_SQRT = 22,
    FLEX_OP_REMAPVALCLAMPED = 23,
    FLEX_OP_SIN = 24,
    FLEX_OP_COS = 25,
    FLEX_OP_ABS = 26,
};

enum class FootFallTagFoot_t : int32_t {
    FOOT1 = 0,
    FOOT2 = 1,
    FOOT3 = 2,
    FOOT4 = 3,
    FOOT5 = 4,
    FOOT6 = 5,
    FOOT7 = 6,
    FOOT8 = 7,
};

enum class FootLockSubVisualization : int32_t {
    FOOTLOCKSUBVISUALIZATION_ReachabilityAnalysis = 0,
    FOOTLOCKSUBVISUALIZATION_IKSolve = 1,
};

enum class FootPinningTimingSource : int32_t {
    FootMotion = 0,
    Tag = 1,
    Parameter = 2,
};

enum class FootstepJumpPhase_t : uint8_t {
    Unknown = 0,
    NotJumping = 1,
    Jumping = 2,
    Landing = 4,
};

enum class FootstepLandedFootSoundType_t : int32_t {
    FOOTSOUND_Left = 0,
    FOOTSOUND_Right = 1,
    FOOTSOUND_UseOverrideSound = 2,
};

enum class GPUParticleCollisionMode_t : int32_t {
    PARTICLE_GPU_COLLISION_MODE_RT = 0,
    PARTICLE_GPU_COLLISION_MODE_DEPTH = 1,
    PARTICLE_GPU_COLLISION_MODE_HYBRID = 2,
};

enum class HandshakeTagState_t : uint8_t {
    eInactive = 0,
    eActive = 1,
    eMomentarilyInactive = 2,
};

enum class HandshakeTagType_t : int32_t {
    eInvalid = -1,
    eTask = 0,
    eMovement = 1,
    eCount = 2,
};

enum class IKChannelMode : int32_t {
    TwoBone = 0,
    TwoBone_Translate = 1,
    OneBone = 2,
    OneBone_Translate = 3,
};

enum class IKSolverType : int32_t {
    IKSOLVER_Perlin = 0,
    IKSOLVER_TwoBone = 1,
    IKSOLVER_Fabrik = 2,
    IKSOLVER_DogLeg3Bone = 3,
    IKSOLVER_CCD = 4,
    IKSOLVER_COUNT = 5,
};

enum class IKTargetCoordinateSystem : int32_t {
    IKTARGETCOORDINATESYSTEM_WorldSpace = 0,
    IKTARGETCOORDINATESYSTEM_ModelSpace = 1,
    IKTARGETCOORDINATESYSTEM_COUNT = 2,
};

enum class IKTargetSource : int32_t {
    IKTARGETSOURCE_Bone = 0,
    IKTARGETSOURCE_AnimgraphParameter = 1,
    IKTARGETSOURCE_COUNT = 2,
};

enum class IkEndEffectorType : int32_t {
    IkEndEffector_Attachment = 0,
    IkEndEffector_Bone = 1,
};

enum class IkTargetType : int32_t {
    IkTarget_Attachment = 0,
    IkTarget_Bone = 1,
    IkTarget_Parameter_ModelSpace = 2,
    IkTarget_Parameter_WorldSpace = 3,
};

enum class JiggleBoneSimSpace : int32_t {
    SimSpace_Local = 0,
    SimSpace_Model = 1,
    SimSpace_World = 2,
};

enum class JumpCorrectionMethod : int32_t {
    ScaleMotion = 0,
    AddCorrectionDelta = 1,
};

enum class LinearRootMotionBlendMode_t : int32_t {
    LERP = 0,
    NLERP = 1,
    SLERP = 2,
};

enum class MatterialAttributeTagType_t : int32_t {
    MATERIAL_ATTRIBUTE_TAG_VALUE = 0,
    MATERIAL_ATTRIBUTE_TAG_COLOR = 1,
};

enum class MeshDrawPrimitiveFlags_t : int32_t {
    MESH_DRAW_FLAGS_NONE = 0,
    MESH_DRAW_FLAGS_USE_SHADOW_FAST_PATH = 1,
    MESH_DRAW_FLAGS_USE_COMPRESSED_NORMAL_TANGENT = 2,
    MESH_DRAW_INPUT_LAYOUT_IS_NOT_MATCHED_TO_MATERIAL = 8,
    MESH_DRAW_FLAGS_USE_COMPRESSED_PER_VERTEX_LIGHTING = 16,
    MESH_DRAW_FLAGS_USE_UNCOMPRESSED_PER_VERTEX_LIGHTING = 32,
    MESH_DRAW_FLAGS_CAN_BATCH_WITH_DYNAMIC_SHADER_CONSTANTS = 64,
    MESH_DRAW_FLAGS_DRAW_LAST = 128,
};

enum class ModelBoneFlexComponent_t : int32_t {
    MODEL_BONE_FLEX_INVALID = -1,
    MODEL_BONE_FLEX_TX = 0,
    MODEL_BONE_FLEX_TY = 1,
    MODEL_BONE_FLEX_TZ = 2,
};

enum class ModelConfigAttachmentType_t : int32_t {
    MODEL_CONFIG_ATTACHMENT_INVALID = -1,
    MODEL_CONFIG_ATTACHMENT_BONE_OR_ATTACHMENT = 0,
    MODEL_CONFIG_ATTACHMENT_ROOT_RELATIVE = 1,
    MODEL_CONFIG_ATTACHMENT_BONEMERGE = 2,
    MODEL_CONFIG_ATTACHMENT_COUNT = 3,
};

enum class ModelMeshBufferUsage_t : uint8_t {
    MESH_BUFFER_USAGE_NONE = 0,
    MESH_BUFFER_USAGE_VB = 1,
    MESH_BUFFER_USAGE_IB = 2,
    MESH_BUFFER_USAGE_ADJACENCY = 4,
    MESH_BUFFER_USAGE_MESHLET_TRIS = 8,
    MESH_BUFFER_USAGE_RT_PROXY = 16,
    MESH_BUFFER_USAGE_VERTEX_ALBEDO = 32,
    MESH_BUFFER_USAGE_VERTEX_EMISSIVE = 64,
};

enum class ModelSkeletonData_t::BoneFlags_t : int32_t {
    FLAG_NO_BONE_FLAGS = 0,
    FLAG_BONEFLEXDRIVER = 4,
    FLAG_CLOTH = 8,
    FLAG_PHYSICS = 16,
    FLAG_ATTACHMENT = 32,
    FLAG_ANIMATION = 64,
    FLAG_MESH = 128,
    FLAG_HITBOX = 256,
    FLAG_BONE_USED_BY_VERTEX_LOD0 = 1024,
    FLAG_BONE_USED_BY_VERTEX_LOD1 = 2048,
    FLAG_BONE_USED_BY_VERTEX_LOD2 = 4096,
    FLAG_BONE_USED_BY_VERTEX_LOD3 = 8192,
    FLAG_BONE_USED_BY_VERTEX_LOD4 = 16384,
    FLAG_BONE_USED_BY_VERTEX_LOD5 = 32768,
    FLAG_BONE_USED_BY_VERTEX_LOD6 = 65536,
    FLAG_BONE_USED_BY_VERTEX_LOD7 = 131072,
    FLAG_BONE_MERGE_READ = 262144,
    FLAG_BONE_MERGE_WRITE = 524288,
    FLAG_ALL_BONE_FLAGS = 1048575,
    BLEND_PREALIGNED = 1048576,
    FLAG_RIGIDLENGTH = 2097152,
    FLAG_PROCEDURAL = 4194304,
};

enum class MoodType_t : int32_t {
    eMoodType_Head = 0,
    eMoodType_Body = 1,
};

enum class MorphBundleType_t : int32_t {
    MORPH_BUNDLE_TYPE_NONE = 0,
    MORPH_BUNDLE_TYPE_POSITION_SPEED = 1,
    MORPH_BUNDLE_TYPE_NORMAL_WRINKLE = 2,
    MORPH_BUNDLE_TYPE_COUNT = 3,
};

enum class MorphFlexControllerRemapType_t : int32_t {
    MORPH_FLEXCONTROLLER_REMAP_PASSTHRU = 0,
    MORPH_FLEXCONTROLLER_REMAP_2WAY = 1,
    MORPH_FLEXCONTROLLER_REMAP_NWAY = 2,
    MORPH_FLEXCONTROLLER_REMAP_EYELID = 3,
};

enum class MovementCapability_t : int32_t {
    eStrafe = 0,
    eIdleTurn = 1,
    eStart = 2,
    eStop = 3,
    eInstantStop = 4,
    eShuffle = 5,
    ePlantedTurn = 6,
    eUseStartAsPlantedTurn = 7,
    eLean = 8,
    eCount = 9,
};

enum class NPCPhysicsHullType_t : int32_t {
    eInvalid = 0,
    eGroundCapsule = 1,
    eCenteredCapsule = 2,
    eGenericCapsule = 3,
    eGroundBox = 4,
    eGroundCylinder = 5,
    eCenteredCylinder = 6,
};

enum class NmCachedValueMode_t : int32_t {
    OnEntry = 0,
    OnExit = 1,
};

enum class NmEasingFunction_t : uint8_t {
    Linear = 0,
    Quad = 1,
    Cubic = 2,
    Quart = 3,
    Quint = 4,
    Sine = 5,
    Expo = 6,
    Circ = 7,
    Back = 8,
};

enum class NmEasingOperation_t : uint8_t {
    Linear = 0,
    InQuad = 1,
    OutQuad = 2,
    InOutQuad = 3,
    InCubic = 4,
    OutCubic = 5,
    InOutCubic = 6,
    InQuart = 7,
    OutQuart = 8,
    InOutQuart = 9,
    InQuint = 10,
    OutQuint = 11,
    InOutQuint = 12,
    InSine = 13,
    OutSine = 14,
    InOutSine = 15,
    InExpo = 16,
    OutExpo = 17,
    InOutExpo = 18,
    InCirc = 19,
    OutCirc = 20,
    InOutCirc = 21,
    None = 22,
};

enum class NmEventConditionRules_t : uint8_t {
    LimitSearchToSourceState = 0,
    IgnoreInactiveEvents = 1,
    PreferHighestWeight = 2,
    PreferHighestProgress = 3,
    OperatorOr = 4,
    OperatorAnd = 5,
    SearchOnlyGraphEvents = 6,
    SearchOnlyAnimEvents = 7,
    SearchBothGraphAndAnimEvents = 8,
};

enum class NmFollowBoneMode_t : uint8_t {
    RotationAndTranslation = 0,
    RotationOnly = 1,
    TranslationOnly = 2,
};

enum class NmFootPhaseCondition_t : uint8_t {
    LeftFootDown = 0,
    LeftFootPassing = 1,
    LeftPhase = 4,
    RightFootDown = 2,
    RightFootPassing = 3,
    RightPhase = 5,
    None = 6,
};

enum class NmFootPhase_t : uint8_t {
    LeftFootDown = 0,
    RightFootPassing = 1,
    RightFootDown = 2,
    LeftFootPassing = 3,
    None = 4,
};

enum class NmFrameSnapEventMode_t : int32_t {
    Floor = 0,
    Round = 1,
};

enum class NmGraphDebugMode_t : int32_t {
    Off = 0,
    On = 1,
};

enum class NmGraphEventTypeCondition_t : uint8_t {
    Entry = 0,
    FullyInState = 1,
    Exit = 2,
    Timed = 3,
    Generic = 4,
    Any = 5,
};

enum class NmGraphValueType_t : uint8_t {
    Unknown = 0,
    Bool = 1,
    ID = 2,
    Float = 3,
    Vector = 4,
    Target = 5,
    BoneMask = 6,
    Pose = 7,
    Special = 8,
};

enum class NmIKBlendMode_t : uint8_t {
    Effector = 0,
    Pose = 1,
};

enum class NmPoseBlendMode_t : uint8_t {
    Overlay = 0,
    Additive = 1,
    ModelSpace = 2,
};

enum class NmRootMotionBlendMode_t : uint8_t {
    Blend = 0,
    Additive = 1,
    IgnoreSource = 2,
    IgnoreTarget = 3,
};

enum class NmTargetWarpAlgorithm_t : uint8_t {
    Lerp = 0,
    Hermite = 1,
    HermiteFeaturePreserving = 2,
    Bezier = 3,
};

enum class NmTargetWarpRule_t : uint8_t {
    WarpXY = 0,
    WarpZ = 1,
    WarpXYZ = 2,
    RotationOnly = 3,
    FixedSection = 4,
};

enum class NmTransitionRuleCondition_t : uint8_t {
    AnyAllowed = 0,
    FullyAllowed = 1,
    ConditionallyAllowed = 2,
    Blocked = 3,
};

enum class NmTransitionRule_t : uint8_t {
    AllowTransition = 0,
    ConditionallyAllowTransition = 1,
    BlockTransition = 2,
};

enum class OrientationWarpMode_t : int32_t {
    eInvalid = 0,
    eAngle = 1,
    eWorldPosition = 2,
};

enum class OrientationWarpRootMotionSource_t : int32_t {
    eAnimationOrProcedural = 0,
    eAnimationOnly = 1,
    eProceduralOnly = 2,
};

enum class OrientationWarpTargetOffsetMode_t : int32_t {
    eLiteralValue = 0,
    eParameter = 1,
    eAnimationMovementHeading = 2,
    eAnimationMovementHeadingAtEnd = 3,
};

enum class PFNoiseModifier_t : int32_t {
    PF_NOISE_MODIFIER_NONE = 0,
    PF_NOISE_MODIFIER_LINES = 1,
    PF_NOISE_MODIFIER_CLUMPS = 2,
    PF_NOISE_MODIFIER_RINGS = 3,
};

enum class PFNoiseTurbulence_t : int32_t {
    PF_NOISE_TURB_NONE = 0,
    PF_NOISE_TURB_HIGHLIGHT = 1,
    PF_NOISE_TURB_FEEDBACK = 2,
    PF_NOISE_TURB_LOOPY = 3,
    PF_NOISE_TURB_CONTRAST = 4,
    PF_NOISE_TURB_ALTERNATE = 5,
};

enum class PFNoiseType_t : int32_t {
    PF_NOISE_TYPE_PERLIN = 0,
    PF_NOISE_TYPE_SIMPLEX = 1,
    PF_NOISE_TYPE_WORLEY = 2,
    PF_NOISE_TYPE_CURL = 3,
};

enum class ParticleAttachment_t : int32_t {
    PATTACH_INVALID = -1,
    PATTACH_ABSORIGIN = 0,
    PATTACH_ABSORIGIN_FOLLOW = 1,
    PATTACH_CUSTOMORIGIN = 2,
    PATTACH_CUSTOMORIGIN_FOLLOW = 3,
    PATTACH_POINT = 4,
    PATTACH_POINT_FOLLOW = 5,
    PATTACH_EYES_FOLLOW = 6,
    PATTACH_OVERHEAD_FOLLOW = 7,
    PATTACH_WORLDORIGIN = 8,
    PATTACH_ROOTBONE_FOLLOW = 9,
    PATTACH_RENDERORIGIN_FOLLOW = 10,
    PATTACH_MAIN_VIEW = 11,
    PATTACH_WATERWAKE = 12,
    PATTACH_CENTER_FOLLOW = 13,
    PATTACH_CUSTOM_GAME_STATE_1 = 14,
    PATTACH_HEALTHBAR = 15,
    MAX_PATTACH_TYPES = 16,
};

enum class ParticleColorBlendMode_t : int32_t {
    PARTICLEBLEND_DEFAULT = 0,
    PARTICLEBLEND_OVERLAY = 1,
    PARTICLEBLEND_DARKEN = 2,
    PARTICLEBLEND_LIGHTEN = 3,
    PARTICLEBLEND_MULTIPLY = 4,
};

enum class ParticleColorBlendType_t : int32_t {
    PARTICLE_COLOR_BLEND_MULTIPLY = 0,
    PARTICLE_COLOR_BLEND_MULTIPLY2X = 1,
    PARTICLE_COLOR_BLEND_DIVIDE = 2,
    PARTICLE_COLOR_BLEND_ADD = 3,
    PARTICLE_COLOR_BLEND_SUBTRACT = 4,
    PARTICLE_COLOR_BLEND_MOD2X = 5,
    PARTICLE_COLOR_BLEND_SCREEN = 6,
    PARTICLE_COLOR_BLEND_MAX = 7,
    PARTICLE_COLOR_BLEND_MIN = 8,
    PARTICLE_COLOR_BLEND_REPLACE = 9,
    PARTICLE_COLOR_BLEND_AVERAGE = 10,
    PARTICLE_COLOR_BLEND_NEGATE = 11,
    PARTICLE_COLOR_BLEND_LUMINANCE = 12,
};

enum class ParticleDirectionNoiseType_t : int32_t {
    PARTICLE_DIR_NOISE_PERLIN = 0,
    PARTICLE_DIR_NOISE_CURL = 1,
    PARTICLE_DIR_NOISE_WORLEY_BASIC = 2,
};

enum class ParticleFloatBiasType_t : int32_t {
    PF_BIAS_TYPE_INVALID = -1,
    PF_BIAS_TYPE_STANDARD = 0,
    PF_BIAS_TYPE_GAIN = 1,
    PF_BIAS_TYPE_EXPONENTIAL = 2,
    PF_BIAS_TYPE_COUNT = 3,
};

enum class ParticleFloatInputMode_t : int32_t {
    PF_INPUT_MODE_INVALID = -1,
    PF_INPUT_MODE_CLAMPED = 0,
    PF_INPUT_MODE_LOOPED = 1,
    PF_INPUT_MODE_COUNT = 2,
};

enum class ParticleFloatMapType_t : int32_t {
    PF_MAP_TYPE_INVALID = -1,
    PF_MAP_TYPE_DIRECT = 0,
    PF_MAP_TYPE_MULT = 1,
    PF_MAP_TYPE_REMAP = 2,
    PF_MAP_TYPE_REMAP_BIASED = 3,
    PF_MAP_TYPE_CURVE = 4,
    PF_MAP_TYPE_NOTCHED = 5,
    PF_MAP_TYPE_ROUND = 6,
    PF_MAP_TYPE_COUNT = 7,
};

enum class ParticleFloatRandomMode_t : int32_t {
    PF_RANDOM_MODE_INVALID = -1,
    PF_RANDOM_MODE_CONSTANT = 0,
    PF_RANDOM_MODE_VARYING = 1,
    PF_RANDOM_MODE_COUNT = 2,
};

enum class ParticleFloatRoundType_t : int32_t {
    PF_ROUND_TYPE_INVALID = -1,
    PF_ROUND_TYPE_NEAREST = 0,
    PF_ROUND_TYPE_FLOOR = 1,
    PF_ROUND_TYPE_CEIL = 2,
    PF_ROUND_TYPE_COUNT = 3,
};

enum class ParticleFloatType_t : int32_t {
    PF_TYPE_INVALID = -1,
    PF_TYPE_LITERAL = 0,
    PF_TYPE_NAMED_VALUE = 1,
    PF_TYPE_RANDOM_UNIFORM = 2,
    PF_TYPE_RANDOM_BIASED = 3,
    PF_TYPE_COLLECTION_AGE = 4,
    PF_TYPE_ENDCAP_AGE = 5,
    PF_TYPE_CONTROL_POINT_COMPONENT = 6,
    PF_TYPE_CONTROL_POINT_CHANGE_AGE = 7,
    PF_TYPE_CONTROL_POINT_SPEED = 8,
    PF_TYPE_PARTICLE_DETAIL_LEVEL = 9,
    PF_TYPE_CONCURRENT_DEF_COUNT = 10,
    PF_TYPE_CLOSEST_CAMERA_DISTANCE = 11,
    PF_TYPE_SNAPSHOT_COUNT = 12,
    PF_TYPE_SNAPSHOT_CHANGED = 13,
    PF_TYPE_CONTROL_POINT_IS_SET = 14,
    PF_TYPE_RENDERER_CAMERA_DISTANCE = 15,
    PF_TYPE_RENDERER_CAMERA_DOT_PRODUCT = 16,
    PF_TYPE_PARTICLE_NOISE = 17,
    PF_TYPE_PARTICLE_AGE = 18,
    PF_TYPE_PARTICLE_AGE_NORMALIZED = 19,
    PF_TYPE_PARTICLE_FLOAT = 20,
    PF_TYPE_PARTICLE_INITIAL_FLOAT = 21,
    PF_TYPE_PARTICLE_VECTOR_COMPONENT = 22,
    PF_TYPE_PARTICLE_INITIAL_VECTOR_COMPONENT = 23,
    PF_TYPE_PARTICLE_SPEED = 24,
    PF_TYPE_PARTICLE_NUMBER = 25,
    PF_TYPE_PARTICLE_NUMBER_NORMALIZED = 26,
    PF_TYPE_PARTICLE_ROPE_SEGMENT = 27,
    PF_TYPE_PARTICLE_ROPE_SEGMENT_NORMALIZED = 28,
    PF_TYPE_PARTICLE_SCREENSPACE_CAMERA_DISTANCE = 29,
    PF_TYPE_PARTICLE_SCREENSPACE_CAMERA_DOT_PRODUCT = 30,
    PF_TYPE_COUNT = 31,
};

enum class ParticleModelType_t : int32_t {
    PM_TYPE_INVALID = 0,
    PM_TYPE_NAMED_VALUE_MODEL = 1,
    PM_TYPE_NAMED_VALUE_EHANDLE = 2,
    PM_TYPE_CONTROL_POINT = 3,
    PM_TYPE_COUNT = 4,
};

enum class ParticleSetMethod_t : int32_t {
    PARTICLE_SET_REPLACE_VALUE = 0,
    PARTICLE_SET_SCALE_INITIAL_VALUE = 1,
    PARTICLE_SET_ADD_TO_INITIAL_VALUE = 2,
    PARTICLE_SET_RAMP_CURRENT_VALUE = 3,
    PARTICLE_SET_SCALE_CURRENT_VALUE = 4,
    PARTICLE_SET_ADD_TO_CURRENT_VALUE = 5,
};

enum class ParticleTransformType_t : int32_t {
    PT_TYPE_INVALID = 0,
    PT_TYPE_NAMED_VALUE = 1,
    PT_TYPE_CONTROL_POINT = 2,
    PT_TYPE_CONTROL_POINT_RANGE = 3,
    PT_TYPE_COUNT = 4,
};

enum class ParticleVecType_t : int32_t {
    PVEC_TYPE_INVALID = -1,
    PVEC_TYPE_LITERAL = 0,
    PVEC_TYPE_LITERAL_COLOR = 1,
    PVEC_TYPE_NAMED_VALUE = 2,
    PVEC_TYPE_PARTICLE_VECTOR = 3,
    PVEC_TYPE_PARTICLE_INITIAL_VECTOR = 4,
    PVEC_TYPE_PARTICLE_VELOCITY = 5,
    PVEC_TYPE_PARTICLE_GRAVITY = 6,
    PVEC_TYPE_CP_VALUE = 7,
    PVEC_TYPE_CP_RELATIVE_POSITION = 8,
    PVEC_TYPE_CP_RELATIVE_DIR = 9,
    PVEC_TYPE_CP_RELATIVE_RANDOM_DIR = 10,
    PVEC_TYPE_FLOAT_COMPONENTS = 11,
    PVEC_TYPE_FLOAT_INTERP_CLAMPED = 12,
    PVEC_TYPE_FLOAT_INTERP_OPEN = 13,
    PVEC_TYPE_FLOAT_INTERP_GRADIENT = 14,
    PVEC_TYPE_RANDOM_UNIFORM = 15,
    PVEC_TYPE_RANDOM_UNIFORM_OFFSET = 16,
    PVEC_TYPE_CP_DELTA = 17,
    PVEC_TYPE_CLOSEST_CAMERA_POSITION = 18,
    PVEC_TYPE_COUNT = 19,
};

enum class PermModelInfo_t::FlagEnum : int32_t {
    FLAG_TRANSLUCENT = 1,
    FLAG_TRANSLUCENT_TWO_PASS = 2,
    FLAG_MODEL_IS_RUNTIME_COMBINED = 4,
    FLAG_SOURCE1_IMPORT = 8,
    FLAG_MODEL_PART_CHILD = 16,
    FLAG_NAV_GEN_NONE = 32,
    FLAG_NAV_GEN_HULL = 64,
    FLAG_NO_FORCED_FADE = 2048,
    FLAG_HAS_SKINNED_MESHES = 1024,
    FLAG_DO_NOT_CAST_SHADOWS = 131072,
    FLAG_FORCE_PHONEME_CROSSFADE = 4096,
    FLAG_NO_ANIM_EVENTS = 1048576,
    FLAG_ANIMATION_DRIVEN_FLEXES = 2097152,
    FLAG_IMPLICIT_BIND_POSE_SEQUENCE = 4194304,
    FLAG_MODEL_DOC = 8388608,
};

enum class PoseType_t : uint8_t {
    POSETYPE_STATIC = 0,
    POSETYPE_DYNAMIC = 1,
    POSETYPE_INVALID = 255,
};

enum class PulseApiFeature_t : int32_t {
    AF_NONE = 0,
    AF_ENTITIES = 1,
    AF_PANORAMA = 2,
    AF_PARTICLES = 8,
    AF_FAKE_ENTITIES = 16,
    AF_SELECTORS_WITHOUT_REQUIREMENTS = 32,
};

enum class PulseBestOutflowRules_t : int32_t {
    SORT_BY_NUMBER_OF_VALID_CRITERIA = 0,
    SORT_BY_OUTFLOW_INDEX = 1,
};

enum class PulseCursorCancelPriority_t : int32_t {
    None = 0,
    CancelOnSucceeded = 1,
    SoftCancel = 2,
    HardCancel = 3,
};

enum class PulseCursorWakePriority_t : int32_t {
    WakeElegantly = 0,
    WakeImmediate = 1,
};

enum class PulseDomainValueType_t : int32_t {
    INVALID = -1,
    ENTITY_NAME = 0,
    PANEL_ID = 1,
    COUNT = 2,
};

enum class PulseDurationStringFormat_t : int32_t {
    MM_SS_LEADING_ZERO = 0,
};

enum class PulseInstructionCode_t : int16_t {
    INVALID = 0,
    IMMEDIATE_HALT = 1,
    RETURN_VOID = 2,
    RETURN_VALUE = 3,
    NOP = 4,
    JUMP = 5,
    JUMP_COND = 6,
    CHUNK_LEAP = 7,
    CHUNK_LEAP_COND = 8,
    PULSE_CALL_SYNC = 9,
    PULSE_CALL_ASYNC_FIRE = 10,
    CREATE_CHILD_CURSOR_OUTFLOW = 11,
    CELL_INVOKE = 12,
    LIBRARY_INVOKE = 13,
    SET_VAR = 14,
    GET_VAR = 15,
    GET_VAR_DETACH = 16,
    DETACH_REGISTER = 17,
    SET_VAR_ARRAY_ELEMENT_1D = 18,
    SET_VAR_OBSERVABLE = 19,
    GET_CONST = 20,
    GET_ARRAY_ELEMENT = 21,
    GET_DOMAIN_VALUE = 22,
    COPY = 23,
    NOT = 24,
    NEGATE = 25,
    ADD = 26,
    SUB = 27,
    MUL = 28,
    DIV = 29,
    MOD = 30,
    LT = 31,
    LTE = 32,
    EQ = 33,
    NE = 34,
    AND = 35,
    OR = 36,
    SCALE = 37,
    SCALE_INV = 38,
    ELEMENT_ACCESS = 39,
    CONVERT_VALUE = 40,
    REINTERPRET_INSTANCE = 41,
    GET_BLACKBOARD_REFERENCE = 42,
    SET_BLACKBOARD_REFERENCE = 43,
    LAST_SERIALIZED_CODE = 44,
    NEGATE_INT = 45,
    NEGATE_FLOAT = 46,
    NEGATE_VEC2 = 47,
    NEGATE_VEC3 = 48,
    NEGATE_VEC4 = 49,
    ADD_INT = 50,
    ADD_FLOAT = 51,
    ADD_STRING = 52,
    ADD_VEC2 = 53,
    ADD_VEC3 = 54,
    ADD_VEC3WS_VEC3 = 55,
    ADD_VEC3_VEC3WS = 56,
    ADD_VEC4 = 57,
    ADD_GAMETIME_FLOAT = 58,
    ADD_FLOAT_GAMETIME = 59,
    SUB_INT = 60,
    SUB_FLOAT = 61,
    SUB_VEC2 = 62,
    SUB_VEC3 = 63,
    SUB_VEC3WS_VEC3 = 64,
    SUB_VEC3WS_VEC3WS = 65,
    SUB_VEC4 = 66,
    SUB_GAMETIME_FLOAT = 67,
    SUB_GAMETIME = 68,
    MUL_INT = 69,
    MUL_FLOAT = 70,
    DIV_FLOAT = 71,
    MOD_INT = 72,
    MOD_FLOAT = 73,
    LT_INT = 74,
    LT_FLOAT = 75,
    LT_GAMETIME = 76,
    LTE_INT = 77,
    LTE_FLOAT = 78,
    LTE_GAMETIME = 79,
    EQ_BOOL = 80,
    EQ_INT = 81,
    EQ_FLOAT = 82,
    EQ_VEC2 = 83,
    EQ_VEC3 = 84,
    EQ_VEC3WS = 85,
    EQ_VEC4 = 86,
    EQ_STRING = 87,
    EQ_ENTITY_NAME = 88,
    EQ_SCHEMA_ENUM = 89,
    EQ_EHANDLE = 90,
    EQ_PANEL_HANDLE = 91,
    EQ_OPAQUE_HANDLE = 92,
    EQ_TEST_HANDLE = 93,
    EQ_COLOR_RGB = 94,
    EQ_ARRAY = 95,
    EQ_GAMETIME = 96,
    NE_BOOL = 97,
    NE_INT = 98,
    NE_FLOAT = 99,
    NE_VEC2 = 100,
    NE_VEC3 = 101,
    NE_VEC3WS = 102,
    NE_VEC4 = 103,
    NE_STRING = 104,
    NE_ENTITY_NAME = 105,
    NE_SCHEMA_ENUM = 106,
    NE_EHANDLE = 107,
    NE_PANEL_HANDLE = 108,
    NE_OPAQUE_HANDLE = 109,
    NE_TEST_HANDLE = 110,
    NE_COLOR_RGB = 111,
    NE_ARRAY = 112,
    NE_GAMETIME = 113,
    SCALE_VEC3 = 114,
    SCALE_VEC2 = 115,
    SCALE_VEC4 = 116,
    SCALE_INV_VEC3 = 117,
    SCALE_INV_VEC2 = 118,
    SCALE_INV_VEC4 = 119,
    ELEMENT_ACCESS_VEC2 = 120,
    ELEMENT_ACCESS_VEC3 = 121,
    ELEMENT_ACCESS_VEC3WS = 122,
    ELEMENT_ACCESS_VEC4 = 123,
    ELEMENT_ACCESS_COLOR_RGB = 124,
    GET_CONST_INLINE_STORAGE = 125,
};

enum class PulseMethodCallMode_t : int32_t {
    SYNC_WAIT_FOR_COMPLETION = 0,
    ASYNC_FIRE_AND_FORGET = 1,
};

enum class PulseValueType_t : int32_t {
    PVAL_VOID = -1,
    PVAL_BOOL = 0,
    PVAL_INT = 1,
    PVAL_FLOAT = 2,
    PVAL_STRING = 3,
    PVAL_VEC2 = 4,
    PVAL_VEC3 = 5,
    PVAL_QANGLE = 6,
    PVAL_VEC3_WORLDSPACE = 7,
    PVAL_VEC4 = 8,
    PVAL_TRANSFORM = 9,
    PVAL_TRANSFORM_WORLDSPACE = 10,
    PVAL_COLOR_RGB = 11,
    PVAL_GAMETIME = 12,
    PVAL_EHANDLE = 13,
    PVAL_RESOURCE = 14,
    PVAL_RESOURCE_NAME = 15,
    PVAL_SNDEVT_GUID = 16,
    PVAL_SNDEVT_NAME = 17,
    PVAL_ENTITY_NAME = 18,
    PVAL_OPAQUE_HANDLE = 19,
    PVAL_TYPESAFE_INT = 20,
    PVAL_MODEL_MATERIAL_GROUP = 21,
    PVAL_CURSOR_FLOW = 22,
    PVAL_VARIANT = 23,
    PVAL_UNKNOWN = 24,
    PVAL_SCHEMA_ENUM = 25,
    PVAL_PANORAMA_PANEL_HANDLE = 26,
    PVAL_TEST_HANDLE = 27,
    PVAL_ARRAY = 28,
    PVAL_TYPESAFE_INT64 = 29,
    PVAL_PARTICLE_EHANDLE = 30,
    PVAL_ANIM_SEQUENCE = 31,
    PVAL_VDATA_CHOICE = 32,
    PVAL_COUNT = 33,
};

enum class PulseVariableKeysSource_t : int32_t {
    PRIVATE = 0,
    CPP = 1,
    VMAP = 2,
    VMDL = 3,
    XML = 4,
    VDATA = 5,
    COUNT = 6,
};

enum class RagdollPoseControl : int32_t {
    Absolute = 0,
};

enum class RenderMeshSlotType_t : uint8_t {
    RENDERMESH_SLOT_INVALID = -1,
    RENDERMESH_SLOT_PER_VERTEX = 0,
    RENDERMESH_SLOT_PER_INSTANCE = 1,
};

enum class ResetCycleOption : int32_t {
    Beginning = 0,
    SameCycleAsSource = 1,
    InverseSourceCycle = 2,
    FixedValue = 3,
    SameTimeAsSource = 4,
};

enum class ScriptedHeldWeaponBehavior_t : int32_t {
    eInvalid = -1,
    eHolster = 0,
    eDeploy = 1,
    eDrop = 2,
};

enum class ScriptedMoveTo_t : int32_t {
    eWait = 0,
    eMoveWithGait = 3,
    eTeleport = 4,
    eWaitFacing = 5,
    eObsoleteBackCompat1 = 1,
    eObsoleteBackCompat2 = 2,
};

enum class SelectorTagBehavior_t : int32_t {
    SelectorTagBehavior_OnWhileCurrent = 0,
    SelectorTagBehavior_OffWhenFinished = 1,
    SelectorTagBehavior_OffBeforeFinished = 2,
};

enum class SeqCmd_t : int32_t {
    SeqCmd_Nop = 0,
    SeqCmd_LinearDelta = 1,
    SeqCmd_FetchFrameRange = 2,
    SeqCmd_Slerp = 3,
    SeqCmd_Add = 4,
    SeqCmd_Subtract = 5,
    SeqCmd_Scale = 6,
    SeqCmd_Copy = 7,
    SeqCmd_Blend = 8,
    SeqCmd_Worldspace = 9,
    SeqCmd_Sequence = 10,
    SeqCmd_FetchCycle = 11,
    SeqCmd_FetchFrame = 12,
    SeqCmd_IKLockInPlace = 13,
    SeqCmd_IKRestoreAll = 14,
    SeqCmd_ReverseSequence = 15,
    SeqCmd_Transform = 16,
};

enum class SeqPoseSetting_t : int32_t {
    SEQ_POSE_SETTING_CONSTANT = 0,
    SEQ_POSE_SETTING_ROTATION = 1,
    SEQ_POSE_SETTING_POSITION = 2,
    SEQ_POSE_SETTING_VELOCITY = 3,
};

enum class SharedMovementGait_t : uint8_t {
    eInvalid = -1,
    eSlow = 0,
    eMedium = 1,
    eFast = 2,
    eVeryFast = 3,
    eCount = 4,
};

enum class SolveIKChainAnimNodeDebugSetting : int32_t {
    SOLVEIKCHAINANIMNODEDEBUGSETTING_None = 0,
    SOLVEIKCHAINANIMNODEDEBUGSETTING_X_Axis_Circle = 1,
    SOLVEIKCHAINANIMNODEDEBUGSETTING_Y_Axis_Circle = 2,
    SOLVEIKCHAINANIMNODEDEBUGSETTING_Z_Axis_Circle = 3,
    SOLVEIKCHAINANIMNODEDEBUGSETTING_Forward = 4,
    SOLVEIKCHAINANIMNODEDEBUGSETTING_Up = 5,
    SOLVEIKCHAINANIMNODEDEBUGSETTING_Left = 6,
};

enum class StanceOverrideMode : int32_t {
    Sequence = 0,
    Node = 1,
};

enum class StateActionBehavior : int32_t {
    STATETAGBEHAVIOR_ACTIVE_WHILE_CURRENT = 0,
    STATETAGBEHAVIOR_FIRE_ON_ENTER = 1,
    STATETAGBEHAVIOR_FIRE_ON_EXIT = 2,
    STATETAGBEHAVIOR_FIRE_ON_ENTER_AND_EXIT = 3,
    STATETAGBEHAVIOR_ACTIVE_WHILE_FULLY_BLENDED = 4,
};

enum class StepPhase : int32_t {
    StepPhase_OnGround = 0,
    StepPhase_InAir = 1,
};

enum class TagActionStatus : uint8_t {
    Inactive = 0,
    Active = 1,
    Fired = 2,
};

enum class TargetSelectorAngleMode_t : int32_t {
    eFacingHeading = 0,
    eMoveHeading = 1,
};

enum class TargetWarpAngleMode_t : int32_t {
    eFacingHeading = 0,
    eMoveHeading = 1,
};

enum class TargetWarpCorrectionMethod : int32_t {
    ScaleMotion = 0,
    AddCorrectionDelta = 1,
};

enum class TargetWarpTimingMethod : int32_t {
    ReachDestinationOnRootMotionEnd = 0,
    ReachDestinationOnWarpTagEnd = 1,
};

enum class VPhysXAggregateData_t::VPhysXFlagEnum_t : int32_t {
    FLAG_IS_POLYSOUP_GEOMETRY = 1,
    FLAG_LEVEL_COLLISION = 16,
    FLAG_IGNORE_SCALE_OBSOLETE_DO_NOT_USE = 32,
};

enum class VPhysXBodyPart_t::VPhysXFlagEnum_t : int32_t {
    FLAG_STATIC = 1,
    FLAG_KINEMATIC = 2,
    FLAG_JOINT = 4,
    FLAG_MASS = 8,
    FLAG_ALWAYS_DYNAMIC_ON_CLIENT = 16,
    FLAG_DISABLE_CCD = 32,
};

enum class VPhysXConstraintParams_t::EnumFlags0_t : int32_t {
    FLAG0_SHIFT_INTERPENETRATE = 0,
    FLAG0_SHIFT_CONSTRAIN = 1,
    FLAG0_SHIFT_BREAKABLE_FORCE = 2,
    FLAG0_SHIFT_BREAKABLE_TORQUE = 3,
};

enum class VPhysXJoint_t::Flags_t : int32_t {
    JOINT_FLAGS_NONE = 0,
    JOINT_FLAGS_BODY1_FIXED = 1,
    JOINT_FLAGS_USE_BLOCK_SOLVER = 2,
};

enum class VelocityMetricMode : uint8_t {
    DirectionOnly = 0,
    MagnitudeOnly = 1,
    DirectionAndMagnitude = 2,
};

enum class VertexAlbedoFormat_t : uint8_t {
    VERTEX_ALBEDO_NONE = 0,
    VERTEX_ALBEDO_8888 = 1,
    VERTEX_ALBEDO_565 = 2,
};

} // namespace sdk::enums::animationsystem

#endif // ISDK_ANIMATIONSYSTEM_ENUMS_HPP

