// Auto-generated by dezlock-dump (internal SDK) — DO NOT EDIT
// Class: CParticleCollectionBindingInstance (runtime-resolved offsets)
// Module: animationsystem.dll
// Parent: CBasePulseGraphInstance
// Generated: 2026-07-16T17:54:25
#pragma once
#ifndef ISDK_CPARTICLECOLLECTIONBINDINGINSTANCE_HPP
#define ISDK_CPARTICLECOLLECTIONBINDINGINSTANCE_HPP

#include "../schema_runtime.hpp"
#include "../client/CBasePulseGraphInstance.hpp"

namespace sdk {

struct CParticleCollectionBindingInstance : CBasePulseGraphInstance {
    SCHEMA_CLASS("animationsystem.dll", "CParticleCollectionBindingInstance");

};

} // namespace sdk

#endif // ISDK_CPARTICLECOLLECTIONBINDINGINSTANCE_HPP

