// Generated by cs2-sdk - https://cs2-sdk.com
// Resolved global RVAs, merged from the offset (pattern-scan) and
// Pattern (rip-relative) passes into one tree: offsets::<module>::Name
// (no dw / _ptr affixes).
#pragma once

#include <cstddef>
#include <cstdint>

namespace offsets {
    namespace animationsystem {
        constexpr std::ptrdiff_t AnimationSystemUtils_001 = 0x837ED0;
        constexpr std::ptrdiff_t AnimationSystem_001 = 0x82FDF0;
        constexpr std::ptrdiff_t pAnimationSystemUtils = 0x837EB0;
    }
    namespace client {
        constexpr std::ptrdiff_t CInputPtrGlobal = 0x209F570;
        constexpr std::ptrdiff_t CSGOInput = 0x23B95F0;
        constexpr std::ptrdiff_t ClientBugBugServic001_Client = 0x2093790;
        constexpr std::ptrdiff_t ClientToolsInfo_001 = 0x2093760;
        constexpr std::ptrdiff_t EmptyWorldService001_Client = 0x206F480;
        constexpr std::ptrdiff_t EntityList = 0x254EE60;
        constexpr std::ptrdiff_t GameClientExports001 = 0x2090400;
        constexpr std::ptrdiff_t GameEntitySystem = 0x254EE60;
        constexpr std::ptrdiff_t GameEntitySystem_highestEntityIndex = 0x2090;
        constexpr std::ptrdiff_t GameRules = 0x1A515A8;
        constexpr std::ptrdiff_t GetAbsOrigin = 0x219EE0;
        constexpr std::ptrdiff_t GetBombsiteACenter = 0x88BDB0;
        constexpr std::ptrdiff_t GetBombsiteBCenter = 0x88BE10;
        constexpr std::ptrdiff_t GlobalVars = 0x208FD60;
        constexpr std::ptrdiff_t GlowManager = 0x23A0708;
        constexpr std::ptrdiff_t LegacyGameUI001 = 0x20A3D00;
        constexpr std::ptrdiff_t LocalPlayerController = 0x237EBA0;
        constexpr std::ptrdiff_t LocalPlayerPawn = 0x23A4238;
        constexpr std::ptrdiff_t ManageGlowSceneObject = 0xB1B2B0;
        constexpr std::ptrdiff_t Prediction = 0x23A4140;
        constexpr std::ptrdiff_t Sensitivity = 0x23A1228;
        constexpr std::ptrdiff_t SetItemItemIdFunction = 0xDD7AE0;
        constexpr std::ptrdiff_t SetSceneObjectAttributeFloat4 = 0x1702B0;
        constexpr std::ptrdiff_t Source2Client002 = 0x239E6D0;
        constexpr std::ptrdiff_t Source2ClientConfig001 = 0x230BA00;
        constexpr std::ptrdiff_t Source2ClientPrediction001 = 0x23A4140;
        constexpr std::ptrdiff_t Source2ClientUI001 = 0x20A2210;
        constexpr std::ptrdiff_t TransformScale3dVMT = 0x1B55CB0;
        constexpr std::ptrdiff_t TransformTranslate3dVMT = 0x1B4D750;
        constexpr std::ptrdiff_t ViewAngles = 0x23B9C78;
        constexpr std::ptrdiff_t ViewMatrix = 0x23A9340;
        constexpr std::ptrdiff_t ViewRender = 0x23A9398;
        constexpr std::ptrdiff_t WeaponC4 = 0x231C9D0;
        constexpr std::ptrdiff_t pCSGOInput = 0x209F570;
        constexpr std::ptrdiff_t pClientMode = 0x23B73B0;
        constexpr std::ptrdiff_t pCvar = 0x25C8358;
        constexpr std::ptrdiff_t pEntityList = 0x254EE60;
        constexpr std::ptrdiff_t pEntitySystem = 0x238C530;
        constexpr std::ptrdiff_t pGameEntitySystem = 0x254EE60;
        constexpr std::ptrdiff_t pGameEventManager = 0x238C590;
        constexpr std::ptrdiff_t pGameRules = 0x23A39D8;
        constexpr std::ptrdiff_t pGameTraceManager = 0x2083B00;
        constexpr std::ptrdiff_t pGetBBox = 0x23A39D8;
        constexpr std::ptrdiff_t pGlobalVariables = 0x208FD60;
        constexpr std::ptrdiff_t pGlowManager = 0x23A0708;
        constexpr std::ptrdiff_t pHudPanel = 0x2414348;
        constexpr std::ptrdiff_t pLocalPlayerController = 0x237EBA0;
        constexpr std::ptrdiff_t pMainMenuPanel = 0x2407B60;
        constexpr std::ptrdiff_t pParticleManager = 0x2083EF8;
        constexpr std::ptrdiff_t pPlantedC4s = 0x236E674;
        constexpr std::ptrdiff_t pPrediction = 0x23A4140;
        constexpr std::ptrdiff_t pSensitivity = 0x23A1220;
        constexpr std::ptrdiff_t pUiEngine = 0x2566290;
        constexpr std::ptrdiff_t pVPhys2World = 0x2083B00;
        constexpr std::ptrdiff_t pViewMatrix = 0x23A9340;
        constexpr std::ptrdiff_t pViewRender = 0x23A9398;
        constexpr std::ptrdiff_t pViewToProjectionMatrix = 0x23A9300;
        constexpr std::ptrdiff_t pWeaponC4 = 0x231C9D0;
        constexpr std::ptrdiff_t pWorldToProjectionMatrix = 0x23A9340;
    }
    namespace engine2 {
        constexpr std::ptrdiff_t BenchmarkService001 = 0x615320;
        constexpr std::ptrdiff_t BugBugService001 = 0x615420;
        constexpr std::ptrdiff_t BugService001 = 0x8CDCD0;
        constexpr std::ptrdiff_t BuildNumber = 0x60F594;
        constexpr std::ptrdiff_t ClientServerEngineLoopService_001 = 0x90F3D0;
        constexpr std::ptrdiff_t ClientServerSharedHandleSystem001 = 0x90E9A0;
        constexpr std::ptrdiff_t EngineGameUI001 = 0x612C70;
        constexpr std::ptrdiff_t EngineServiceMgr001 = 0x90ECB0;
        constexpr std::ptrdiff_t GameEventSystemClientV001 = 0x90EF90;
        constexpr std::ptrdiff_t GameEventSystemServerV001 = 0x90F0C0;
        constexpr std::ptrdiff_t GameResourceServiceClientV001 = 0x615460;
        constexpr std::ptrdiff_t GameResourceServiceServerV001 = 0x6154C0;
        constexpr std::ptrdiff_t GameUIService_001 = 0x8CE120;
        constexpr std::ptrdiff_t HostStateMgr001 = 0x615CA0;
        constexpr std::ptrdiff_t INETSUPPORT_001 = 0x60E960;
        constexpr std::ptrdiff_t InputService_001 = 0x8CE410;
        constexpr std::ptrdiff_t KeyValueCache001 = 0x615D50;
        constexpr std::ptrdiff_t MapListService_001 = 0x90D280;
        constexpr std::ptrdiff_t NetworkClientService_001 = 0x90D410;
        constexpr std::ptrdiff_t NetworkGameClient = 0x90D4B0;
        constexpr std::ptrdiff_t NetworkGameClient_clientTickCount = 0x378;
        constexpr std::ptrdiff_t NetworkGameClient_deltaTick = 0x24C;
        constexpr std::ptrdiff_t NetworkGameClient_localPlayer = 0xF8;
        constexpr std::ptrdiff_t NetworkGameClient_maxClients = 0x240;
        constexpr std::ptrdiff_t NetworkGameClient_serverTickCount = 0x24C;
        constexpr std::ptrdiff_t NetworkGameClient_signOnState = 0x230;
        constexpr std::ptrdiff_t NetworkP2PService_001 = 0x90D750;
        constexpr std::ptrdiff_t NetworkServerService_001 = 0x90D900;
        constexpr std::ptrdiff_t NetworkService_001 = 0x615630;
        constexpr std::ptrdiff_t RenderService_001 = 0x90DB70;
        constexpr std::ptrdiff_t ScreenshotService001 = 0x90DE30;
        constexpr std::ptrdiff_t SimpleEngineLoopService_001 = 0x615DB0;
        constexpr std::ptrdiff_t SoundService_001 = 0x615670;
        constexpr std::ptrdiff_t Source2EngineToClient001 = 0x6125A0;
        constexpr std::ptrdiff_t Source2EngineToClientStringTable001 = 0x612600;
        constexpr std::ptrdiff_t Source2EngineToServer001 = 0x612678;
        constexpr std::ptrdiff_t Source2EngineToServerStringTable001 = 0x6126A0;
        constexpr std::ptrdiff_t SplitScreenService_001 = 0x615950;
        constexpr std::ptrdiff_t StatsService_001 = 0x90E1F0;
        constexpr std::ptrdiff_t ToolService_001 = 0x615B10;
        constexpr std::ptrdiff_t VENGINE_GAMEUIFUNCS_VERSION005 = 0x612D00;
        constexpr std::ptrdiff_t VProfService_001 = 0x615B50;
        constexpr std::ptrdiff_t WindowHeight = 0x9118D4;
        constexpr std::ptrdiff_t WindowWidth = 0x9118D0;
        constexpr std::ptrdiff_t pBuildNumber = 0x60F594;
        constexpr std::ptrdiff_t pNetworkGameClient = 0x90D4B0;
        constexpr std::ptrdiff_t pPVSManager = 0x615E00;
        constexpr std::ptrdiff_t pWindowHeight = 0x9118D4;
        constexpr std::ptrdiff_t pWindowWidth = 0x9118D0;
    }
    namespace filesystem_stdio {
        constexpr std::ptrdiff_t VAsyncFileSystem2_001 = 0x211600;
        constexpr std::ptrdiff_t VFileSystem017 = 0x2113C0;
    }
    namespace host {
        constexpr std::ptrdiff_t DebugDrawQueueManager001 = 0x13E0A0;
        constexpr std::ptrdiff_t GameModelInfo001 = 0x13E0E0;
        constexpr std::ptrdiff_t GameSystem2HostHook = 0x13E120;
        constexpr std::ptrdiff_t HostUtils001 = 0x14DB50;
        constexpr std::ptrdiff_t PredictionDiffManager001 = 0x13E230;
        constexpr std::ptrdiff_t SaveRestoreDataVersion001 = 0x13E360;
        constexpr std::ptrdiff_t SinglePlayerSharedMemory001 = 0x13E390;
        constexpr std::ptrdiff_t Source2Host001 = 0x13E400;
    }
    namespace imemanager {
        constexpr std::ptrdiff_t IMEManager001 = 0x36AA0;
    }
    namespace inputsystem {
        constexpr std::ptrdiff_t InputStackSystemVersion001 = 0x43E90;
        constexpr std::ptrdiff_t InputSystem = 0x45BA0;
        constexpr std::ptrdiff_t InputSystemVersion001 = 0x45BA0;
        constexpr std::ptrdiff_t pInputSystem = 0x45BA0;
        constexpr std::ptrdiff_t pInputSystemSvc = 0x45BA0;
    }
    namespace localize {
        constexpr std::ptrdiff_t Localize_001 = 0x58100;
    }
    namespace matchmaking {
        constexpr std::ptrdiff_t GameTypes = 0x1ADF80;
        constexpr std::ptrdiff_t GameTypes001 = 0x1ADF80;
        constexpr std::ptrdiff_t MATCHFRAMEWORK_001 = 0x1B5F00;
    }
    namespace materialsystem2 {
        constexpr std::ptrdiff_t FontManager_001 = 0x15CBB0;
        constexpr std::ptrdiff_t MaterialUtils_001 = 0x144F00;
        constexpr std::ptrdiff_t PostProcessingSystem_001 = 0x144E30;
        constexpr std::ptrdiff_t TextLayout_001 = 0x144E90;
        constexpr std::ptrdiff_t VMaterialSystem2_001 = 0x15C800;
    }
    namespace meshsystem {
        constexpr std::ptrdiff_t MeshSystem001 = 0x16BDE0;
    }
    namespace navsystem {
        constexpr std::ptrdiff_t NavSystem001 = 0x128C20;
    }
    namespace networksystem {
        constexpr std::ptrdiff_t FlattenedSerializersVersion001 = 0x26C810;
        constexpr std::ptrdiff_t NetworkMessagesVersion001 = 0x294A30;
        constexpr std::ptrdiff_t NetworkSystemVersion001 = 0x285F60;
        constexpr std::ptrdiff_t SerializedEntitiesVersion001 = 0x286050;
        constexpr std::ptrdiff_t pNetworkSystem = 0x285F60;
    }
    namespace panorama {
        constexpr std::ptrdiff_t PanoramaUIEngine001 = 0x50FD60;
    }
    namespace panorama_text_pango {
        constexpr std::ptrdiff_t PanoramaTextServices001 = 0x2B89D0;
    }
    namespace panoramauiclient {
        constexpr std::ptrdiff_t PanoramaUIClient001 = 0x295210;
    }
    namespace particles {
        constexpr std::ptrdiff_t GetParticleManager = 0x5A81F8;
        constexpr std::ptrdiff_t ParticleSystemMgr003 = 0x5FEAD0;
    }
    namespace pulse_system {
        constexpr std::ptrdiff_t IPulseSystem_001 = 0x219710;
    }
    namespace rendersystemdx11 {
        constexpr std::ptrdiff_t RenderDeviceMgr001 = 0x42C550;
        constexpr std::ptrdiff_t RenderUtils_001 = 0x42CE30;
        constexpr std::ptrdiff_t VRenderDeviceMgrBackdoor001 = 0x42C5F0;
    }
    namespace resourcesystem {
        constexpr std::ptrdiff_t ResourceSystem013 = 0x81680;
    }
    namespace scenefilecache {
        constexpr std::ptrdiff_t ResponseRulesCache001 = 0x113450;
        constexpr std::ptrdiff_t SceneFileCache002 = 0x113578;
    }
    namespace scenesystem {
        constexpr std::ptrdiff_t RenderingPipelines_001 = 0x667F10;
        constexpr std::ptrdiff_t SceneSystem_002 = 0x911530;
        constexpr std::ptrdiff_t SceneUtils_001 = 0x668DD0;
        constexpr std::ptrdiff_t pSceneSystem = 0x911530;
    }
    namespace schemasystem {
        constexpr std::ptrdiff_t SchemaSystem_001 = 0x75730;
        constexpr std::ptrdiff_t pSchemaSystem = 0x75730;
    }
    namespace server {
        constexpr std::ptrdiff_t EmptyWorldService001_Server = 0x1C36F60;
        constexpr std::ptrdiff_t EntitySubclassUtilsV001 = 0x1BE6B50;
        constexpr std::ptrdiff_t NavGameTest001 = 0x1CAA070;
        constexpr std::ptrdiff_t ServerToolsInfo_001 = 0x1C70928;
        constexpr std::ptrdiff_t Source2GameClients001 = 0x1C6FB10;
        constexpr std::ptrdiff_t Source2GameDirector001 = 0x1DF1240;
        constexpr std::ptrdiff_t Source2GameEntities001 = 0x1C700D0;
        constexpr std::ptrdiff_t Source2Server001 = 0x1C6FF20;
        constexpr std::ptrdiff_t Source2ServerConfig001 = 0x1F5A578;
        constexpr std::ptrdiff_t customnavsystem001 = 0x1BCAFA8;
    }
    namespace soundsystem {
        constexpr std::ptrdiff_t SoundBugBugService001_Client = 0x54BD80;
        constexpr std::ptrdiff_t SoundOpSystem001 = 0x54BC60;
        constexpr std::ptrdiff_t SoundOpSystemEdit001 = 0x54BB70;
        constexpr std::ptrdiff_t SoundSystem001 = 0x54B5D0;
        constexpr std::ptrdiff_t SoundSystem_engineViewData = 0x7C;
        constexpr std::ptrdiff_t VMixEditTool001 = 0x594945F;
        constexpr std::ptrdiff_t pSoundChannels = 0x66FC28;
        constexpr std::ptrdiff_t pSoundSystem = 0x54B5D0;
    }
    namespace steamaudio {
        constexpr std::ptrdiff_t SteamAudio001 = 0x260610;
    }
    namespace tier0 {
        constexpr std::ptrdiff_t TestScriptMgr001 = 0x399800;
        constexpr std::ptrdiff_t VEngineCvar007 = 0x3A44F0;
        constexpr std::ptrdiff_t VProcessUtils002 = 0x3997A0;
        constexpr std::ptrdiff_t VStringTokenSystem001 = 0x3CB1F0;
        constexpr std::ptrdiff_t pCVar = 0x3A44F0;
        constexpr std::ptrdiff_t pCvarRegistry = 0x3A1398;
    }
    namespace v8system {
        constexpr std::ptrdiff_t Source2V8System001 = 0x31770;
    }
    namespace vconcomm {
        constexpr std::ptrdiff_t VConComm001 = 0x3B730;
    }
    namespace vphysics2 {
        constexpr std::ptrdiff_t VPhysics2_Interface_001 = 0x428E90;
    }
    namespace vscript {
        constexpr std::ptrdiff_t VScriptManager010 = 0x13D430;
    }
    namespace worldrenderer {
        constexpr std::ptrdiff_t WorldRendererMgr001 = 0x231DA0;
    }
}
