// Generated by cs2-sdk — https://cs2-sdk.com
//
// module:        pulse_system.dll
// classes:       38
// enums:         4
// generated_at:  2026-07-19T01:55:39.517213600+00:00
//
// Use:
//   auto* pawn = reinterpret_cast<C_CSPlayerPawn*>(addr);
//   pawn->m_iHealth() = 100;

#pragma once
#include "../macros.hpp"

namespace pulse_system {

    class CPulseCell_Step_TestDomainDestroyFakeEntity;
    class CPulseCell_Test_NoInflow;
    class CPulseGraphInstance_TestDomain_FakeEntityOwner;
    class CTestDomainDerived_Cursor;
    class CPulseTestFuncs_LibraryA;
    class CPulseCell_TestYieldForever;
    class CPulseGraphInstance_TestDomain_UseReadOnlyBlackboardView;
    class CPulseCell_TestWaitWithCursorState_InstanceState_t;
    class CPulseCell_TestWaitWithAutoTracepoints;
    class CPulseCell_Test_MultiOutflow_WithParams;
    class CPulseCell_Test_MultiOutflow_WithParams_Yielding_CursorState_t;
    class CPulseTurtleGraphicsCursor;
    class CPulseCell_TestWaitWithCursorState_CursorState_t;
    class CPulseCell_Test_MultiInflow_NoDefault;
    class CPulseCell_Value_TestValue50;
    class CPulseCell_Test_MultiOutflow_WithParams_Yielding;
    class TestComponent_tAPI;
    class CPulseCell_Step_TestDomainTracepoint;
    class CPulseGraphInstance_TestDomain_Derived;
    class CPulseGraphInstance_TestDomain;
    class CPulseCell_Outflow_TestExplicitYesNo;
    class CPulseCell_Outflow_TestRandomYesNo;
    class FakeEntity_tAPI;
    class CPulseCell_Test_MultiInflow_WithDefault;
    class CPulseGraphInstance_TurtleGraphics;
    class CPulseCell_Val_TestDomainGetEntityName;
    class CPulseCell_TestWaitWithCursorState;
    class FakeEntityDerivedB_tAPI;
    class CPulseCell_Val_TestDomainFindEntityByName;
    class CPulseCell_TestEnums;
    class CPulseCell_Step_TestDomainEntFire;
    class FakeEntityDerivedA_tAPI;
    class CPulseCell_ExampleSelector;
    class CPulseCell_ExampleCriteria_Criteria_t;
    class CPulseCell_ExampleCriteria;
    class CPulseCell_Step_TestDomainCreateFakeEntity;
    class CPulseCell_TestYieldWithObservables;
    class TestComponent_t;

    enum class PulseTestEnumFlags_t : std::uint32_t {
        NONE = 0x0, // MPropertyFriendlyName
        FIRST = 0x1, // MPropertyFriendlyName
        SECOND = 0x2, // MPropertyFriendlyName
        THIRD = 0x4, // MPropertyFriendlyName
    };

    enum class PulseTestEnumShape_t : std::uint32_t {
        CIRCLE = 0x64, // MPropertyFriendlyName
        SQUARE = 0xC8, // MPropertyFriendlyName
        TRIANGLE = 0x12C, // MPropertyFriendlyName
    };

    enum class PulseTestEnumFlagsAlt_t : std::uint32_t {
        NONE = 0x0,
        FIRST = 0x1,
    };

    enum class PulseTestEnumColor_t : std::uint32_t {
        BLACK = 0x0, // MPropertyFriendlyName
        WHITE = 0x1, // MPropertyFriendlyName
        RED = 0x2, // MPropertyFriendlyName
        GREEN = 0x3, // MPropertyFriendlyName
        BLUE = 0x4, // MPropertyFriendlyName
    };

    // CPulseGraphInstance_TestDomain
    //   fields: 9
    //   size: 0x158
    class CPulseGraphInstance_TestDomain {
    public:
        SCHEMA_FIELD(bool                            , m_bIsRunningUnitTests                           , 0x128) // bool
        SCHEMA_FIELD(bool                            , m_bExplicitTimeStepping                         , 0x129) // bool
        SCHEMA_FIELD(bool                            , m_bExpectingToDestroyWithYieldedCursors         , 0x12A) // bool
        SCHEMA_FIELD(bool                            , m_bQuietTracepoints                             , 0x12B) // bool
        SCHEMA_FIELD(bool                            , m_bExpectingCursorTerminatedDueToMaxInstructions, 0x12C) // bool
        SCHEMA_FIELD(std::int32_t                    , m_nCursorsTerminatedDueToMaxInstructions        , 0x130) // int32
        SCHEMA_FIELD(std::int32_t                    , m_nNextValidateIndex                            , 0x134) // int32
        SCHEMA_FIELD(CUtlVector<CUtlString>          , m_Tracepoints                                   , 0x138) // CUtlVector<CUtlString>
        SCHEMA_FIELD(bool                            , m_bTestYesOrNoPath                              , 0x150) // bool
    };

    // CPulseCell_TestYieldForever
    //   fields: 0
    //   size: 0xD8
    //   @MGetKV3ClassDefaults
    class CPulseCell_TestYieldForever {
    public:
    };

    // CPulseCell_Value_TestValue50
    //   fields: 0
    //   size: 0x48
    //   @MGetKV3ClassDefaults
    //   @MPropertyFriendlyName
    //   @MPropertyDescription
    class CPulseCell_Value_TestValue50 {
    public:
    };

    // CPulseCell_ExampleSelector
    //   fields: 1
    //   size: 0x60
    //   @MGetKV3ClassDefaults
    //   @MPropertyFriendlyName
    //   @MPropertyDescription
    //   @MPulseEditorHeaderIcon
    //   @MPulseEditorCanvasItemSpecKV3
    class CPulseCell_ExampleSelector {
    public:
        SCHEMA_FIELD(::animationsystem::PulseSelectorOutflowList_t, m_OutflowList                                   , 0x48) // PulseSelectorOutflowList_t
    };

    // CPulseCell_Val_TestDomainGetEntityName
    //   fields: 0
    //   size: 0x48
    //   @MGetKV3ClassDefaults
    //   @MPropertyFriendlyName
    class CPulseCell_Val_TestDomainGetEntityName {
    public:
    };

    // CPulseCell_ExampleCriteria
    //   fields: 0
    //   size: 0x48
    //   @MGetKV3ClassDefaults
    //   @MPropertyFriendlyName
    //   @MPropertyDescription
    class CPulseCell_ExampleCriteria {
    public:
    };

    // CPulseCell_Step_TestDomainCreateFakeEntity
    //   fields: 0
    //   size: 0x48
    //   @MGetKV3ClassDefaults
    //   @MPropertyFriendlyName
    class CPulseCell_Step_TestDomainCreateFakeEntity {
    public:
    };

    // TestComponent_t
    //   fields: 1
    //   size: 0x10
    class TestComponent_t {
    public:
        SCHEMA_FIELD(::CUtlString                    , m_ComponentData                                 , 0x8) // CUtlString
    };

    // CPulseCell_Test_MultiInflow_WithDefault
    //   fields: 0
    //   size: 0x48
    //   @MGetKV3ClassDefaults
    class CPulseCell_Test_MultiInflow_WithDefault {
    public:
    };

    // CPulseTurtleGraphicsCursor
    //   fields: 4
    //   size: 0xF0
    class CPulseTurtleGraphicsCursor {
    public:
        SCHEMA_FIELD(::Color                         , m_Color                                         , 0xD8) // Color
        SCHEMA_FIELD(::Vector2D                      , m_vPos                                          , 0xDC) // Vector2D
        SCHEMA_FIELD(float                           , m_flHeadingDeg                                  , 0xE4) // float32
        SCHEMA_FIELD(bool                            , m_bPenUp                                        , 0xE8) // bool
    };

    // CPulseGraphInstance_TestDomain_FakeEntityOwner
    //   fields: 0
    //   size: 0x110
    class CPulseGraphInstance_TestDomain_FakeEntityOwner {
    public:
    };

    // CPulseCell_Outflow_TestRandomYesNo
    //   fields: 2
    //   size: 0xD8
    //   @MGetKV3ClassDefaults
    //   @MPropertyFriendlyName
    //   @MPropertyDescription
    class CPulseCell_Outflow_TestRandomYesNo {
    public:
        SCHEMA_FIELD(::animationsystem::CPulse_OutflowConnection, m_Yes                                           , 0x48) // CPulse_OutflowConnection [MPropertyFriendlyName, MPropertyDescription]
        SCHEMA_FIELD(::animationsystem::CPulse_OutflowConnection, m_No                                            , 0x90) // CPulse_OutflowConnection [MPropertyFriendlyName, MPropertyDescription]
    };

    // CPulseCell_Val_TestDomainFindEntityByName
    //   fields: 0
    //   size: 0x48
    //   @MGetKV3ClassDefaults
    //   @MPropertyFriendlyName
    class CPulseCell_Val_TestDomainFindEntityByName {
    public:
    };

    // CPulseTestFuncs_LibraryA
    //   fields: 0
    //   size: 0x1
    //   @MPropertyDescription
    class CPulseTestFuncs_LibraryA {
    public:
    };

    // CPulseCell_Test_MultiInflow_NoDefault
    //   fields: 0
    //   size: 0x48
    //   @MGetKV3ClassDefaults
    class CPulseCell_Test_MultiInflow_NoDefault {
    public:
    };

    // CPulseGraphInstance_TestDomain_Derived
    //   fields: 1
    //   size: 0x160
    class CPulseGraphInstance_TestDomain_Derived {
    public:
        SCHEMA_FIELD(std::int32_t                    , m_nInstanceValueX                               , 0x158) // int32
    };

    // CPulseCell_ExampleCriteria::Criteria_t
    //   fields: 3
    //   size: 0xC
    class CPulseCell_ExampleCriteria_Criteria_t {
    public:
        SCHEMA_FIELD(float                           , m_flFloatValue1                                 , 0x0) // float32
        SCHEMA_FIELD(float                           , m_flFloatValue2                                 , 0x4) // float32
        SCHEMA_FIELD(bool                            , m_bMyBool                                       , 0x8) // bool
    };

    // CPulseCell_TestWaitWithCursorState::CursorState_t
    //   fields: 5
    //   size: 0x24
    //   @MGetKV3ClassDefaults
    class CPulseCell_TestWaitWithCursorState_CursorState_t {
    public:
        SCHEMA_FIELD(float                           , flWaitValue                                     , 0x0) // float32
        SCHEMA_FIELD(bool                            , bFail                                           , 0x4) // bool
        SCHEMA_FIELD(HYieldedCursor                  , m_hSelfCursor                                   , 0x8) // HYieldedCursor
        SCHEMA_FIELD(HPulseCellBase                  , m_hSelfCellInstanceUntyped                      , 0x14) // HPulseCellBase
        SCHEMA_FIELD(HPulseCell<CPulseCell_TestWaitWithCursorState>, m_hSelfCellInstance                             , 0x1C) // HPulseCell<CPulseCell_TestWaitWithCursorState>
    };

    // CPulseCell_Test_MultiOutflow_WithParams_Yielding::CursorState_t
    //   fields: 1
    //   size: 0x4
    //   @MGetKV3ClassDefaults
    class CPulseCell_Test_MultiOutflow_WithParams_Yielding_CursorState_t {
    public:
        SCHEMA_FIELD(std::int32_t                    , nTestStep                                       , 0x0) // int32
    };

    // CPulseGraphInstance_TestDomain_UseReadOnlyBlackboardView
    //   fields: 0
    //   size: 0x158
    class CPulseGraphInstance_TestDomain_UseReadOnlyBlackboardView {
    public:
    };

    // CPulseCell_Test_MultiOutflow_WithParams
    //   fields: 2
    //   size: 0xD8
    //   @MGetKV3ClassDefaults
    class CPulseCell_Test_MultiOutflow_WithParams {
    public:
        SCHEMA_FIELD(::animationsystem::SignatureOutflow_Continue, m_Out1                                          , 0x48) // SignatureOutflow_Continue
        SCHEMA_FIELD(::animationsystem::SignatureOutflow_Continue, m_Out2                                          , 0x90) // SignatureOutflow_Continue
    };

    // CPulseCell_TestWaitWithAutoTracepoints
    //   fields: 2
    //   size: 0x128
    //   @MGetKV3ClassDefaults
    //   @MPropertyFriendlyName
    class CPulseCell_TestWaitWithAutoTracepoints {
    public:
        SCHEMA_FIELD(::CUtlString                    , m_TracePrefix                                   , 0xD8) // CUtlString
        SCHEMA_FIELD(::animationsystem::CPulse_ResumePoint, m_WakeResume                                    , 0xE0) // CPulse_ResumePoint
    };

    // CPulseCell_Outflow_TestExplicitYesNo
    //   fields: 2
    //   size: 0xD8
    //   @MGetKV3ClassDefaults
    //   @MPropertyFriendlyName
    //   @MPropertyDescription
    class CPulseCell_Outflow_TestExplicitYesNo {
    public:
        SCHEMA_FIELD(::animationsystem::CPulse_OutflowConnection, m_Yes                                           , 0x48) // CPulse_OutflowConnection [MPropertyFriendlyName]
        SCHEMA_FIELD(::animationsystem::CPulse_OutflowConnection, m_No                                            , 0x90) // CPulse_OutflowConnection [MPropertyFriendlyName]
    };

    // CPulseCell_TestYieldWithObservables
    //   fields: 5
    //   size: 0x220
    //   @MGetKV3ClassDefaults
    class CPulseCell_TestYieldWithObservables {
    public:
        SCHEMA_FIELD(float                           , m_flWatchForFloatValue                          , 0xD8) // float32
        SCHEMA_FIELD(CPulseObservableExpression<float32>, m_LiveFloatValue                                , 0xE0) // CPulseObservableExpression<float32>
        SCHEMA_FIELD(::CUtlString                    , m_WatchForStringValue                           , 0x158) // CUtlString
        SCHEMA_FIELD(CPulseObservableExpression<CUtlString>, m_LiveStringValue                               , 0x160) // CPulseObservableExpression<CUtlString>
        SCHEMA_FIELD(::animationsystem::CPulse_ResumePoint, m_WakeResume                                    , 0x1D8) // CPulse_ResumePoint
    };

    // TestComponent_tAPI
    //   fields: 0
    //   size: 0x8
    class TestComponent_tAPI {
    public:
    };

    // CTestDomainDerived_Cursor
    //   fields: 2
    //   size: 0xE0
    class CTestDomainDerived_Cursor {
    public:
        SCHEMA_FIELD(std::int32_t                    , m_nCursorValueA                                 , 0xD8) // int32
        SCHEMA_FIELD(std::int32_t                    , m_nCursorValueB                                 , 0xDC) // int32
    };

    // CPulseCell_TestEnums
    //   fields: 2
    //   size: 0x50
    //   @MGetKV3ClassDefaults
    //   @MPropertyFriendlyName
    class CPulseCell_TestEnums {
    public:
        SCHEMA_FIELD(PulseTestEnumColor_t            , m_nReferenceColor                               , 0x48) // PulseTestEnumColor_t
        SCHEMA_FIELD(PulseTestEnumFlags_t            , m_nReferenceFlags                               , 0x4C) // PulseTestEnumFlags_t
    };

    // CPulseCell_Step_TestDomainDestroyFakeEntity
    //   fields: 0
    //   size: 0x48
    //   @MGetKV3ClassDefaults
    //   @MPropertyFriendlyName
    class CPulseCell_Step_TestDomainDestroyFakeEntity {
    public:
    };

    // CPulseCell_Test_NoInflow
    //   fields: 0
    //   size: 0x48
    //   @MGetKV3ClassDefaults
    class CPulseCell_Test_NoInflow {
    public:
    };

    // FakeEntityDerivedB_tAPI
    //   fields: 0
    //   size: 0x8
    class FakeEntityDerivedB_tAPI {
    public:
    };

    // CPulseCell_TestWaitWithCursorState
    //   fields: 2
    //   size: 0x168
    //   @MGetKV3ClassDefaults
    class CPulseCell_TestWaitWithCursorState {
    public:
        SCHEMA_FIELD(::animationsystem::CPulse_ResumePoint, m_WakeResume                                    , 0xD8) // CPulse_ResumePoint
        SCHEMA_FIELD(::animationsystem::CPulse_ResumePoint, m_WakeFail                                      , 0x120) // CPulse_ResumePoint
    };

    // CPulseCell_Test_MultiOutflow_WithParams_Yielding
    //   fields: 5
    //   size: 0x240
    //   @MGetKV3ClassDefaults
    class CPulseCell_Test_MultiOutflow_WithParams_Yielding {
    public:
        SCHEMA_FIELD(::animationsystem::SignatureOutflow_Continue, m_Out1                                          , 0xD8) // SignatureOutflow_Continue
        SCHEMA_FIELD(::animationsystem::SignatureOutflow_Continue, m_AsyncChild1                                   , 0x120) // SignatureOutflow_Continue
        SCHEMA_FIELD(::animationsystem::SignatureOutflow_Continue, m_AsyncChild2                                   , 0x168) // SignatureOutflow_Continue
        SCHEMA_FIELD(::animationsystem::SignatureOutflow_Resume, m_YieldResume1                                  , 0x1B0) // SignatureOutflow_Resume
        SCHEMA_FIELD(::animationsystem::SignatureOutflow_Resume, m_YieldResume2                                  , 0x1F8) // SignatureOutflow_Resume
    };

    // CPulseGraphInstance_TurtleGraphics
    //   fields: 0
    //   size: 0x138
    class CPulseGraphInstance_TurtleGraphics {
    public:
    };

    // CPulseCell_Step_TestDomainTracepoint
    //   fields: 0
    //   size: 0x48
    //   @MGetKV3ClassDefaults
    //   @MPropertyFriendlyName
    class CPulseCell_Step_TestDomainTracepoint {
    public:
    };

    // CPulseCell_TestWaitWithCursorState::InstanceState_t
    //   fields: 1
    //   size: 0x4
    //   @MGetKV3ClassDefaults
    class CPulseCell_TestWaitWithCursorState_InstanceState_t {
    public:
        SCHEMA_FIELD(std::int32_t                    , m_nDummy                                        , 0x0) // int32
    };

    // FakeEntity_tAPI
    //   fields: 0
    //   size: 0x8
    class FakeEntity_tAPI {
    public:
    };

    // CPulseCell_Step_TestDomainEntFire
    //   fields: 1
    //   size: 0x50
    //   @MGetKV3ClassDefaults
    //   @MPropertyFriendlyName
    //   @MPulseEditorHeaderText
    class CPulseCell_Step_TestDomainEntFire {
    public:
        SCHEMA_FIELD(::CUtlString                    , m_Input                                         , 0x48) // CUtlString
    };

    // FakeEntityDerivedA_tAPI
    //   fields: 0
    //   size: 0x8
    class FakeEntityDerivedA_tAPI {
    public:
    };

} // namespace pulse_system
