// Generated by cs2-sdk — https://cs2-sdk.com
//
// module:        resourcesystem.dll
// classes:       59
// enums:         2
// generated_at:  2026-07-19T01:55:39.517213600+00:00
//
// Use:
//   auto* pawn = reinterpret_cast<C_CSPlayerPawn*>(addr);
//   pawn->m_iHealth() = 100;

#pragma once
#include "../macros.hpp"

namespace resourcesystem {

    class InfoForResourceTypeCResponseRulesList;
    class AABBWS_t;
    class InfoForResourceTypeCDotaItemDefinitionResource;
    class InfoForResourceTypeCMorphSetData;
    class InfoForResourceTypeCVSoundStackScriptList;
    class PackedAABB_t;
    class InfoForResourceTypeCVPhysXSurfacePropertiesList;
    class InfoForResourceTypeManifestTestResource_t;
    class ConstantInfo_t;
    class FuseFunctionIndex_t;
    class InfoForResourceTypeCGcExportableExternalData;
    class InfoForResourceTypeIAnimGraphModelBinding;
    class InfoForResourceTypeCJavaScriptResource;
    class CFuseSymbolTable;
    class InfoForResourceTypeCRenderMesh;
    class InfoForResourceTypeCVoxelVisibility;
    class InfoForResourceTypeCPhysAggregateData;
    class InfoForResourceTypeCNmClip;
    class InfoForResourceTypeWorld_t;
    class InfoForResourceTypeProceduralTestResource_t;
    class AABB_t;
    class InfoForResourceTypeCPostProcessingResource;
    class VariableInfo_t;
    class InfoForResourceTypeIParticleSnapshot;
    class FourQuaternions;
    class InfoForResourceTypeCPanoramaLayout;
    class InfoForResourceTypeCTypeScriptResource;
    class InfoForResourceTypeCChoreoSceneResource;
    class InfoForResourceTypeCNmSkeleton;
    class InfoForResourceTypeCTestResourceData;
    class InfoForResourceTypeCAnimationGroup;
    class InfoForResourceTypeCVSoundEventScriptList;
    class InfoForResourceTypeCVoiceContainerBase;
    class InfoForResourceTypeCPanoramaStyle;
    class InfoForResourceTypeCWorldNode;
    class InfoForResourceTypeCSurfaceGraph;
    class InfoForResourceTypeCCSGOEconItem;
    class InfoForResourceTypeCNmGraphDefinition;
    class InfoForResourceTypeCSmartProp;
    class CFuseProgram;
    class InfoForResourceTypeCCompositeMaterialKit;
    class InfoForResourceTypeCVMixListResource;
    class InfoForResourceTypeCAnimData;
    class InfoForResourceTypeIMaterial2;
    class InfoForResourceTypeIVectorGraphic;
    class InfoForResourceTypeCPanoramaDynamicImages;
    class InfoForResourceTypeIPulseGraphDef;
    class InfoForResourceTypeCVDataItemDefs;
    class FunctionInfo_t;
    class InfoForResourceTypeCVDataResource;
    class InfoForResourceTypeCModel;
    class InfoForResourceTypeCDOTANovelsList;
    class InfoForResourceTypeCTextureBase;
    class FuseVariableIndex_t;
    class InfoForResourceTypeIParticleSystemDefinition;
    class InfoForResourceTypeCSequenceGroupData;
    class ManifestTestResource_t;
    class InfoForResourceTypeCEntityLump;
    class InfoForResourceTypeCDOTAPatchNotesList;

    enum class FuseVariableType_t : std::uint8_t {
        INVALID = 0x0,
        BOOL = 0x1,
        INT8 = 0x2,
        INT16 = 0x3,
        INT32 = 0x4,
        UINT8 = 0x5,
        UINT16 = 0x6,
        UINT32 = 0x7,
        FLOAT32 = 0x8,
    };

    enum class FuseVariableAccess_t : std::uint8_t {
        WRITABLE = 0x0,
        READ_ONLY = 0x1,
    };

    // VariableInfo_t
    //   fields: 6
    //   size: 0x18
    //   @MGetKV3ClassDefaults
    class VariableInfo_t {
    public:
        SCHEMA_FIELD(::CUtlString                    , m_name                                          , 0x0) // CUtlString
        SCHEMA_FIELD(CUtlStringToken                 , m_nameToken                                     , 0x8) // CUtlStringToken
        SCHEMA_FIELD(FuseVariableIndex_t             , m_nIndex                                        , 0xC) // FuseVariableIndex_t
        SCHEMA_FIELD(std::uint8_t                    , m_nNumComponents                                , 0xE) // uint8
        SCHEMA_FIELD(FuseVariableType_t              , m_eVarType                                      , 0xF) // FuseVariableType_t
        SCHEMA_FIELD(FuseVariableAccess_t            , m_eAccess                                       , 0x10) // FuseVariableAccess_t
    };

    // InfoForResourceTypeIParticleSnapshot
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeIParticleSnapshot {
    public:
    };

    // InfoForResourceTypeCNmGraphDefinition
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCNmGraphDefinition {
    public:
    };

    // InfoForResourceTypeCNmSkeleton
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCNmSkeleton {
    public:
    };

    // InfoForResourceTypeCPanoramaLayout
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCPanoramaLayout {
    public:
    };

    // InfoForResourceTypeCAnimData
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCAnimData {
    public:
    };

    // ManifestTestResource_t
    //   fields: 2
    //   size: 0x10
    //   @MGetKV3ClassDefaults
    class ManifestTestResource_t {
    public:
        SCHEMA_FIELD(::CUtlString                    , m_name                                          , 0x0) // CUtlString [MKV3TransferName]
        SCHEMA_FIELD(CStrongHandle<InfoForResourceTypeManifestTestResource_t>, m_child                                         , 0x8) // CStrongHandle<InfoForResourceTypeManifestTestResource_t> [MKV3TransferName]
    };

    // InfoForResourceTypeCVDataItemDefs
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCVDataItemDefs {
    public:
    };

    // InfoForResourceTypeCVoiceContainerBase
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCVoiceContainerBase {
    public:
    };

    // AABBWS_t
    //   fields: 2
    //   size: 0x18
    class AABBWS_t {
    public:
        SCHEMA_FIELD(VectorWS                        , m_vMinBounds                                    , 0x0) // VectorWS
        SCHEMA_FIELD(VectorWS                        , m_vMaxBounds                                    , 0xC) // VectorWS
    };

    // InfoForResourceTypeCMorphSetData
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCMorphSetData {
    public:
    };

    // InfoForResourceTypeCTestResourceData
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCTestResourceData {
    public:
    };

    // InfoForResourceTypeCVPhysXSurfacePropertiesList
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCVPhysXSurfacePropertiesList {
    public:
    };

    // InfoForResourceTypeCCSGOEconItem
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCCSGOEconItem {
    public:
    };

    // InfoForResourceTypeCPhysAggregateData
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCPhysAggregateData {
    public:
    };

    // InfoForResourceTypeCChoreoSceneResource
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCChoreoSceneResource {
    public:
    };

    // CFuseSymbolTable
    //   fields: 6
    //   size: 0xB0
    //   @MGetKV3ClassDefaults
    class CFuseSymbolTable {
    public:
        using _Type0 = CUtlHashtable<CUtlStringToken,int32>;
        using _Type1 = CUtlHashtable<CUtlStringToken,int32>;
        using _Type2 = CUtlHashtable<CUtlStringToken,int32>;
        SCHEMA_FIELD(CUtlVector<ConstantInfo_t>      , m_constants                                     , 0x0) // CUtlVector<ConstantInfo_t>
        SCHEMA_FIELD(CUtlVector<VariableInfo_t>      , m_variables                                     , 0x18) // CUtlVector<VariableInfo_t>
        SCHEMA_FIELD(CUtlVector<FunctionInfo_t>      , m_functions                                     , 0x30) // CUtlVector<FunctionInfo_t>
        SCHEMA_FIELD(_Type0                          , m_constantMap                                   , 0x48) // CUtlHashtable<CUtlStringToken,int32>
        SCHEMA_FIELD(_Type1                          , m_variableMap                                   , 0x68) // CUtlHashtable<CUtlStringToken,int32>
        SCHEMA_FIELD(_Type2                          , m_functionMap                                   , 0x88) // CUtlHashtable<CUtlStringToken,int32>
    };

    // InfoForResourceTypeCAnimationGroup
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCAnimationGroup {
    public:
    };

    // PackedAABB_t
    //   fields: 2
    //   size: 0x8
    class PackedAABB_t {
    public:
        SCHEMA_FIELD(std::uint32_t                   , m_nPackedMin                                    , 0x0) // uint32
        SCHEMA_FIELD(std::uint32_t                   , m_nPackedMax                                    , 0x4) // uint32
    };

    // FunctionInfo_t
    //   fields: 5
    //   size: 0x20
    //   @MGetKV3ClassDefaults
    class FunctionInfo_t {
    public:
        SCHEMA_FIELD(::CUtlString                    , m_name                                          , 0x8) // CUtlString
        SCHEMA_FIELD(CUtlStringToken                 , m_nameToken                                     , 0x10) // CUtlStringToken
        SCHEMA_FIELD(std::int32_t                    , m_nParamCount                                   , 0x14) // int32
        SCHEMA_FIELD(FuseFunctionIndex_t             , m_nIndex                                        , 0x18) // FuseFunctionIndex_t
        SCHEMA_FIELD(bool                            , m_bIsPure                                       , 0x1A) // bool
    };

    // InfoForResourceTypeCWorldNode
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCWorldNode {
    public:
    };

    // InfoForResourceTypeCVSoundEventScriptList
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCVSoundEventScriptList {
    public:
    };

    // InfoForResourceTypeCDOTANovelsList
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCDOTANovelsList {
    public:
    };

    // InfoForResourceTypeCEntityLump
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCEntityLump {
    public:
    };

    // InfoForResourceTypeIPulseGraphDef
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeIPulseGraphDef {
    public:
    };

    // InfoForResourceTypeCSurfaceGraph
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCSurfaceGraph {
    public:
    };

    // InfoForResourceTypeCDOTAPatchNotesList
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCDOTAPatchNotesList {
    public:
    };

    // InfoForResourceTypeIParticleSystemDefinition
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeIParticleSystemDefinition {
    public:
    };

    // InfoForResourceTypeCVSoundStackScriptList
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCVSoundStackScriptList {
    public:
    };

    // InfoForResourceTypeCDotaItemDefinitionResource
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCDotaItemDefinitionResource {
    public:
    };

    // InfoForResourceTypeIAnimGraphModelBinding
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeIAnimGraphModelBinding {
    public:
    };

    // InfoForResourceTypeCPanoramaStyle
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCPanoramaStyle {
    public:
    };

    // InfoForResourceTypeCSequenceGroupData
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCSequenceGroupData {
    public:
    };

    // InfoForResourceTypeCModel
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCModel {
    public:
    };

    // CFuseProgram
    //   fields: 4
    //   size: 0x50
    //   @MGetKV3ClassDefaults
    class CFuseProgram {
    public:
        SCHEMA_FIELD(CUtlVector<uint8>               , m_programBuffer                                 , 0x0) // CUtlVector<uint8>
        SCHEMA_FIELD(CUtlVector<FuseVariableIndex_t> , m_variablesRead                                 , 0x18) // CUtlVector<FuseVariableIndex_t>
        SCHEMA_FIELD(CUtlVector<FuseVariableIndex_t> , m_variablesWritten                              , 0x30) // CUtlVector<FuseVariableIndex_t>
        SCHEMA_FIELD(std::int32_t                    , m_nMaxTempVarsUsed                              , 0x48) // int32
    };

    // InfoForResourceTypeCTypeScriptResource
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCTypeScriptResource {
    public:
    };

    // InfoForResourceTypeCGcExportableExternalData
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCGcExportableExternalData {
    public:
    };

    // InfoForResourceTypeCResponseRulesList
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCResponseRulesList {
    public:
    };

    // InfoForResourceTypeCTextureBase
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCTextureBase {
    public:
    };

    // InfoForResourceTypeCNmClip
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCNmClip {
    public:
    };

    // InfoForResourceTypeCCompositeMaterialKit
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCCompositeMaterialKit {
    public:
    };

    // InfoForResourceTypeManifestTestResource_t
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeManifestTestResource_t {
    public:
    };

    // InfoForResourceTypeIMaterial2
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeIMaterial2 {
    public:
    };

    // FuseVariableIndex_t
    //   fields: 1
    //   size: 0x2
    class FuseVariableIndex_t {
    public:
        SCHEMA_FIELD(std::uint16_t                   , m_Value                                         , 0x0) // uint16
    };

    // InfoForResourceTypeCVDataResource
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCVDataResource {
    public:
    };

    // FourQuaternions
    //   fields: 4
    //   size: 0x40
    class FourQuaternions {
    public:
        SCHEMA_FIELD(fltx4                           , x                                               , 0x0) // fltx4
        SCHEMA_FIELD(fltx4                           , y                                               , 0x10) // fltx4
        SCHEMA_FIELD(fltx4                           , z                                               , 0x20) // fltx4
        SCHEMA_FIELD(fltx4                           , w                                               , 0x30) // fltx4
    };

    // InfoForResourceTypeCVoxelVisibility
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCVoxelVisibility {
    public:
    };

    // InfoForResourceTypeCPostProcessingResource
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCPostProcessingResource {
    public:
    };

    // InfoForResourceTypeCJavaScriptResource
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCJavaScriptResource {
    public:
    };

    // InfoForResourceTypeIVectorGraphic
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeIVectorGraphic {
    public:
    };

    // InfoForResourceTypeCSmartProp
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCSmartProp {
    public:
    };

    // InfoForResourceTypeWorld_t
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeWorld_t {
    public:
    };

    // InfoForResourceTypeCVMixListResource
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCVMixListResource {
    public:
    };

    // ConstantInfo_t
    //   fields: 3
    //   size: 0x10
    //   @MGetKV3ClassDefaults
    class ConstantInfo_t {
    public:
        SCHEMA_FIELD(::CUtlString                    , m_name                                          , 0x0) // CUtlString
        SCHEMA_FIELD(CUtlStringToken                 , m_nameToken                                     , 0x8) // CUtlStringToken
        SCHEMA_FIELD(float                           , m_flValue                                       , 0xC) // float32
    };

    // InfoForResourceTypeProceduralTestResource_t
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeProceduralTestResource_t {
    public:
    };

    // FuseFunctionIndex_t
    //   fields: 1
    //   size: 0x2
    class FuseFunctionIndex_t {
    public:
        SCHEMA_FIELD(std::uint16_t                   , m_Value                                         , 0x0) // uint16
    };

    // AABB_t
    //   fields: 2
    //   size: 0x18
    class AABB_t {
    public:
        SCHEMA_FIELD(::Vector                        , m_vMinBounds                                    , 0x0) // Vector
        SCHEMA_FIELD(::Vector                        , m_vMaxBounds                                    , 0xC) // Vector
    };

    // InfoForResourceTypeCRenderMesh
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCRenderMesh {
    public:
    };

    // InfoForResourceTypeCPanoramaDynamicImages
    //   fields: 0
    //   size: 0x1
    //   @MResourceTypeForInfoType
    class InfoForResourceTypeCPanoramaDynamicImages {
    public:
    };

} // namespace resourcesystem
