// schema_runtime.hpp -- Runtime schema offset resolver for Source 2
// Auto-generated by dezlock-dump. Copy this file into your injected DLL project.
// Zero dependencies beyond <Windows.h> and C++17 stdlib.
#pragma once

#include <Windows.h>
#include <cstdint>
#include <cstring>
#include <unordered_map>
#include <string>
#include <mutex>
#include <utility>

namespace sdk::schema {

// ---- SchemaSystem interface discovery (singleton) ----

inline void* get_schema_system() {
    static void* s_system = nullptr;
    if (s_system) return s_system;

    HMODULE hmod = GetModuleHandleA("schemasystem.dll");
    if (!hmod) return nullptr;

    using CreateInterfaceFn = void*(*)(const char*, int*);
    auto fn = reinterpret_cast<CreateInterfaceFn>(
        GetProcAddress(hmod, "CreateInterface"));
    if (!fn) return nullptr;

    int ret = 0;
    s_system = fn("SchemaSystem_001", &ret);
    return s_system;
}

// ---- SEH-isolated vtable calls ----

inline void* find_type_scope(void* schema_system, const char* module_name) {
    void* result = nullptr;
    __try {
        auto vtable = *reinterpret_cast<uintptr_t**>(schema_system);
        auto fn = reinterpret_cast<void*(__fastcall*)(void*, const char*, void*)>(vtable[13]);
        result = fn(schema_system, module_name, nullptr);
    } __except(EXCEPTION_EXECUTE_HANDLER) { result = nullptr; }
    return result;
}

inline void* find_declared_class(void* type_scope, const char* class_name) {
    void* result = nullptr;
    __try {
        auto vtable = *reinterpret_cast<uintptr_t**>(type_scope);
        auto fn = reinterpret_cast<void(__fastcall*)(void*, void**, const char*)>(vtable[2]);
        fn(type_scope, &result, class_name);
    } __except(EXCEPTION_EXECUTE_HANDLER) { result = nullptr; }
    return result;
}

// ---- Offset resolution with caching ----

inline int32_t resolve_offset(const char* module_name, const char* class_name, const char* field_name) {
    struct FieldCache {
        std::unordered_map<std::string, int32_t> fields;
    };
    struct ClassCache {
        std::unordered_map<std::string, FieldCache> classes;
    };
    struct ModuleCache {
        void* type_scope = nullptr;
        ClassCache cache;
    };

    static std::unordered_map<std::string, ModuleCache> s_modules;
    static std::mutex s_mutex;

    std::lock_guard<std::mutex> lock(s_mutex);

    // Check cache
    auto& mod = s_modules[module_name];
    auto& cls = mod.cache.classes[class_name];
    auto it = cls.fields.find(field_name);
    if (it != cls.fields.end()) return it->second;

    // Resolve from SchemaSystem
    void* sys = get_schema_system();
    if (!sys) return -1;

    if (!mod.type_scope) {
        mod.type_scope = find_type_scope(sys, module_name);
    }
    if (!mod.type_scope) return -1;

    void* class_info = find_declared_class(mod.type_scope, class_name);
    if (!class_info) return -1;

    // CSchemaClassInfo: field_count at +0x1C (int16), fields_ptr at +0x28
    // SchemaClassFieldData_t: 0x20 bytes each, name at +0x00, offset at +0x10
    uintptr_t ci = reinterpret_cast<uintptr_t>(class_info);
    int16_t field_count = 0;
    uintptr_t fields_ptr = 0;

    __try {
        field_count = *reinterpret_cast<int16_t*>(ci + 0x1C);
        fields_ptr = *reinterpret_cast<uintptr_t*>(ci + 0x28);
    } __except(EXCEPTION_EXECUTE_HANDLER) { return -1; }

    if (!fields_ptr || field_count <= 0) return -1;

    // Walk all fields and cache them (avoids repeated walks for the same class)
    for (int i = 0; i < field_count; i++) {
        uintptr_t entry = fields_ptr + i * 0x20;
        __try {
            const char* fname = *reinterpret_cast<const char**>(entry + 0x00);
            int32_t foffset = *reinterpret_cast<int32_t*>(entry + 0x10);
            if (fname) {
                cls.fields[fname] = foffset;
            }
        } __except(EXCEPTION_EXECUTE_HANDLER) { continue; }
    }

    // Return the requested field
    it = cls.fields.find(field_name);
    if (it != cls.fields.end()) return it->second;
    return -1;
}

} // namespace sdk::schema

// ============================================================================
// Macros -- the public API
// ============================================================================

// Declare once per struct: binds module + class name for all FIELD macros below
#define SCHEMA_CLASS(mod, cls)                                              \
    static constexpr const char* _schema_module = mod;                      \
    static constexpr const char* _schema_class  = cls;

// Standard field accessor: returns type&
#define FIELD(name, type)                                                   \
    type& name() {                                                          \
        static int32_t off = ::sdk::schema::resolve_offset(                 \
            _schema_module, _schema_class, #name);                          \
        return *reinterpret_cast<type*>(                                    \
            reinterpret_cast<uintptr_t>(this) + off);                       \
    }                                                                       \
    const type& name() const {                                              \
        static int32_t off = ::sdk::schema::resolve_offset(                 \
            _schema_module, _schema_class, #name);                          \
        return *reinterpret_cast<const type*>(                              \
            reinterpret_cast<uintptr_t>(this) + off);                       \
    }

// Array field: returns pointer to first element
#define FIELD_ARRAY(name, elem_type, count)                                 \
    elem_type* name() {                                                     \
        static int32_t off = ::sdk::schema::resolve_offset(                 \
            _schema_module, _schema_class, #name);                          \
        return reinterpret_cast<elem_type*>(                                \
            reinterpret_cast<uintptr_t>(this) + off);                       \
    }                                                                       \
    const elem_type* name() const {                                         \
        static int32_t off = ::sdk::schema::resolve_offset(                 \
            _schema_module, _schema_class, #name);                          \
        return reinterpret_cast<const elem_type*>(                          \
            reinterpret_cast<uintptr_t>(this) + off);                       \
    }

// Pointer field: reads and returns the pointer value
#define FIELD_PTR(name, type)                                               \
    type name() {                                                           \
        static int32_t off = ::sdk::schema::resolve_offset(                 \
            _schema_module, _schema_class, #name);                          \
        return *reinterpret_cast<type*>(                                    \
            reinterpret_cast<uintptr_t>(this) + off);                       \
    }

// Opaque/embedded type: returns void* to the field's raw memory
#define FIELD_BLOB(name, sz)                                                \
    void* name() {                                                          \
        static int32_t off = ::sdk::schema::resolve_offset(                 \
            _schema_module, _schema_class, #name);                          \
        return reinterpret_cast<void*>(                                     \
            reinterpret_cast<uintptr_t>(this) + off);                       \
    }                                                                       \
    const void* name() const {                                              \
        static int32_t off = ::sdk::schema::resolve_offset(                 \
            _schema_module, _schema_class, #name);                          \
        return reinterpret_cast<const void*>(                               \
            reinterpret_cast<uintptr_t>(this) + off);                       \
    }

// ============================================================================
// Virtual function call wrappers
// ============================================================================

namespace sdk::vfunc {

inline uintptr_t* get_vtable(void* obj) {
    uintptr_t* vt = nullptr;
    __try { vt = *reinterpret_cast<uintptr_t**>(obj); }
    __except(EXCEPTION_EXECUTE_HANDLER) { vt = nullptr; }
    return vt;
}

} // namespace sdk::vfunc

// Zero-argument virtual function call (most common, used for getters)
#define VFUNC(idx, ret, name)                                              \
    ret name() {                                                           \
        auto _vt = ::sdk::vfunc::get_vtable(this);                         \
        if (!_vt) return ret{};                                            \
        return reinterpret_cast<ret(__fastcall*)(void*)>(_vt[idx])(this);   \
    }

// Variadic-argument virtual function call (manual use)
#define VFUNC_ARGS(idx, ret, name, ...)                                    \
    template<typename... _VArgs>                                           \
    ret name(_VArgs&&... args) {                                           \
        auto _vt = ::sdk::vfunc::get_vtable(this);                         \
        if (!_vt) return ret{};                                            \
        using _Fn = ret(__fastcall*)(void*, _VArgs...);                    \
        return reinterpret_cast<_Fn>(_vt[idx])(this, std::forward<_VArgs>(args)...); \
    }

// Unnamed fallback returning void*
#define VFUNC_RAW(idx)                                                     \
    void* vfunc_##idx() {                                                  \
        auto _vt = ::sdk::vfunc::get_vtable(this);                         \
        if (!_vt) return nullptr;                                          \
        return reinterpret_cast<void*(__fastcall*)(void*)>(_vt[idx])(this); \
    }
