// Auto-generated by dezlock-dump (internal SDK) -- DO NOT EDIT
// Base SDK types for runtime-resolved headers
#pragma once

#include <cstdint>
#include <cstddef>

namespace sdk {

struct Vec2 {
    float x, y;
    Vec2() : x(0), y(0) {}
    Vec2(float x, float y) : x(x), y(y) {}
    Vec2 operator+(const Vec2& o) const { return {x + o.x, y + o.y}; }
    Vec2 operator-(const Vec2& o) const { return {x - o.x, y - o.y}; }
    Vec2 operator*(float s) const { return {x * s, y * s}; }
};

struct Vec3 {
    float x, y, z;
    Vec3() : x(0), y(0), z(0) {}
    Vec3(float x, float y, float z) : x(x), y(y), z(z) {}
    Vec3 operator+(const Vec3& o) const { return {x + o.x, y + o.y, z + o.z}; }
    Vec3 operator-(const Vec3& o) const { return {x - o.x, y - o.y, z - o.z}; }
    Vec3 operator*(float s) const { return {x * s, y * s, z * s}; }
    float length_sqr() const { return x * x + y * y + z * z; }
    float length_2d_sqr() const { return x * x + y * y; }
};

struct Vec4 { float x, y, z, w; };

struct QAngle {
    float pitch, yaw, roll;
    QAngle() : pitch(0), yaw(0), roll(0) {}
    QAngle(float p, float y, float r) : pitch(p), yaw(y), roll(r) {}
};

struct Color { uint8_t r, g, b, a; };

struct CHandle {
    uint32_t value;
    bool is_valid() const { return value != 0xFFFFFFFF; }
    uint32_t index() const { return value & 0x7FFF; }
    uint32_t serial() const { return value >> 15; }
};

struct ViewMatrix { float m[4][4]; };

} // namespace sdk
